### ISSUE TITLE
 Add search to the site

### ISSUE THREAD

**Issue by juliaelman** [uswds/uswds-site#100]
This idea proposal was submitting to us via email by Isabelle Giuong. Here is what she wrote:

> Reasons: As you add things to this wiki-like resource, it'll be more beneficial for users to search for specific things without having to spend a long time looking for it. The Android developers guide, used by Android devs in the tech industry, has a good example (https://developer.android.com/guide/index.html) and is very similar to your site.

**Comment by maya** [comment]
Your suggestion is appreciated, however it is not on the current product roadmap.
