### ISSUE TITLE
Publish sample contract language for 21st Century IDEA 

### ISSUE THREAD

**Issue by afeijoo** [uswds/uswds-site#1025]
This issue is a follow-up to #995. 

**Remaining to-do list includes:**
- [X] Content located [here](https://docs.google.com/document/d/1Dd5q9wgzSIqdgNcvslMPVFXPdYGEVLIX0HRvjuRy_JM/edit?usp=sharing)
- [X] Decide where to publish it. Publish on designsystem.digital.gov under `How to Use`
- [x] Create Github page
- [x] KPI: engagement w content. Metrics:  time on page - sessions - entrance - exit - 
- [x] Publish on designsystem.digital.gov as a new documentation page under `How to Use`

**Comment by jAigret-Bix** [comment]
@afeijoo  Can you please confirm: Build new page in `How to use USWDS` New page is titled: `Sample Contract Language for 21st Century IDEA`  [Final content is here](https://docs.google.com/document/d/1Dd5q9wgzSIqdgNcvslMPVFXPdYGEVLIX0HRvjuRy_JM/edit).

**Comment by afeijoo** [comment]
@jAigret-Bix Yes, that's the final, approved content and page title.

**Comment by jAigret-Bix** [comment]
@afeijoo  @katieekline  the team agrees on metrics for this page:  time on page - page views - entrance - exit - event tracking for scroll - event tracking for clicks. Can you let us know your thoughts and possible next steps? Do we work w Rhett to get these established  in GA?

**Comment by afeijoo** [comment]
@jAigret-Bix Yes, please coordinate with @RhettSkelton.

**Comment by afeijoo** [comment]
Published at https://designsystem.digital.gov/documentation/sample-contract-language/
