### ISSUE TITLE
Move the USWDS communities page from Digital.gov

### ISSUE THREAD

**Issue by afeijoo** [uswds/uswds-site#1041]
The USWDS community page is currently on Digital.gov at https://digital.gov/communities/uswds/.

To create a more seamless experience and reduce the amount of bouncing between the two sites, let's move the community page from Digital.gov to designsystem.digital.gov.

We'll need to coordinate this move with @saracope (https://github.com/GSA/digitalgov.gov/pull/3215), so they can redirect to our new page.

- [ ] create community page located: `about`
- [ ] light content edit @katieekline

**Comment by saracope** [comment]
I split this into a new PR: https://github.com/GSA/digitalgov.gov/pull/3244
