### ISSUE TITLE
Draft UXPA article (due Sept 25)

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds-site#1042]
September 25 - draft is due
You will find a template on the magazine site (http://uxpamagazine.org/editorial-guidelines/) that we’d like you to use to turn in your draft.. It’s got placeholders for all the bits and pieces like your bio, that we need along with the article. 

As you write, think about illustrations for your article.  We like to have a strong image near the start of the article, so don’t save all the good visuals for the end. 

[Submitted Pitch](https://docs.google.com/document/d/1eY9ydHMwopPTqnPlplYmQO62Xwzxh4BBGUJWBqMqTp8/edit)
* Tasks to Complete*
- [x] Katie to create an outline by 9/11
- [x] Review and feedback meeting scheduled 9/11
- [X] [First draft](https://docs.google.com/document/d/1W0UwPhqEpGfTwirARQShVVHev-uHi04y1kO86aygxzY/edit?usp=sharing) review, client approval, and possible comms review. 
- [ ] Final first draft and client approval (due by 9/25)

**Comment by jAigret-Bix** [comment]
First draft sent 9/17. https://docs.google.com/document/d/1W0UwPhqEpGfTwirARQShVVHev-uHi04y1kO86aygxzY/edit?usp=sharing

**Comment by afeijoo** [comment]
@thisisdano I left some comments and suggestions. It is ready for your review.

**Comment by afeijoo** [comment]
Pending review.

**Comment by jAigret-Bix** [comment]
https://github.com/uswds/uswds-site/issues/1061

**Comment by afeijoo** [comment]
Not submitting an article.
