### ISSUE TITLE
Add video clips to the banner blog post

### ISSUE THREAD

**Issue by afeijoo** [uswds/uswds-site#1053]
This is a follow-up task from https://github.com/uswds/uswds-site/issues/1035.

- [ ] Include [video clips from the July and August calls](https://drive.google.com/drive/u/2/folders/1dnOwoDxQjffLYhNmAnFL5nlwEMgctC7M) in the [banner blog post](https://designsystem.digital.gov/whats-new/updates/2020/09/08/Improvements-banner/).

**Comment by thisisdano** [comment]
We won't be adding video clips to the USWDS site
