### ISSUE TITLE
UXPA Article: Final Submission Oct 23

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds-site#1061]
Draft issue #1042
[Pitch submission](https://docs.google.com/document/d/1eY9ydHMwopPTqnPlplYmQO62Xwzxh4BBGUJWBqMqTp8/edit)
[Draft UXPA Article](https://docs.google.com/document/d/1W0UwPhqEpGfTwirARQShVVHev-uHi04y1kO86aygxzY/edit)

Template on the magazine site (http://uxpamagazine.org/editorial-guidelines/)  
**October  6** (Katie is out Oct 7-12)
**October 14** (comms/legal)
**October 23** - Final draft due for submission 

Once draft is received, we’ll assign someone from our editorial team to work with you. 
November - Publication.

- [ ] Receive edits on draft
- [ ] Revise draft
- [ ] client approval
- [ ] Comms and legal 
- [ ] submit to UXPA by Oct 23

**Comment by afeijoo** [comment]
Not submitting an article.
