### ISSUE TITLE
GSA branding on Public Sans website

### ISSUE THREAD

**Issue by afeijoo** [uswds/uswds-site#1067]
- [ ] Add the new `Identifer` component to the [Public Sans website](https://public-sans.digital.gov/) so it follows GSA branding guidelines per our [modernization plan](https://github.com/uswds/uswds-team/issues/7).
- [ ] Update the banner to 2.9.0

**Comment by thisisdano** [comment]
PR: https://github.com/uswds/public-sans/pull/174

**Comment by thisisdano** [comment]
Update! New PR: https://github.com/uswds/public-sans/pull/175

**Comment by thisisdano** [comment]
Updates are now live: https://public-sans.digital.gov/
