### ISSUE TITLE
Intro paragraph for Banner component

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds-site#1088]
New intro paragraph for Banner has been created. See preview [here](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-banner-intro/components/banner/#site-component-intro) 

- [X] create [draft intro](https://docs.google.com/document/d/1I6bHDbbLz28Hbamr2mL7ZRSSVqe7Wy5vv_iVleKRtSc/edit#heading=h.cwqvrw8xqdb1)
- [x] PR created: https://github.com/uswds/uswds-site/pull/1105
- [x] align w comms plan
- [x] client review 2.17
- [x] update and finalize PR

**DOD**
- [x] all tasked are complete
- [ ] new paragraph is published to banner component page

**Comment by katieekline** [comment]
@afeijoo and @thisisdano The [draft intro paragraph](https://docs.google.com/document/d/1I6bHDbbLz28Hbamr2mL7ZRSSVqe7Wy5vv_iVleKRtSc/edit?usp=sharing) for the banner guidance page is ready for your review.

**Comment by afeijoo** [comment]
@katieekline I left a few comments and suggestions in the [draft intro paragraph](https://docs.google.com/document/d/1I6bHDbbLz28Hbamr2mL7ZRSSVqe7Wy5vv_iVleKRtSc/edit?usp=sharing).

**Comment by katieekline** [comment]
Thank you @afeijoo! @thisisdano the [draft intro paragraph](https://docs.google.com/document/d/1I6bHDbbLz28Hbamr2mL7ZRSSVqe7Wy5vv_iVleKRtSc/edit?usp=sharing) is ready for your review.

**Comment by mejiaj** [comment]
I've created a [PR →](https://github.com/uswds/uswds-site/pull/1105)

You can view the preview [here →](https://github.com/uswds/uswds-site/pull/1105)

**Comment by katieekline** [comment]
@afeijoo and @thisisdano The revised banner introduction is ready for your review in the [core components comms plan](https://docs.google.com/document/d/1ySdXCiQ09K-IcSDOCCF4SrgWKE_U8dba4PJ6IbFJt_w/edit?usp=sharing).

**Comment by jAigret-Bix** [comment]
Revised banner page
Add to the introduction:
Banner is a core component along with identifier. We recommend using both components as they are the most recognizable and standardized design elements of a government site.

**Comment by jAigret-Bix** [comment]
@katieekline look at [preview page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-banner-intro/components/banner/#site-component-intro) for banner intro.  the "why use banner" section is the addition that was originally proposed. is this still accurate?  where is the "revised" two sentences going? Is it replacing that entire "why" section or going at the very end of it, or someplace else?  TY

**Comment by jAigret-Bix** [comment]
KC, KM, JA: review on 2/11. two additional new sentences to be added to proposed intro. requested James to update PR. then, it is ready for client review

**Comment by jAigret-Bix** [comment]
@thisisdano the new intro to the banner is created, ready for your final review. Per our discussion 2/17, we have removed the opening sentences that introduce it as a "core" component. we can add that in later when the core component page is created and published. @katieekline

**Comment by thisisdano** [comment]
This will be fixed in https://github.com/uswds/uswds-site/pull/1136
Closing the other open PR.

**Comment by thisisdano** [comment]
Banner intro preview: https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/dw-reorganize-components/components/banner/

Identifier intro preview: https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/dw-reorganize-components/components/identifier/
