### ISSUE TITLE
USWDS - Components: Create yml file for component variants.

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds-site#1091]
## Description

Variants don't exist in `_data`, so we can't generate tables for them on component pages. Instead, we have to create them manually.

Settings generate a table based on `yml` files in `_data/settings/components` For example, accordions:
```md
<h5 id="component-settings">Accordion settings</h5>
{% assign settings = site.data.settings.components.accordion %}
{% include settings-table-simple.html settings=settings.contents %}
```

We should do the same for variants.

## Additional information [optional]

Do we create a new `variants` folder in `_data` or rework component settings to take variants as well?

**Comment by thisisdano** [comment]
This is happening as a part of #1136
