### ISSUE TITLE
USWDS - a11y: Heading order.

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds-site#1108]
## Description

Related to #1104.

**id:** 'heading-order',
**impact:** 'moderate',
**tags:** [ 'cat.semantics', 'best-practice' ],
**description:** 'Ensures the order of headings is semantically correct',
**help:** 'Heading levels should only increase by one',
**helpUrl:** 'https://dequeuniversity.com/rules/axe/3.5/heading-order?application=axeAPI',

### Pages to fix
- [x] Typography
- [x] Tooltip
- [x] Tag
- [x] Table
- [x] Step indicator
- [x] Sidenav
- [x] Search
- [x] Identifier
- [x] Icons
- [x] Header
- [x] Form templates
- [x] Form controls
- [x] Footer
- [x] Data visualizations
- [x] Button groups
- [x] Button
- [x] Breadcrumb
- [x] Banner
- [x] Alert
- [x] Accordion

## Steps to reproduce the issue

1. Open `run-axe.js`
2. Add component URLs from #1104 to `const PAGES` array
4. `npm run axe`

**Comment by mejiaj** [comment]
Blocked by #1136

**Comment by thisisdano** [comment]
Perhaps fair to say that this is fixed by #1136
