### ISSUE TITLE
Document New Detector Script

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds-site#1120]
- [x] add detector script to the project (Dan has started this, look in develop branch, README)
- [x] document that the new script exists
- [x] document where it lives and where to insert it
- [x] client review
- [x] Dan implemented this for the 2.10.0 release. Issue can be closed.

**Comment by sarnikbixal** [comment]
Dan implemented this for the release already. I reviewed it and it has everything we need.
