### ISSUE TITLE
federalist-uswds-jekyll repository scan

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds-site#1123]
https://github.com/18F/federalist-uswds-jekyll repository has possible security vulnerabilities in its dependencies  To resolve, merge the open pull requests, then fix the outstanding alerts, or archive the repositoryhttps://github.com/18F/federalist-uswds-jekyll/pulls?q=is%3Apr+is%3Aopen+label%3Adependencies

https://gsa-tts.slack.com/archives/C3F14AHSQ/p1607965430362000
- [x] Validate vulnerabilities 
- [ ] [merge open PRs](https://github.com/18F/federalist-uswds-jekyll/pulls?q=is%3Apr+is%3Aopen+label%3Adependencies) JM 12/15: The only one that applied was the `ini` PR. I updated and created a PR: https://github.com/uswds/uswds-site/pull/1124. The rest are modules we don't use. 
- [ ] Final reviewer to cross reference with POAM 2020-030

**Comment by mejiaj** [comment]
We're not using the gems listed. I did create a PR #1124 to update `ini`.

**Comment by thisisdano** [comment]
Merged https://github.com/uswds/uswds-site/pull/1124 and `federalist-uswds-jekyll` is not our repo. 
@jAigret-Bix, please update the POAM and this will be all set.
