### ISSUE TITLE
Release notes: table displayed as raw markdown

### ISSUE THREAD

**Issue by asarazor** [uswds/uswds-site#1188]
## Description

In the release notes for v2.11.0 the settings table is not understandable. The table is served in raw markdown syntax.

## Steps to reproduce the issue

1. [View the settings changes in v2.11.0](https://designsystem.digital.gov/about/releases/#v2.11.0-settings)

### How it looks now
<img width="632" alt="image" src="https://user-images.githubusercontent.com/19854/111874444-ab194c80-896b-11eb-9922-4f3e73610189.png">

### How it should look
<img width="1361" alt="image" src="https://user-images.githubusercontent.com/19854/111881253-06583880-8986-11eb-8a38-447ba089817f.png">

## Possible solution

Add **a line-return** between `## Settings` and the table in the [release description](https://github.com/uswds/uswds/releases/tag/v2.11.0) on GitHub. Those descriptions are the data source, which are pulled into this Jekyll site via the GitHub API.

I don't believe I can PR something like that. But a manual test on my local version suggests that would fix it. Seems that Github Flavored Markdown is more forgiving than Jekyll's Kramdown here.

Unrelated: Thanks for writing such detailed release notes, I find them very helpful.

**Comment by mejiaj** [comment]
Thank you for reporting this!

**Comment by scottqueen-bixal** [comment]
yup, thanks @asarazor 

@mejiaj updated the release notes.  Should pull in once we deploy `uswds-site` again 👍 

![Screen Shot 2021-03-22 at 11 22 08 AM](https://user-images.githubusercontent.com/37077057/112014198-0cbeef80-8b01-11eb-9230-c76198ac7c52.png)

**Comment by asarazor** [comment]
Looks like the site was redeployed and the fix is in place. Closing 👍.
