### ISSUE TITLE
Fix the side nav for page templates

### ISSUE THREAD

**Issue by afeijoo** [uswds/uswds-site#1199]
## Description

Fix the jump links in the side nav for all the new page templates so the jump links work.

## Steps to reproduce the issue

1. Go to the 404 page template at https://designsystem.digital.gov/templates/404-page/
2. Click `Guidance` in the side nav
3. Note how it goes to https://designsystem.digital.gov/templates/404-page/#documentation-page-guidance and doesn't jump to the expected anchor link
4. Update the URL manually to the correct anchor link and note how it now jumps to the expected anchor link: https://designsystem.digital.gov/templates/404-page/#404-page-guidance

## Additional information [optional]

* This issue is happening on the page templates for both [404 page](https://designsystem.digital.gov/templates/404-page/) and [landing page](https://designsystem.digital.gov/templates/landing-page/).

**Comment by mejiaj** [comment]
Fixed in https://github.com/uswds/uswds-site/commit/7ad19f653f54fab851c1950f159d872b88848c19#diff-7d19facfdc9795de8de77358b309f7b1d6f2b54fd52a23a629a848da8a74d38a
