### ISSUE TITLE
Changelog: Prototype Component changelog/version/newsfeed

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-site#1280]
Let's develop a prototype of a Component changelog/newsfeed - what information would it hold, where would it live on a Component page, how would it look (in general)?

**Comment by amyleadem** [comment]
# Possible tasks:
Including some notes from our discussions for possible paths forward. 

✨  = candidate for MVP

## For GitHub: 
- ✨ Create template for component CHANGELOG.md
    - Related PR: https://github.com/uswds/uswds-team/pull/207
- ✨ Create a CHANGELOG.md for each component package

## For USWDS site
- ✨ Add the package version number to each component page, inside the Package section (when available)
- ✨ Create a "Changelog" or "Recent Updates" section at the bottom of guidance pages. This section could include:
    - ✨ For components, a link to the component CHANGELOG.md
    - ✨ For all pages, a list of change summaries
        -  Each item inside this list would include a date, 1-2 sentence summary, and a link to related PR
        - These items could include summaries of: 
            - Breaking or markup changes
            - High-level changes relating to usability, accessibility, performance guidance
            - OR All user-affected changes
            - Example: https://www.w3.org/TR/html-aria/#change-log
- Create posts in the "what's new" or "news and updates" section to explain significant shifts in guidance, and link to that content from the relevant page
    - Build trust by showing research and process
    - Possible example: Upcoming performance guidance update
- Create a CHANGELOG.md for the USWDS-Site repo that tracks significant changes in guidance

**Comment by amyleadem** [comment]
Some next steps identified during the team discussion:

- [ ] Evaluate header categories
    - Find alternative for "General"
    - Is there a better way to categorize? Bugs, Enhancements, etc 
- [ ] Edit guidance so that markup changes are not identified with the warning symbol
- [ ] Add contributor callout 
    - Contributors should be highlighted next to the item they contributed to, not as part of general release

**Comment by amyleadem** [comment]
Closing this issue and will create new issues for the remaining changelog tasks. 

USWDS-Site - Changelog prototype PR: https://github.com/uswds/uswds-site/pull/1753
USWDS-Team - Changelog.md prototype PR: https://github.com/uswds/uswds-team/pull/207
