### ISSUE TITLE
Validation of 1st iteration of Developer guide

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-site#1283]
Conduct user research with the 1st version of the Developer guide to inform a 2nd version (if needed).

**Methodology**
- [ ] Conduct at least 5 user interviews with new developers
- [ ] Post Federalist preview to GH Discussion to gather feedback
- [ ] Generate findings report in GDrive

**Comment by sofya-UX** [comment]
Our research process and approach are outlined in this Developers: Getting Started guide: test plan[https://docs.google.com/document/d/1pSxI6EyF5EY7OcPEb5uG53biDCeT7PlhHlX6KRmsJqc/edit#](url) on g-drive
