### ISSUE TITLE
Investigate sharing of Newsletter email template

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-site#1296]
- Figure out if sharing newsletter template is useful and possible. If so, how and where?
- Request was for an export of our USWDS email template. Could we export our GovDelivery version into a format that could be re-purposed? Who would find this useful?
- Is it worth doing for a percentage of our community & what would the LOE be?
- KM to check with Huck/GovDelivery on this process

**Comment by KMullan944** [comment]
KM posed this question in a case to Granicus: "Dan & I wanted to ask you how flexible our GovDelivery platform is when it generates a newsletter -- like for instance, could we export the content into a format that is more platform-agnostic, so if some in our community want to use Drupal to lay out that same content (and share on their site), would that be possible? Alternatively, if GovDelivery only generates HTML-based communications AND several of our partners use GovDelivery, is there a hub in the backend where we could upload our version of each newsletter, and they could pull it down for themselves in the format that works best for their audiences?

I have never seen a newsletter created with Drupal so I am not entirely sure if this question makes sense -- as I also don't know how flexible and robust GovDelivery is as a software program that can morph to various needs."

Matt Eckl's response: "Thanks for your question! This kind of functionality isn’t built into govDelivery natively, however we do have APIs which might be able to accomplish what you described. Here is a link to our API documentation: https://developer.govdelivery.com/api/comm_cloud_v1/Default.htm#API/Comm%20Cloud%20V1/API_CommCloudV1_Landing.htm

You would need a developer resource to assist, but it seems to be possible to do with this API, especially with the List Sent Bulletins command: https://developer.govdelivery.com/api/comm_cloud_v1/Default.htm#API/Comm%20Cloud%20V1/API_CommCloudV1_Bulletins_ListSentBulletins.htm%3FTocPath%3DCommunications%2520Cloud%2520API%2520v1%7CResources%7CBulletins%7C_____10

 Please let me know what you think, I am happy to loop in an API specialist from my side if you’d like to move forward with this."

**Comment by KMullan944** [comment]
Granicus case response: "A few questions: Will these other people be sending an email from govdelivery? Are you looking to leverage the existing email design as an email available for other folks to use? Are they going to be sending their email from govdelivery application? If all you are looking for is the html/css from that email template, I could just pass that over to you as a file and you could do with it as you please. Please let me know your vision."

**Comment by brunerae** [comment]
@KMullan944 from my perspective, I think the HTML/CSS would be great - thoughts, @thisisdano?

**Comment by brunerae** [comment]
To close this ticket, detail out learnings for sharing template. New issue can be created for executing share method.
