### ISSUE TITLE
Broken images and links in Collections

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds-site#1320]
The image on [USA Collection's preview](https://designsystem.digital.gov/components/collection/) is broken. It's the first example in **media thumbnail**.

![image](https://user-images.githubusercontent.com/3385219/142435625-93a094e4-8921-49c6-ba9f-c7e896c40c29.png)

## Additional information
The links that point to performance.gov are broken.

**Comment by amyleadem** [comment]
Repaired broken links with updated urls. 

Pull request found here:
https://github.com/uswds/uswds/pull/4405
