### ISSUE TITLE
Landscape analysis of other Designer getting started documentation

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-site#1353]
Conduct a landscape analysis of how other design systems present and communicate getting started guidance for designers.

**Comment by brunerae** [comment]
Potential resource as flagged by @thisisdano : https://design.va.gov/documentation/designers

**Comment by sofya-UX** [comment]
The landscape analysis report can be found [at this g-drive link](https://docs.google.com/presentation/d/1QfNlctVyPA82J6dPNNNSkViGc2Rj54oZ/edit#slide=id.p12)
