### ISSUE TITLE
Confirm templates are consistent with handling of required fields

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-site#1354]
Review templates to ensure they are consistent in their handling of required fields.  (https://designsystem.digital.gov/templates/)

**Comment by mejiaj** [comment]
@brunerae only the [Sign in form →](https://designsystem.digital.gov/templates/form-templates/sign-in-form/) needs to be updated. This template is also used in the [Sign in Page layout](https://designsystem.digital.gov/templates/authentication-pages/sign-in/).

**Comment by mejiaj** [comment]
I've updated the Sign in form template in this PR to reflect that. PR https://github.com/uswds/uswds/pull/4417

**Comment by brunerae** [comment]
Not ready to merge in #4417 so moving this issue to backlog.
