### ISSUE TITLE
ALT Text for the United States Flag on the Banner Components Page

### ISSUE THREAD

**Issue by jfc3-dol** [uswds/uswds-site#1357]
## Description

To make the small the United States flag in the four different code examples more readable for those using assistive technologies like a screen reader, shouldn't the ALT text for the United States flag on the Banner Components page ( https://designsystem.digital.gov/components/banner/ ) be "**United States flag**" instead of "**U.S. flag**" since some assistive technologies might not read it out properly?

**Comment by jfc3-dol** [comment]
After looking at other pages, such as the Header component, the code examples have the same issues.

The change will need to be made on multiple component pages and the different packages that USWDS has.

So this problem is a slightly larger fix than  I first thought it might be when I created the issue.

**Comment by thisisdano** [comment]
According to https://www.deque.com/blog/dont-screen-readers-read-whats-screen-part-1-punctuation-typographic-symbols/ JAWS, NVDA, and VoiceOver will all read a period as a short pause, resulting the expected voicing of `U.S. flag`. I'm not inclined to change this until we hear that this voicing is not what our users expect.

**Comment by jfc3-dol** [comment]
@thisisdano,

My concern is that people might not know what "U.S." is referring too, but if you changed it to "United States" they would have no doubt.
