### ISSUE TITLE
Confusing Text on the Button Group Page

### ISSUE THREAD

**Issue by jfc3-dol** [uswds/uswds-site#1358]
## Description

There is confusing text on the Button Group page ( https://designsystem.digital.gov/components/button-group/ ). The following text is "there are several ways modify how the default button group is displayed." is missing the word "to". Please see the corrected text with the word "to" in bold text "there are several ways **to** modify how the default button group is displayed."

**Comment by bonnieAcameron** [comment]
Looks like someone caught this in passing in the time since it was reported. Closing as fixed.
