### ISSUE TITLE
Collection Component Page - Image No Longer Found in Example Code Section

### ISSUE THREAD

**Issue by jfc3-dol** [uswds/uswds-site#1373]
## Description

On the Collections page  (https://designsystem.digital.gov/components/collection/ ), in the "Component Preview" section, the image related to the heading "Gears of Government President’s Award winners" is not found. For now, the ALT text is being displayed in its place.

I'm assuming they removed it or changed the URL structure.

Here is the link to the image - https://www.performance.gov/img/GoG/gears-govt-presidents.png

**Comment by mejiaj** [comment]
Hey, thanks for reporting this! We recently fixed this issue in https://github.com/uswds/uswds/pull/4416.
