### ISSUE TITLE
[Date Picker] Link is Getting "This site can’t be reached" Message

### ISSUE THREAD

**Issue by jfc3-dol** [uswds/uswds-site#1375]
## Description

On the date picker page ( https://designsystem.digital.gov/components/date-picker/ ), while clicking the "date input" link ( //components/date-input ), the user will see the "This site can’t be reached" message on the next page.

The issue is likely that there are two slashes in front of the URL instead of only one.

NOTE - There is more than one "date input" link on the page.

I assume it's because the link is not fully formed/missing something.

**Comment by thisisdano** [comment]
I can't find the issue on the Date Picker page. Perhaps the content changed since this issue was reported.
