### ISSUE TITLE
Footer Component Page - Text Says It's a Link But Not Coded as a Link

### ISSUE THREAD

**Issue by jfc3-dol** [uswds/uswds-site#1379]
## Description

On the Footer Component page ( https://designsystem.digital.gov/components/footer/ ), in the "Big Footer" section, the text says it's a link ( <Primary link> ), but it is not coded as a link. This applies in the "Component Preview" (footer example) and the "Component Code" sections. 

I would expect the bold text to be a heading as it's coded in the Large Footer section, but the text does not say it's a link then. Something like "Section Heading" could work if it's not a link. Also, since the text said they were links, I expected to be able to tab to them.

Below is the code for one of the four pieces of text in the "Big Footer" section. Other similar code can be found in the "Medium footer" or "Slim Footer" example as a link.

**Incorrect Code Not a Link**

`<h4 class="usa-footer__primary-link">&lt;Primary link&gt;</h4>`

**Correct Code as a Link**

`<a class="usa-footer__primary-link" href="javascript:void(0);">&lt;Primary link&gt;</a>`

**Comment by thisisdano** [comment]
This now says `[Topic]` and not `Primary link`
