### ISSUE TITLE
Pagination Page - Missing Period at End of Sentence

### ISSUE THREAD

**Issue by jfc3-dol** [uswds/uswds-site#1390]
## Description

On the Pagination Page (https://designsystem.digital.gov/components/pagination/ ), there is a missing period at the end of the sentence. For the text below, I assume there should be a period after the word "Set" and before the capitalized word  "Each" which is under the heading "Behaviors".

we call this paginated content a set Each item in the set

**Comment by brunerae** [comment]
https://github.com/uswds/uswds-site/pull/1632
