### ISSUE TITLE
Process List Page - Link Redirects to t Different Page

### ISSUE THREAD

**Issue by jfc3-dol** [uswds/uswds-site#1391]
## Description

On the Process List Page ( https://designsystem.digital.gov/components/process-list/ ), the "side navigation" link redirects to a different page ( https://designsystem.digital.gov/components/side-navigation/ ). You might want to save the redirect by fixing the URL.

**Comment by bonnieAcameron** [comment]
Hi there @jfc3-dol! When I tested this, both the link to Side Navigation in the page body and the side navigation on the page (confusingly meta, here!) direct to where I would expect: https://designsystem.digital.gov/components/side-navigation/

Can you clarify what your expectation was? Thank you so much for catching all of these errors!

**Comment by jfc3-dol** [comment]
@bonnieAcameron,

The link in the following sentence- "In-page navigation. Use the side navigation **`https://designsystem.digital.gov/components/sidenav`** component to display the “sub-navigation” within a section or page of the website."

As you can see the URL goes to "sidenav" and not "side-navigation". So it's getting redirected since it changed. Think it would be better to save the redirect step.
