### ISSUE TITLE
Compile Findings from Leadership GS research

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-site#1409]
Host an ideation session that compiles findings from Getting Started for Leadership research and defines approach.

**Comment by sofya-UX** [comment]
[Mural board ](https://app.mural.co/t/gsa6/m/gsa6/1633627979224/1f5d6224dac6eb33eedb761a20b2ca8ff541d55a?sender=uf90a6e8e2ff5dc4049236267)(synthesis/service blueprint)

Concept/outline testing [Raw notes and recording]:(https://drive.google.com/drive/u/0/folders/1EdauM06S1Sj3SSQqaCxIi8Dd6-TLYP80): g-folder
