### ISSUE TITLE
Write research plan for IA assessment

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-site#1437]
Write a research plan for the IA assessment. 

-- What data are we using?
-- Do we need to complete any new research activities?
-- What is the timeline?

**Comment by bonnieAcameron** [comment]
https://docs.google.com/document/d/1PzQGBCNIWd6l7fXQRuqZ0oWBLQegRLVh9PkZbEwxm_A/edit#heading=h.pr4v8wy05ayq
