### ISSUE TITLE
Draft script for Designer GS user interviews

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-site#1442]
Draft a script to use in Designer Getting Started user interviews.

**Comment by sofya-UX** [comment]
Completed section [7.Discussion guide of research plan](https://docs.google.com/document/d/1RAp7nyAwZfMjNE9HMD9cM4nud6SL8avqzZZCYXTtWDw/edit#heading=h.9dm7dfxgwzey) 🔒
