### ISSUE TITLE
High level analysis of workflows in GA

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-site#1446]
In Google Analytics, examine stats and behaviors to form quantitative understanding of workflows and journeys on site.

**Comment by bonnieAcameron** [comment]
Link to [What do people come to our site to do? ](https://analytics.google.com/analytics/web/?authuser=1#/dashboard/rCoNKbe5TmCA0sr1jWkQSA/a48605964w116904186p122266996/)

**Comment by bonnieAcameron** [comment]
[How do people move through the site](https://analytics.google.com/analytics/web/?authuser=1#/dashboard/MtQJ7LFhSQmMn07M4kRngA/a48605964w116904186p122266996/)? (need to add more capability for event tracking)
[Behavior flow](https://analytics.google.com/analytics/web/?authuser=1#/report/content-engagement-flow/a48605964w116904186p122266996/)
