### ISSUE TITLE
Identify where pattern library will live in IA

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-site#1459]
Identify where pattern library information will live in IA

**Comment by bonnieAcameron** [comment]
2 Options laid out here: https://docs.google.com/spreadsheets/d/1SDSjWHKMuMf_0MxnAb-B_ulH5OQlmjisdAnWeXS47yY/edit#gid=442281973

**Comment by thisisdano** [comment]
Let's proceed with Option 1 and fold `Templates` into `Patterns`
