### ISSUE TITLE
display-none not displayed in docs because class is applied as example

### ISSUE THREAD

**Issue by jduss4** [uswds/uswds-site#1498]
## Description

When I visit the [display](https://designsystem.digital.gov/utilities/display/) utility documentation, I expect to learn about a class that hides elements. While there are other display classes at the top, `.display-none` is not obvious because when it is applied to an element it is, in fact, not displayed...therefore you can't see it in the documentation.

The only mention of `.display-none` is in the component code section, which people may miss unless they are looking closely for it.

I am wondering if there is an alternate way to indicate that `display-none` is an available class?

## Steps to reproduce the issue

1. Visit https://designsystem.digital.gov/utilities/display/
2. Visually look at the top of the documentation page for examples and usage of "display"

## Additional information

![image](https://user-images.githubusercontent.com/2480492/161310954-997a623e-14e0-4867-bfb1-5aaecffe775d.png)

(alt text: display classes applied to elements to demonstrate their appearance, which does not include `.display-none`, followed by the code which does show `.display-none` applied to a div)

**Comment by brunerae** [comment]
Hey @jduss4! Just letting you know we've seen this and have pulled it into our backlog for attention!
