### ISSUE TITLE
Add Rails Implementation

### ISSUE THREAD

**Issue by ExMember** [uswds/uswds-site#1499]
I've created a new implementation of the USWDS. James Mejia suggested it'd be a good addition to the implementations page. According to the [implementations page](https://designsystem.digital.gov/documentation/implementations/) this is a good way to add it to that list.

[USWDS components](https://github.com/TalariaSoftware/uswds_components)
Framework: Rails
Author: [Damien Burke (Talaria Software)](https://talariasoftware.com)
Target: USWDS version 2.12
Notes: An implementation of USWDS for Rails applications using [View Components](https://viewcomponent.org). [Demo](https://uswdscomponents.herokuapp.com/rails/view_components)

**Comment by brunerae** [comment]
Awesome, thank you so much @ExMember! I've added this to the backlog.
