### ISSUE TITLE
Update Readme for 3.0

### ISSUE THREAD

**Issue by bonnieAcameron** [uswds/uswds-site#1514]
What: updates from V2 to V3
Where: USWDS repository readme file

Context: this came up in the site audit, beginning on this page:
https://designsystem.digital.gov/documentation/developers/
Documentation | U.S. Web Design System (USWDS)

Which, in GitHub, appears to pull most of the content in through the readme.md on the **uswds repostitory**.
So when I entered into the readme, there were a lot of changes I didn't feel comfortable making/suggesting, since many of them were 1) links 2) javascript or even 3) potentially pulling in content from (another) source

 I wanted to get your eyes on the readme changes that may be pulling into other pages that I haven't identified yet.

**Comment by mejiaj** [comment]
@mahoneycm or @amyleadem we'll have to do the following tasks: 

- [ ] Update references in USWDS's [README.md](https://github.com/uswds/uswds/blob/develop/README.md)
- [ ] Create a test branch here that uses that updated README branch from USWDS [(How to install specific branch ℹ️)](https://github.com/uswds/uswds-site#updating-the-uswds-version)

**Comment by thisisdano** [comment]
Done
