### ISSUE TITLE
Write intro to 3.0 for Site

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-site#1515]
Write an intro for 3.0 that will go on Site. This will summarize the release and be accompanied by the migration guide.

**Comment by bonnieAcameron** [comment]
Draft here @thisisdano : https://docs.google.com/document/d/1TE2D9wO4A3H0QV0D2sxiINvTKMAZx7wWpfmRB4kEAsw/edit#heading=h.8p85x32pit41
