### ISSUE TITLE
Readme Updates for V3

### ISSUE THREAD

**Issue by bonnieAcameron** [uswds/uswds-site#1525]
Context: V3 Content Updates

There are several updates to the readme file that is pulled into the Designers Documentation page.

Affected Location: How to Use USWDS > Documentation page
URL: https://designsystem.digital.gov/documentation/developers/
GitHub: https://github.com/uswds/uswds-site/blob/v3-content-updates/pages/documentation/developers.md

Please see the list of changes needed for V3 in this spreadsheet:
https://docs.google.com/spreadsheets/d/1xhshfcXHI3u0UCQFTl5alWbELJovedf9/edit#gid=33939255

Feel free to reach out with questions!

**Comment by brunerae** [comment]
https://github.com/uswds/uswds/pull/4633
