### ISSUE TITLE
Add breaking changes back to 2.10.1 to Migration Guide

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-site#1588]
In [Migration Guide](https://docs.google.com/document/d/1SwoD7jychCEfeDptfxe6zOFt5eE4AyH7glEeIyr-2VU/edit#heading=h.6g4xhcvk7bhi), add a list of all breaking changes by version. We expect to add to this list over time.

**Comment by thisisdano** [comment]
This is in the current migration guide as of USWDS 3.0.0
