### ISSUE TITLE
Migration guide links to v2.x theme tokens

### ISSUE THREAD

**Issue by sawyerh** [uswds/uswds-site#1593]
It's possible this is intentional, and might be more of a content phrasing confusion, but the [Migration guide](https://designsystem.digital.gov/documentation/migration/) mentions "the most current version of the USWDS default settings" and then lists links that point to assets in the `2.13.3` release. Since it mentioned "the most current version", I was expecting these to link to `v3.x` assets:

<img width="684" alt="CleanShot 2022-05-11 at 11 03 17@2x" src="https://user-images.githubusercontent.com/371943/167882957-caa9a01c-ae5c-41c0-9995-578e4b708207.png">

**Comment by thisisdano** [comment]
This was intentional, but perhaps a mistake. Our hope was to convey that `3.0` settings are the same as `2.13.3` settings, but it makes sense to either link to the `3.0` defaults or be more clear why these link to `2.13.3`. 
cc @bonnieAcameron
