### ISSUE TITLE
SPIKE: Fold templates into patterns section

### ISSUE THREAD

**Issue by jonadecker** [uswds/uswds-site#1699]
For consideration...should the templates section be folded into the patterns section?

Currently:

- [404 page](https://designsystem.digital.gov/templates/404-page/)
- [Documentation page](https://designsystem.digital.gov/templates/documentation-page/)
- [Landing page](https://designsystem.digital.gov/templates/landing-page/)
- [Authentication pages](https://designsystem.digital.gov/templates/authentication-pages/) - includes [Create account](https://designsystem.digital.gov/templates/authentication-pages/create-account/), [Sign-in](https://designsystem.digital.gov/templates/authentication-pages/sign-in/), [Multiple sign-in options](https://designsystem.digital.gov/templates/authentication-pages/multiple-sign-in-options/)
- [Form templates](https://designsystem.digital.gov/templates/form-templates/) - includes [Address form](https://designsystem.digital.gov/templates/form-templates/address-form/), [Name form](https://designsystem.digital.gov/templates/form-templates/name-form/), [Password reset form](https://designsystem.digital.gov/templates/form-templates/password-reset-form/), &  [Sign-in form](https://designsystem.digital.gov/templates/form-templates/sign-in-form/)

**Comment by jonadecker** [comment]
- Address & Name dovetail nicely into patterns. Auth to a lesser extent
- Documentation page could be a good demo for in-page navigation?

**Comment by jonadecker** [comment]
Identify where things need to change and what recommendations we have based on patterns for core team.

**Comment by thisisdano** [comment]
We're leaving patterns and templates separate for now
