### ISSUE TITLE
SPIKE: Icon for invoking language picker

### ISSUE THREAD

**Issue by jonadecker** [uswds/uswds-site#1700]
Is there a well-understood and communicative icon that could be used as part of a language selector menu and potentially stand alone? Related to #1580

**Comment by jonadecker** [comment]
[Top 10 Best Practices for Multilingual Websites](https://digital.gov/resources/top-10-best-practices-for-multilingual-websites/)

**Comment by jonadecker** [comment]
![Image](https://user-images.githubusercontent.com/1735772/177412209-8dd0f9ef-5b80-442f-bc76-b9f5f51b9a02.png)
![Image](https://user-images.githubusercontent.com/1735772/177412210-3d65e6dd-85a5-4dec-99f0-398d2ac0b7e2.png)

**Comment by jonadecker** [comment]
![Image](https://user-images.githubusercontent.com/1735772/177412561-adc241d0-1f32-4f02-a30f-68b780819e8e.png)
![Image](https://user-images.githubusercontent.com/1735772/177412564-5baed5be-5259-40db-b517-149e2bf41cd2.png)

**Comment by jonadecker** [comment]
![Image](https://user-images.githubusercontent.com/1735772/177412586-56c827b9-dc6e-42f4-9c25-c9362c45be7e.png)
![Image](https://user-images.githubusercontent.com/1735772/177412588-42df8c0c-d285-4b8e-bb89-4e2aa28caeff.png)
![Image](https://user-images.githubusercontent.com/1735772/177412587-e2039ecb-15c9-41f0-8f1e-a79f43d3fbeb.png)

**Comment by jonadecker** [comment]
![Image](https://user-images.githubusercontent.com/1735772/177412609-a7fdd312-f3e0-4e77-9592-caae8bcbb5bd.png)
![Image](https://user-images.githubusercontent.com/1735772/177412610-98c5bba2-ba62-4695-ae93-a23c0408e124.png)
![Image](https://user-images.githubusercontent.com/1735772/177412611-c1296298-6a4c-4d29-8a37-824ffb959891.png)

**Comment by jonadecker** [comment]
![Image](https://user-images.githubusercontent.com/1735772/177413488-778a0005-42f7-4eef-a371-c16d986f84a1.png)
![Image](https://user-images.githubusercontent.com/1735772/177413489-8d8ba06c-52f4-41e7-a519-3ed44e849f16.png)
![Image](https://user-images.githubusercontent.com/1735772/177413491-129dc8d2-15b4-4129-8e63-d1d17ca83d83.png)
![Image](https://user-images.githubusercontent.com/1735772/177413490-fba968b3-caf2-43a6-95a9-7639022c9f8b.png)

**Comment by thisisdano** [comment]
Completed

**Comment by caseywatts** [comment]
I've been researching this a bit too, and I think the most likely recognized icon for languages is probably the globe icon that is used on many smartphone keyboards.

There was a thread in the a11y Slack that discussed icon options. The globe icon seemed to be the group's consensus by the end of the thread.
https://web-a11y.slack.com/archives/C071U5Y3H/p1773581954167839

<img width="48" height="48" alt="Image" src="https://github.com/user-attachments/assets/6627849a-20c5-4a88-b610-94765683962d" />

The other option mentioned is the "google translate" icon with the A and a Mandarin Chinese character. These accessibility professionals believe that that icon is less universally understood than the globe icon.

<img width="48" height="48" alt="Image" src="https://github.com/user-attachments/assets/2e79ec2a-6623-4c3e-a6c1-0313cf826879" />

It sounds like the globe icon is more widely used/understood in 2026 -- I believe it!
