### ISSUE TITLE
Create metrics for CSAT on uswds-site

### ISSUE THREAD

**Issue by bonnieAcameron** [uswds/uswds-site#1707]
We have been capturing data on CSAT via touchpoints since early 2022. We can track the volume and value of this feedback on a monthly basis to provide a "health check" on the performance and helpfulness of the design system's website. 

To complete:

- [x] Add touchpoints volume metric to metrics board
- [x] Add touchpoints value (csat) metric to metrics board
- [x] Fill out the data from the last several months of tracking

**Comment by bonnieAcameron** [comment]
Done: https://docs.google.com/spreadsheets/d/1VNJ-U0I8I4u30Nce4GE0u58jj_YTeNjG4Wm77Vrd07U/edit#gid=1800287171

Net CSAT = Yes (assigned value of 1) + No (assigned value of -1)

**Comment by thisisdano** [comment]
DONE
