### ISSUE TITLE
Add Bonnie as an "editor" in Google Analytics

### ISSUE THREAD

**Issue by bonnieAcameron** [uswds/uswds-site#1721]
Steps to complete:

1. Go to Analytics > Admin
2. Find Account/18F Column
3. Select "Account Access Management"
4. Verify whether you have permission to make @bonnieAcameron  an "editor"
5. If not, you may need to reach out to one of the 4 account admins listed in "Account Access Management" > "View Organization Admins"

**Comment by brunerae** [comment]
Closing as no longer needed.
