### ISSUE TITLE
USWDS-Site - Bug: Inability to consistently stand up uswds-site locally. 

### ISSUE THREAD

**Issue by mitchmoccia** [uswds/uswds-site#1745]
### Describe the bug

Attempting to stand up uswds-site locally throws a variety of eventmachine-related errors.

### Steps to reproduce the bug

1. fresh clone of uswds-site repo
2. run the commands
- gem install bundler
- bundle install
- npm install
- npm start
3. the site runs inconsistently, tried on the M1 and it didn't work, then tried on the Mac intel and it worked initially, however switching branches causes issues
4. checkout working branch e.g. jb-patterns-complete-a-profile
5. merge main into working branch
6. npm install, npm start causes errors
7. errors appear to be mostly eventmachine related e.g.:
- The `SortedSet` class has been extracted from the `set` library.You must use the `sorted_set` gem or other alternatives. (RuntimeError)
- set.rb:540:in `delete`: cant modify rbtree during iteration (TypeError)
- `bind': Address family not supported by protocol family - bind(2) 

### Expected Behavior

The uswds-site should run locally without issue.

### Screenshots

![image](https://user-images.githubusercontent.com/19338309/184850702-266f3585-c216-465d-a7ec-cf5449d34c1c.png)

### System setup

Attempted / tested on three different machines:
Mac M1 running Monterey version 12.4
Mac Intel running Monterey version 12.4
Surface running Windows 10

### Additional context

On the windows machine, the error is different:
buildUSWDSComponents errored after 24ms
Error: Error: Spawn npm ENOENT
at ChildProcess.<anonymous> ... build.js:27:16

On the Macs, eventmachine errors:
~/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:8:in `require': dlopen(~/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/eventmachine-1.2.7/lib/rubyeventmachine.bundle, 0x0009): symbol not found in flat namespace '_BIO_ctrl' - ~/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/eventmachine-1.2.7/lib/rubyeventmachine.bundle (LoadError)

Some of the other things I've tried:

Full uninstall of eventmachine:
gem uninstall -aIx eventmachine
rm -rf vendor/cache

Added this to Gemfile
gem 'eventmachine'
bundle install

npm cache clean --force
rm -fr node_modules
rm -f package-lock.json
npm install

npm config set legacy-peer-deps true

Error: Failed to load plugin 'import' declared in '--config': Cannot find module 'eslint'
npm link eslint

Sorted set errors

Added this to Gemfile
gem 'sorted_set'
bundle install

Added this to the following file
~/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/eventmachine-1.2.7/lib/em/pure_ruby.rb
require 'sorted_set'

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds-site/issues) for duplicate bug reports.

**Comment by mitchmoccia** [comment]
Some more info... Just tried another fresh clone and this time I removed eventmachine first with this command:

ruby --version
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-darwin21]

Error 1:
Error: Failed to load plugin 'import' declared in '--config': Cannot find module 'eslint'

Solution:
npm link eslint
This temporarily fixes this error

Error 2:
~/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/eventmachine-1.2.7/lib/em/pure_ruby.rb:37:in `require': cannot load such file -- sorted_set (LoadError)

Solution:
I found a few possible solutions but tried them before and they didn't help like:
Add this to Gemfile
gem 'sorted_set'
bundle install

Added this to the following file
~/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/eventmachine-1.2.7/lib/em/pure_ruby.rb
require 'sorted_set'

I'm stuck at this error. This was from a fresh clone, switching to new branch and running:
gem install bundler
bundle install
npm install
npm start

**Comment by mitchmoccia** [comment]
UPDATE: I completely uninstalled rbenv and Ruby which was installed with homebrew
I finally got RVM installed despite some key server issues.
Installed Ruby 3.0.2 with RVM and made it a little farther... Had to also do the following:

Ran into some OpenSSL issues... TL;DR OpenSSL3 did not work, had to use OpenSSL1.1

**THIS IS WHAT ULTIMATELY WORKED**
brew install openssl@1.1

brew --prefix openssl@1.1         /usr/local/opt/openssl@1.1

rvm install 3.0.2 --with-openssl-dir=/usr/local/opt/openssl@1.1

gem uninstall eventmachine

bundle config build.eventmachine --with-openssl-dir=$(brew --prefix openssl@1.1)

bundle

npm run serve       Success!

**Comment by amyleadem** [comment]
Glad you were able to get it working! Big thanks for sharing the solution here.
