### ISSUE TITLE
USWDS-Site - Changelog: Mock-up changelog with real content for a component

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-site#1776]
Use real content/updates for a component to mock-up changelog.

**Comment by amyleadem** [comment]
Mockup changelogs with real content for the following pages:
- Accessibility (guidance)
- Accordion (component)
- Banner (component)
- Pattern page (TBD)

**Comment by amyleadem** [comment]
Closing and moving focused changelog work to `al-changelog-main` and PR https://github.com/uswds/uswds-site/pull/1870
