### ISSUE TITLE
Combobox: visual treatment for documenting unknowns/problems/need for additional research within patterns, components

### ISSUE THREAD

**Issue by jonadecker** [uswds/uswds-site#1778]
Design visual treatment for informational notices on patterns and components when communicating unknowns, problems, and/or a need for additional research. Relates to #1777 

_While this is specific to the combobox, it is the start of establishing a design convention for noting unknowns, problems, and/or a need for additional research on other patterns and components._

**Comment by thisisdano** [comment]
Completed
