### ISSUE TITLE
Combobox: replace pattern examples/code with select

### ISSUE THREAD

**Issue by jonadecker** [uswds/uswds-site#1779]
Update combobox address pattern examples, code replacing combobox with select.

**Comment by jonathanbobel** [comment]
Preview: https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/jb-change-combobox-to-select/

**Comment by thisisdano** [comment]
Completed
