### ISSUE TITLE
Language selector component: incorporate sync feedback

### ISSUE THREAD

**Issue by jonadecker** [uswds/uswds-site#1780]
Takeaways from sync with Dan:

- Simplify link structure to allow link semantics to drive screenreader (no aria-label, no title)
- Add English language label after native language label in list-item, e.g., Español (English)

**Comment by mitchmoccia** [comment]
This is complete. aria-label and title have been removed and the text content updated to "Native language (English translation)"

https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/mm-language-selector/?path=/story/components-language-selector--three-or-more-languages

![Image](https://user-images.githubusercontent.com/19338309/192785288-15e7f625-bbfd-4537-811a-3ca6342ba972.png)

**Comment by thisisdano** [comment]
Completed
