### ISSUE TITLE
Language selector patterns: incorporate sync feedback

### ISSUE THREAD

**Issue by jonadecker** [uswds/uswds-site#1781]
Takeaways from sync with Dan:

- Simplify link structure to allow link semantics to drive screenreader (no aria-label, no title)
- Add English language label after native language label in list-item, e.g., Español (English)

Takeaways from sync with ML-COP

- Weave in mission support
- Consider how to display notice of "Reco based on current knowledge/more research required" (see related work in issue #1777)
- Consider how to illustrate topic vs. language (vs. text description only - is the October MC "selected content" artwork a starting point?)

**Comment by thisisdano** [comment]
Completed
