### ISSUE TITLE
USWDS-Site - Bug: Side navigation with anchor links not working

### ISSUE THREAD

**Issue by pglevy** [uswds/uswds-site#1793]
### Describe the bug

- Links in the side navigation that link to anchors on the same page are not "jumping" to those anchors as expected. For example: https://designsystem.digital.gov/documentation/developers/#accessibility
- This only seems to occur when I'm on the site. Interestingly, it _does_ work as expected when opening a new, blank tab and going directly to the URL.
- I've tried Chrome, Firefox, and Safari on Mac. Also Chrome on Windows.

### Steps to reproduce the bug

1. Go to https://designsystem.digital.gov/
2. Click on `How to use USWDS` in the main nav
3. Click on `Documentation` in the side nav
4. Click on `Accessibility` (or any other anchor link) in the second-level side nav

Unexpected behavior: The URL reflects the anchor link, but the page does not "jump" to that heading.

### Expected Behavior

I expect the page to "jump" down to that heading on the same page.

### Screenshots

<img width="1608" alt="Screen Shot 2022-10-02 at 3 13 28 PM" src="https://user-images.githubusercontent.com/5177337/193472076-e1286945-9701-4056-a10c-d6c71fac8390.png">

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds-site/issues) for duplicate bug reports.

**Comment by amyleadem** [comment]
@pglevy Thank you for flagging this! Our team will take a look and will schedule this as soon as we are able.
