### ISSUE TITLE
USWDS-Site - Feature: remove federalist/build checks from branches

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds-site#1801]
### Is your feature request related to a problem? Please describe.

Since we migrated from Federalist to pages.cloud.gov `federalist/build` status checks are blocking PR merges.

### Describe the solution you'd like

Remove `federalist/build` status check requirement in Github repo branch settings.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds-site/issues) for duplicate feature requests.

**Comment by thisisdano** [comment]
OK, swapped `federalist/build` with `pages/build` on all protected branches in our org

**Comment by mejiaj** [comment]
Thank you! Closing this issue.
