### ISSUE TITLE
Together report: large pull quote incorporated into intro page

### ISSUE THREAD

**Issue by jonadecker** [uswds/uswds-site#1821]
Evaluate existing "small quote" style for suitability. Iterate on design as needed to incorporate long-form quote on intro page of Together report

**Comment by fpigeonjr** [comment]
Came up with a couple variations via props to the `together-quote` component.
`top-icon="true"` will add the quote icon on top of the block-quote.
`hide-icon="true"` will hide all quote icons.

![SCR-20221012-krp](https://user-images.githubusercontent.com/4629398/195439717-3e3d11e7-4d4e-4e7c-8697-7bfa63ba241d.png)
![SCR-20221012-ktv](https://user-images.githubusercontent.com/4629398/195439722-f4a36c5a-a3ee-49d5-9f2a-0225c76dfecc.png)
