### ISSUE TITLE
USWDS-Site - Changelog: Generate data rollout plan

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-site#1830]
### Prepare data files [Complete]
- [x] Related issue: #1858 
- [x] Create data files for all component pages and planned guidance pages
- [x] Set them up with the appropriate data template
- [x] Fill in values for `title` and `type`

### Begin adding all new updates
- Update component page changelogs as part of the release process
- Update guidance page changelogs with each guidance update

:warning: Note: once first changelog item is added, we must add the "Latest update" link to the side navigation

### Add historical changes
1. [x] **Phase 1: Add release/code changes to component pages, release 3.2.0 - 2.11.0** 
    - Split up work between Amy, Charlie, and James
    - Assign by component
        - [Spreadsheet: changelog items identified by release and component](https://docs.google.com/spreadsheets/d/16W0IO8gTW3yv47Dy9sUBAkEAkvVzpOYQpg2R9C6CM5s/edit#gid=0)
    - Opened the following issues for component data entry: 
        - #1865 
        - #1863 
        - #1864 
2. [ ] **Phase 2: Add guidance changes to component pages for dates 2021-03-17 - present (equivalent of 2.11.0 - 3.2.0)**
     - Assign by component
     - Data will be added in the following PR: 
        - #1895
3. [ ] **Phase 3: Template pages, releases 3.3.0 - 2.10.0**
     - [Spreadsheet: template data items](https://docs.google.com/spreadsheets/d/16W0IO8gTW3yv47Dy9sUBAkEAkvVzpOYQpg2R9C6CM5s/edit#gid=2036251212)
     - Data will be added in the following PR:
         - #1917 
4. [x] **Phase 4: Guidance pages, 2021-03-16 - present**
    - [Spreadsheet: guidance page data items](https://docs.google.com/spreadsheets/d/16W0IO8gTW3yv47Dy9sUBAkEAkvVzpOYQpg2R9C6CM5s/edit#gid=1432939193)
    - Data will be added in the following PR:
         - #1919 
6. [ ] **Phase 5: Additional components releases, TBD**    - Possible paths:
    - Back to 2.10.0/Dec 17, 2020 
        - This solution covers all updates for 2022 and 2021
        - [Spreadsheet: component data items 2.11.0 - 2.10.0](https://docs.google.com/spreadsheets/d/16W0IO8gTW3yv47Dy9sUBAkEAkvVzpOYQpg2R9C6CM5s/edit#gid=232365673)
    - Back to component creation ([Spreadsheet: component creation](https://docs.google.com/spreadsheets/d/16W0IO8gTW3yv47Dy9sUBAkEAkvVzpOYQpg2R9C6CM5s/edit#gid=2003683185))
    - Other?

**Comment by amyleadem** [comment]
## Notes
1. Set up files for all component pages with data template

**Comment by amyleadem** [comment]
@thisisdano How far back would you like to go for historical changelog data? Phases 1-4 add data from the `uswds` and `uswds-site` repo from the present back to USWDS 2.11.0/March 16, 2021. Would you like to include more? I have listed some possibilities in "Phase 5" in the description above.

**Comment by thisisdano** [comment]
I think the farthest back we need to go is USWDS 2.0.0 — and I think that should be the goal of Phase 5
