### ISSUE TITLE
SPIKE: UAT suite: component candidates for UAT

### ISSUE THREAD

**Issue by jonadecker** [uswds/uswds-site#1836]

**Comment by mitchmoccia** [comment]
The need for a standalone UAT site is essential for testing new components. We have utilized uswds-sandbox (Zombie apocalypse) and public-sans (language selector) for testing / demoing; however, a more complex structure is needed. 

For example, in-page navigation ideally would be tested on a page with a left side navigation present. This is to primarily test if keyboard users can effectively navigate a page with multiple navigation landmarks, potentially three (header, left nav, in-page nav).

One thought was to clone uswds-site and create a scaled down version strictly for testing purposes. 

A couple questions:
- would this create an unnecessary maintenance burden
- is there an existing repo that can be used that contains the left side nav structure

**Comment by jonadecker** [comment]
- [ ] Input mask (perhaps current state/future state?)
- [ ] Date picker
- [ ] Time picker
- [ ] Pattern previews

**Comment by thisisdano** [comment]
Completed. Using sandbox.
