### ISSUE TITLE
UAT suite: site/pages for testing purposes

### ISSUE THREAD

**Issue by jonadecker** [uswds/uswds-site#1837]
UAT Rd. 1: [Vaccination appointment scheduler](https://federalist-d5e7c07c-6ffa-4b8e-935f-49a7df24a505.sites.pages.cloud.gov/preview/uswds/uswds-sandbox/jb-schedule-appointment/) preview
UAT Rd. 2: [Training sign-in](https://federalist-d5e7c07c-6ffa-4b8e-935f-49a7df24a505.sites.pages.cloud.gov/preview/uswds/uswds-sandbox/jb-zombie-defense-training/) preview
UAT Rd. 3: [Training course evaluation](https://federalist-d5e7c07c-6ffa-4b8e-935f-49a7df24a505.sites.pages.cloud.gov/preview/uswds/uswds-sandbox/jb-zdt-course-evaluation/) preview

**Comment by jonadecker** [comment]
Use existing components to explore a "create an appointment" story - evaluate what's working, what's an opportunity for improvement.

A/B test (potentially) input mask as part of this (thinking MHN or similar)

**Comment by mitchmoccia** [comment]
Options for UAT site implementation:
- uswds-sandbox
- public-sans
- uswds-site (scaled down version, good having left side nav)

**Comment by jonadecker** [comment]
Sandbox 👍

**Comment by thisisdano** [comment]
Completed
