### ISSUE TITLE
Clarify relationship between Standards Sass + Bourbon + Neat

### ISSUE THREAD

**Issue by juliaelman** [uswds/uswds-site#184]
@manavm1990 pointed out to us the need to clarify the relationship between the Standards Sass files and the Bourbon/Neat libraries, [see this issue](https://github.com/18F/web-design-standards/pull/1737). We should take a look at our documentation to help explain more about how these all co-exist and compile into our Standards distributed assets.

**Comment by maya** [comment]
We will hope to sunset our dependence on Bourbon, so this can be closed.
