### ISSUE TITLE
Add page title to 404 template

### ISSUE THREAD

**Issue by bonnieAcameron** [uswds/uswds-site#1852]
it would improve accessibility if we added a page title to our 404 template. To do that, we'd just need to add a title to the front matter (lines 3-5). Something like this:

```
layout: default
permalink: /404.html
title: "Page not found"
touchpoints_survey: false
```

2. Additionally, I wonder if it would be helpful to give users clear instructions on how to search for what they need - maybe just give them directions to use the search bar in the nav?

_Originally posted by @amyleadem in https://github.com/uswds/uswds-site/pull/1802#pullrequestreview-1130553908_

**Comment by thisisdano** [comment]
Fixed in https://github.com/uswds/uswds-site/pull/1802
