### ISSUE TITLE
Update plain language and clarity in 404 template

### ISSUE THREAD

**Issue by bonnieAcameron** [uswds/uswds-site#1853]
Reflect these changes in #1802 in the [USWDS 404 template](https://designsystem.digital.gov/templates/404-page/) recommendations.
- In order to align with the on-site work, we'd need to complete the following tasks:
    - [ ] update the data in `usa-error.json` in the USWDS repo.
    - [ ] update the screenshots on https://designsystem.digital.gov/templates/404-page/ (once we have language finalized). 
    - [ ] Investigate if the [spanish template](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/develop/iframe.html?id=pages-error--page-not-found-spanish&args=&viewMode=story) copy also should be updated (Thinking mostly about the new line about search)

_Originally posted by @amyleadem in https://github.com/uswds/uswds-site/issues/1802#issuecomment-1267600933_

**Comment by amyleadem** [comment]
Closing because https://github.com/uswds/uswds-site/pull/1802 was merged and issue [#4980](https://github.com/uswds/uswds/issues/4980) was created to update USWDS with this change.
