### ISSUE TITLE
USWDS-Site - Feature: Update the in-page nav design to be more clear and meaningful

### ISSUE THREAD

**Issue by bonnieAcameron** [uswds/uswds-site#1931]
### Is your feature request related to a problem? Please describe.

Problem: The right-side nav and the in-page navigation appear at the same height on the page. When the left and right side navigation duplicate each other or closely mirror each other, it can be overwhelming or confusing to tell which information is telling me what. What's the distinction between right and left side navigation?

![91CDDE6B-0E7B-4E3C-9072-A1E2D983BCDC](https://user-images.githubusercontent.com/96838068/205319441-ecf51e3b-f402-477b-a9ef-1d1c45f54b12.jpeg)

### Describe the solution you'd like

1. The in-page nav could appear at a lower "height" to indicate that it is "in page" rather than a "site level" navigation tool, like the nav on the left
AND/OR
2. There could be additional visual distinction (simple partial border, shadow etc) to indicate this is part of the page rather then site-level.

 [See this example from Slack's documentation site](https://slack.com/help/articles/360047512554-Use-channel-management-tools). 
[See this example from the Atlassian design system](https://atlassian.design/components/banner/examples)

### Describe alternatives you've considered

1. Put the in-page nav above the content rather than in a right-side bar, OR
2. Remove left-side nav altogether

### Additional context

The [component documentation for in-page nav](https://designsystem.digital.gov/components/in-page-navigation/) may need to be updated to reflect this guidance. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds-site/issues) for duplicate feature requests.

**Comment by mejiaj** [comment]
### Related issues

- https://github.com/uswds/uswds-site/issues/1944
- https://github.com/uswds/uswds-site/issues/1930
