### ISSUE TITLE
USWDS-Site - Content audit: Create plan to audit developer documentation

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds-site#1954]
## Summary
Create an audit plan to verify the code references in our developer documentation.

**Comment by amyleadem** [comment]
## Draft notes

### Check instructions
- [ ] Documentation
    - Identify if content is redundant with/could belong in another section of the site
    - Confirm that Instructions are accurate and current
    - [ ] Installation
    - [ ] Compiling USWDS Sass into CSS
    - [ ] JS Customization
    - [ ] Style theming and tokens
    - [ ] CSS Architecture
    - [ ] Browser support
    - [ ] Accessibility
    - [ ] Long-term support of v1.x
    - [ ] Long-term support of v2.x
    - [ ] Need installation help?
    - [ ] Contributing t the code base?

### Check values and keys
- [ ] Settings
    - [ ] Test each code example in a test project. Confirm that instuctions make sense, that example code is current, works as expected, and do not cause error.
    - [ ] Confirm that all settings exist in USWDS
    - [ ] Confirm that all USWDS settings are listed
    - [ ] Confirm that listed settings defaults match the USWDS system defaults
    - [ ] Confirm that custom values can be added without error
- [ ] Tokens
    - [ ] Confirm values on site match values in USWDS
    - [ ] Test each value in the noted mixin or function
    - [ ] Overview
    - [ ] Color
    - [ ] Typesetting
        - [ ] Font family
        - [ ] Font size
        - [ ] Font weight
        - [ ] Letterspacing
        - [ ] Line height
        - [ ] Measure/Line length
            - Use `measure()`
    - [ ] Flex
    - [ ] Opacity
    - [ ] Order
    - [ ] Shadow
    - [ ] Spacing units
        - use `units()`
    - [ ] Z-index
- [ ] Utilities
    - [ ] Layout grid
    - [ ] Color
    - [ ] Height and width
    - [ ] Margin and padding
    - [ ] Border
    - [ ] Outline
    - [ ] Font size and family
    - [ ] Text styles
    - [ ] Paragraph styles
    - [ ] Display
    - [ ] Flex
    - [ ] Shadow
    - [ ] Float
    - [ ] Clearfix
    - [ ] List reset

## Optional?
- [ ] Check component instructions and code

**Comment by amyleadem** [comment]
This is the proposed plan for auditing the code references on the settings, tokens, utilities, and components pages. 

I have flagged the items that would involve a higher level of effort, and consider those to be optional paths. Before beginning the audit, we should decide if these are mandatory paths.

Please note that I have not included an audit plan for pages in the "How to use USWDS" section at this time because because of both the relatively high level of effort and the fact that this was recently updated with the release of USWDS 3. If you think it should be included, please let me know. 

Please review this list and share if there are any items missing or any items that should be removed. 

Once the plan is finalized, we can create new issues to break out the work into smaller pieces and assign according to work load and priority. 

# Proposed plan

## Audit instructions
Our aim is to verify that all code references in our documentation pages are up-to-date and work with the current version of USWDS. In general, this means that we should: 
1. Confirm that all code references exist in the current version of USWDS and are used correctly.
1. Confirm that all code snippets can be used in a project without error.
1. Confirm that all step-by-step instructions make sense and can be completed without error.

This plan also provides specific instruction for each section that applies only to that page type. See the page types section for more details.

Note: These items are not dependent on one another and can be worked on and merged individually if needed. This list should be broken into several issues so that it can be completed incrementally.

## Remediation
We should open new issues for all discrepancies and errors. The issue title should be written in the following format for easy reference: `USWDS-Site - Code audit: [brief description of issue]`

## Page types
### Tokens
1. Confirm that all tokens listed on site exist in USWDS.
1. Confirm that all USWDS tokens are listed on site.
1. Check that each token example displays visually as expected.
1. (High level of effort) Test each settings, mixin, and function code example.
- [ ] [Overview](https://designsystem.digital.gov/design-tokens/)
- [ ] [Using color](https://designsystem.digital.gov/design-tokens/color/overview/)
- [ ] [Theme colors](https://designsystem.digital.gov/design-tokens/color/theme-tokens/)
- [ ] [State colors](https://designsystem.digital.gov/design-tokens/color/state-tokens/)
- [ ] [System colors](https://designsystem.digital.gov/design-tokens/color/system-tokens/)
- [ ] [Using type](https://designsystem.digital.gov/design-tokens/typesetting/overview/)
- [ ] [Font family](https://designsystem.digital.gov/design-tokens/typesetting/font-family/)
- [ ] [Font size](https://designsystem.digital.gov/design-tokens/typesetting/font-size/)
- [ ] [Font weight](https://designsystem.digital.gov/design-tokens/typesetting/font-weight/)
- [ ] [Letterspacing](https://designsystem.digital.gov/design-tokens/typesetting/letterspacing/)
- [ ] [Line height](https://designsystem.digital.gov/design-tokens/typesetting/line-height/)
- [ ] [Measure (Line length)](https://designsystem.digital.gov/design-tokens/typesetting/measure/)
- [ ] [Flex](https://designsystem.digital.gov/design-tokens/flex/)
- [ ] [Opacity](https://designsystem.digital.gov/design-tokens/opacity/)
- [ ] [Order](https://designsystem.digital.gov/design-tokens/order/)
- [ ] [Shadow](https://designsystem.digital.gov/design-tokens/shadow/)
- [ ] [Spacing units](https://designsystem.digital.gov/design-tokens/spacing-units/)
- [ ] [Z-index](https://designsystem.digital.gov/design-tokens/z-index/)

### Settings
1. Confirm that all settings listed on site exist in USWDS.
1. Confirm that all USWDS settings are listed on site.
1. Confirm that the listed defaults match USWDS
1. Confirm that the listed name, type, and description make sense.
1. (High Level of effort) Confirm that each setting can be configured with custom values according the instructions without error
- [ ] [Overview](https://designsystem.digital.gov/documentation/settings/)
- [ ] [General settings](https://designsystem.digital.gov/documentation/settings/#general-settings)
- [ ] [Color settings](https://designsystem.digital.gov/documentation/settings/#color-settings)
- [ ] [Component settings](https://designsystem.digital.gov/documentation/settings/#component-settings)
- [ ] [Spacing settings](https://designsystem.digital.gov/documentation/settings/#spacing-settings)
- [ ] [Typography settings](https://designsystem.digital.gov/documentation/settings/#typography-settings)
- [ ] [Utilities settings](https://designsystem.digital.gov/documentation/settings/#utilities-settings)

### Utilities
1. Confirm that all utilities listed on site exist in the USWDS defaults.
1. Confirm that all USWDS default utilities are listed on site.
1. Check that all visual examples display as expected.
1. (High level of effort) Check that each utility class works as expected.
- [ ] [Overview](https://designsystem.digital.gov/utilities/)
- [ ] [Layout grid](https://designsystem.digital.gov/utilities/layout-grid)
- [ ] [Color](https://designsystem.digital.gov/utilities/color/)
- [ ] [Height and width](https://designsystem.digital.gov/utilities/height-and-width/)
- [ ] [Margin and padding](https://designsystem.digital.gov/utilities/margin-and-padding/)
- [ ] [Border](https://designsystem.digital.gov/utilities/border/)
- [ ] [Outline](https://designsystem.digital.gov/utilities/outline/)
- [ ] [Font size and family](https://designsystem.digital.gov/utilities/font-size-and-family/)
- [ ] [Text styles](https://designsystem.digital.gov/utilities/text-styles)
- [ ] [Paragraph styles](https://designsystem.digital.gov/utilities/paragraph-styles/)
- [ ] [Display](https://designsystem.digital.gov/utilities/display/)
- [ ] [Flex](https://designsystem.digital.gov/utilities/flex/)
- [ ] [Shadow](https://designsystem.digital.gov/utilities/shadow/)
- [ ] [Float](https://designsystem.digital.gov/utilities/float/)
- [ ] [Clearfix](https://designsystem.digital.gov/utilities/clearfix/)
- [ ] [List reset](https://designsystem.digital.gov/utilities/list-reset/)

### Components
1. Confirm that listed component settings match USWDS
1. Confirm that listed component variants match USWDS
1. Confirm that listed component aria and data attributes match USWDS
1. Confirm component package name and package dependencies match USWDS
- [ ] [Accordion](https://designsystem.digital.gov/components/accordion/)
- [ ] [Alert](https://designsystem.digital.gov/components/alert/)
- [ ] [Banner](https://designsystem.digital.gov/components/banner/)
- [ ] [Breadcrumb](https://designsystem.digital.gov/components/breadcrumb/)
- [ ] [Button group](https://designsystem.digital.gov/components/button-group/)
- [ ] [Button](https://designsystem.digital.gov/components/button/)
- [ ] [Card](https://designsystem.digital.gov/components/card/)
- [ ] [Character count](https://designsystem.digital.gov/components/character-count/)
- [ ] [Checkbox](https://designsystem.digital.gov/components/checkbox/)
- [ ] [Collection](https://designsystem.digital.gov/components/collection/)
- [ ] [Combo box](https://designsystem.digital.gov/components/combo-box/)
- [ ] [Date picker](https://designsystem.digital.gov/components/date-picker/)
- [ ] [Date range picker](https://designsystem.digital.gov/components/date-range-picker/)
- [ ] [File input](https://designsystem.digital.gov/components/file-input/)
- [ ] [Footer](https://designsystem.digital.gov/components/footer/)
- [ ] [Header](https://designsystem.digital.gov/components/header/)
- [ ] [Icon list](https://designsystem.digital.gov/components/icon-list/)
- [ ] [Icon](https://designsystem.digital.gov/components/icon/)
- [ ] [Identifier](https://designsystem.digital.gov/components/identifier/)
- [ ] [In-page navigation](https://designsystem.digital.gov/components/in-page-navigation/)
- [ ] [Input mask](https://designsystem.digital.gov/components/input-mask/)
- [ ] [Input prefix/suffix](https://designsystem.digital.gov/components/input-prefix-suffix/)
- [ ] [Language selector](https://designsystem.digital.gov/components/language-selector/)
- [ ] [Link](https://designsystem.digital.gov/components/link/)
- [ ] [List](https://designsystem.digital.gov/components/list/)
- [ ] [Memorable date](https://designsystem.digital.gov/components/memorable-date/)
- [ ] [Modal](https://designsystem.digital.gov/components/modal/)
- [ ] [Pagination](https://designsystem.digital.gov/components/pagination/)
- [ ] [Process list](https://designsystem.digital.gov/components/process-list/)
- [ ] [Prose](https://designsystem.digital.gov/components/prose/)
- [ ] [Radio buttons](https://designsystem.digital.gov/components/radio-buttons/)
- [ ] [Range slider](https://designsystem.digital.gov/components/range-slider/)
- [ ] [Search](https://designsystem.digital.gov/components/search/)
- [ ] [Select](https://designsystem.digital.gov/components/select/)
- [ ] [Side navigation](https://designsystem.digital.gov/components/side-navigation/)
- [ ] [Site alert](https://designsystem.digital.gov/components/site-alert/)
- [ ] [Step indicator](https://designsystem.digital.gov/components/step-indicator/)
- [ ] [Summary box](https://designsystem.digital.gov/components/summary-box/)
- [ ] [Table](https://designsystem.digital.gov/components/table/)
- [ ] [Text input](https://designsystem.digital.gov/components/text-input/)
- [ ] [Time picker](https://designsystem.digital.gov/components/time-picker/)
- [ ] [Tooltip](https://designsystem.digital.gov/components/tooltip/)
- [ ] [Typography](https://designsystem.digital.gov/components/typography/)
- [ ] [Validation](https://designsystem.digital.gov/components/validation/)

**Comment by amyleadem** [comment]
@thisisdano @mejiaj @mahoneycm @brunerae 
In the comment above, I created a plan to verify that the code references on our site at up-to-date and accurate. Please let me know if you have any questions or comments.

**Comment by mejiaj** [comment]
@amyleadem no questions, the plan looks good!

**Comment by thisisdano** [comment]
I agree with @mejiaj — this is comprehensive and ready to go!
