### ISSUE TITLE
Add OCC.gov, helpwithmybank.gov and careers.occ.gov to Showcase

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-site#2115]
Add the following Sites to Showcase:

https://occ.gov/
https://helpwithmybank.gov/
https://careers.occ.gov/

**Comment by finekatie** [comment]
Sarah had already made these changes and yesterday we committed the changes. Waiting to see if that went through. If so, this will be complete. I have another ticket to do full audit on all the links on the page.

**Comment by finekatie** [comment]
Sarah and I talked today. She's adding this to Office Hours for 11/21 because we can't figure out what happened with this.

**Comment by finekatie** [comment]
relates to #2318

**Comment by finekatie** [comment]
Approved #2272 so this can be closed.
