### ISSUE TITLE
USWDS-Site - Bug: In-Page Navigation targets Collection links

### ISSUE THREAD

**Issue by mahoneycm** [uswds/uswds-site#2137]
### Describe the bug

In-page navigation is currently targeting all links within the Collection component.

### Steps to reproduce the bug

1. Visit the Collection component page
2. Scroll down and view in-page navigation

### Expected Behavior

In-page Navigation should ignore the component preview links/headings and only target guidance headings

### Screenshots

<img width="1123" alt="image" src="https://github.com/uswds/uswds-site/assets/25211650/1d0cabea-f8f2-4a18-b182-fea51d7caa59">

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds-site/issues) for duplicate bug reports.

**Comment by amyleadem** [comment]
Closing this issue as resolved with the merge of PR https://github.com/uswds/uswds-site/pull/2021

Updated collection page: https://designsystem.digital.gov/components/collection/
