### ISSUE TITLE
Created new accessible research signup form in Microsoft forms

### ISSUE THREAD

**Issue by jaclinec** [uswds/uswds-site#2142]
we have a "Community of Testers" research signup form originally created in Google forms. We heard feedback at the April monthly call that some people could not access our original form. Some govt agencies do not use Google products, so we needed to find a different tool to host the form.

We decided to use Microsoft Forms since they are accessible to anyone with the link. So, we had to re-create the Google form/import into Microsoft Forms and edit it for new content (for instance, we wanted to specify that only federal employees could sign up).

**Comment by jaclinec** [comment]
I finished the new [Microsoft version of the signup form.](https://forms.office.com/r/DrYNkBJ3pu)

**Comment by thisisdano** [comment]
We'll use Qualtrics the next time we do this.
