### ISSUE TITLE
Identify where on the site disabled styles guidance needs to be added or updated

### ISSUE THREAD

**Issue by jaclinec** [uswds/uswds-site#2144]
Once the research/literature review is completed  (#2157) and the team has discussed possible next steps for what we want to recommend for guidance, we will document what pages on the USWDS site may need updated or added guidance on disabled states. In other words, we will identify the components, patterns, and templates where the guidance may apply.

**Comment by jaclinec** [comment]
Possible components, patterns, and templates that may need disabled states guidance: https://docs.google.com/document/d/11K16g1qmqh9aU-ebSFtn_WRCVjB6lmBVLno5Vs854Ig/edit?usp=sharing

Need to discuss if these are the best next steps:

1. Write ‘overall’ guidance on our stance with disabled styles (i.e. Don't use them, what to do instead)
2. Give narrow instances where it is ok to use them - 

- Unavailable states like appointment scheduling (date range, date picker), future steps in step indicator
- Processing/Loading - Avoid submitting a form several times

3. See what we recommend for specific components:

- Never disable form inputs
- Buttons can be disabled sometimes for processing
- Date picker/range - can be disabled for future/unavailable appointments
- Step indicator - future steps can be disabled

4. For those instances where it’s ok to use disabled states, give appropriate best practices to use for the specific scenario and component, template, or pattern

**Comment by jaclinec** [comment]
We've had a discussion as a team and have identified where on the site disabled styles guidance may be needed. This work is continuing in #2108 .

**Comment by thisisdano** [comment]
Done
