### ISSUE TITLE
USWDS-Site - Component lifecycle: Update contribution page

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds-site#2150]
> **Note**
> Originating this based on the comment from @bonnieAcameron in the proposal PR: https://github.com/amyleadem/uswds-proposals/pull/1#issuecomment-1604359498

> This should also be on the uswds site (eventually). Right now we have [Contribute](https://designsystem.digital.gov/about/contribute/) which feels like a V1 of what you're doing here, and I'll think we'll need to revise this to add some nuance or replace altogether. We should have a larger conversation about that, possibly at CS/UX sync.

We should update the [Contribute](https://designsystem.digital.gov/about/contribute/) page to include any relevant component lifecycle information.

**Comment by finekatie** [comment]
This is in process. Sarah and I working on copy.

**Comment by sarah-sch** [comment]
Copy was sent to Dan for review on 2/9/2024. Still needs to be entered into GitHub and reviewed there.

**Comment by amyleadem** [comment]
Marking this as complete after merging https://github.com/uswds/uswds-site/pull/2491/
