### ISSUE TITLE
USWDS - Guidance: Clarify role of custom color tokens

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds-site#2153]
It's not always clear where custom colors come into play when customizing USWDS.

**Questions to answer**
1. Is the intention to eventually have all agencies use only the USWDS colors on all websites?
2. Many agencies have their own official color scheme as part of their style guide, so is USWDS supposed to override those colors when they publish a website?

**Current guidance**
Color [token guidance](https://designsystem.digital.gov/design-tokens/color/overview/#:~:text=Use%20USWDS%20color,USWDS%E2%80%99s%20design%20tokens.) says:

>Use USWDS color tokens, and avoid custom colors whenever possible. Creating coherent government sites and services helps provide a good user experience to the public. Of course, your mission, project needs, and user needs always come first, but if you plan to contribute your work back into the system — which helps the system learn, adapt, and improve — that work will need to conform to system standards and use USWDS’s design tokens.

**Code example**
https://github.com/uswds/uswds-site/blob/4342599e25795ae9d6af0b51730ecf7830ad60e4/pages/design-tokens/color/overview.md#L34

### Additional context

Original discussion in [public slack](https://gsa-tts.slack.com/archives/C3F14AHSQ/p1687806679101339).

**Comment by brunerae** [comment]
Closing as not needed.
