### ISSUE TITLE
Create informed consent form for August 2023 component testing

### ISSUE THREAD

**Issue by jaclinec** [uswds/uswds-site#2155]
An informed consent form, or participation agreement, is a necessary step in the research process. It informs participants on the purpose of the study, what to expect, how their information will be used and protected, that participation is voluntary, and also asks for their permission to record the session. It allows users to make an informed decision on whether or not they want to participate in our research.

I will create a draft of the consent form that we will use for the upcoming July usability testing of several components (e.g. combo box, accordion, date range picker, etc.)

**Comment by jaclinec** [comment]
Draft of the consent form: https://forms.gle/fekHLdL9twPvR2yB9

**Comment by annepetersen** [comment]
This is a no-compensation round? (noting the "no compensation" item near the end)

**Comment by jaclinec** [comment]
Good catch - nope that is just a mistake. I copied and modified this from the consent form we did for content testing (which was not compensated). I thought I removed all that working but missed that. Should be removed now. Thanks!
