### ISSUE TITLE
Showcase - Include www.sfhsa.org

### ISSUE THREAD

**Issue by alex-hsa** [uswds/uswds-site#2156]
The Human Services Agency in San Francisco released its new website using the USWDS this week:
https://www.sfhsa.org

Kindly add the sfhsa.org to the Showcase page at:
https://designsystem.digital.gov/documentation/showcase/

Thank you very much,
Alexander Ismail
alexander.ismail@sfgov.org

**Comment by brunerae** [comment]
Hi @alex-hsa ! Thanks for submitting this. Unfortunately, we're only able to feature .gov/.mil websites on our Showcase.
