### ISSUE TITLE
USWDS-Site: Review research page

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds-site#2188]
## Summary 
We should review the content on the [research page](https://designsystem.digital.gov/about/research/) to confirm that the content is still relevant and accurate. 

For example, the "about our work" link suggests that users will get information on USWDS metrics, but the link points to the "What's new" page.

We also removed a reference link in https://github.com/uswds/uswds-site/pull/2185 that we should consider replacing. 

## Related PR
Related PR that removed a broken reference link: https://github.com/uswds/uswds-site/pull/2185

**Comment by jaclinec** [comment]
@cathybaptista  I don't see a quarterly report section on the research page, could you please clarify?

**Comment by annepetersen** [comment]
@jaclinec I think the reference was to "[How often we do research](https://designsystem.digital.gov/about/research/#how-often-we-do-research-2)" here, but may also be relevant to [line 24 here](https://docs.google.com/spreadsheets/d/1KPPHXr5YhV2Zyl-c9fZh6NB-kKgXyzgBZyIhio-97OA/edit?gid=0#gid=0)

**Comment by jaclinec** [comment]
I think this is an old issue that was created before we rewrote the entire research page and launched it in November 2023. I think the "How often we do research" section can remain as-is for now since we do intend to test that often. We haven't been able to keep that pace since other priorities came up, but I think its a good goal to have.

**Comment by amyleadem** [comment]
@jaclinec, I agree that this looks like an outdated issue. You can see from the [cloud pages preview](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-500-error/about/research/) in the related PR (#2185) that the page had a much different format at the time this issue was created. I believe this issue should be safe to close now.

**Comment by amyleadem** [comment]
Closing this as completed  in PR #2355
