### ISSUE TITLE
Review draft of publicly shareable disabled states research findings to publish to site and Github

### ISSUE THREAD

**Issue by jaclinec** [uswds/uswds-site#2243]
Continues the work from #2108 

We aim to share research findings of the recent disabled states literature review publicly on our site on relevant pages (forms-related component, template, and pattern). 

I've drafted the [research findings Github wiki content](https://docs.google.com/document/d/1VP6HHXE0diVQBqYBdQhhLDo489V2DtbI9xrF031nJ-I/edit?usp=sharing) that we may link to from the site. We are following the model we used for the [Link component research findings in the Github wiki](https://github.com/uswds/uswds/wiki/2021-07-29-External-Link-Indicator-Research-Findings). For now it is just a draft in a Google doc. We can move it to the wiki when it's a final draft.

**Comment by jaclinec** [comment]
Thank you @annepetersen for already reviewing and revising the content. Please, @thisisdano and one Content Strategist should also take a pass @bonnieAcameron @sarah-sch

**Comment by bonnieAcameron** [comment]
This looks great, @jaclinec. I've added my comments in the doc. cc' @sarah-sch

**Comment by jaclinec** [comment]
The [disabled states research findings shareable draft ](References list)has been reviewed by CS and a11y team members, and suggestions have been accepted in the document. Marking this issue as complete.

Next step: Determining where this should go in the Github wiki and building it out there.

**Comment by thisisdano** [comment]
Done
