### ISSUE TITLE
Disabled States: Phase 1 guidance rollout

### ISSUE THREAD

**Issue by jaclinec** [uswds/uswds-site#2246]
Phase 1 disabled states site [content](https://docs.google.com/document/d/1M1h6hLsLqhDtJb5S9NXjO4M4AKeoNjEiogtKiL59wk8/edit?usp=sharing) to update:

- Complete a complex form - [Progress easily pattern](https://designsystem.digital.gov/patterns/complete-a-complex-form/progress-easily/)
- Form templates (THIS WILL UPDATE BASED ON CHANGES WE MAKE TO FORM COMPONENT. SEE COMMENTS BELOW - KF 8/23)
- [Form component](https://designsystem.digital.gov/components/form/)

### Steps required to complete this work

- [x] Content strategy team aligns on text
- [x] Text review by UX and accessibility team
- [x] Text review by federal team
- [x] Update complete a complex form [progress easily pattern]  (https://designsystem.digital.gov/patterns/complete-a-complex-form/progress-easily/) -  PR: [2744 ](https://github.com/uswds/uswds-site/pull/2744)
- [x] Update [form component](https://designsystem.digital.gov/components/form/) guidance - PR: [2776](https://github.com/uswds/uswds-site/pull/2776)

**Comment by jaclinec** [comment]
I created a [draft of the guidance](https://docs.google.com/document/d/1M1h6hLsLqhDtJb5S9NXjO4M4AKeoNjEiogtKiL59wk8/edit?usp=sharing) for those sections of the site and it is ready for content strategy to review, edit, and publish to the site.

**Comment by brunerae** [comment]
@brunerae and @sarah-sch to come back and breakdown this Issue

**Comment by finekatie** [comment]
Reviewed draft and made comments today. (12/1)

**Comment by sarah-sch** [comment]
12/13 discussed with Katie plan to align on text recommendations by end of week and pass on to team for review by 12/18.

**Comment by finekatie** [comment]
reviewed draft again after Sarah's work

**Comment by sarah-sch** [comment]
Will pass draft to Jacline and accessibility team week of 12/18.

**Comment by jaclinec** [comment]
I reviewed it and accepted most suggestions and added comments. It's shaping up really nicely!

**Comment by sarah-sch** [comment]
UX and accessibility reviewed content team's changes week of 12/18. Katie and Sarah giving text one more pass before handing off to fed team for review.

**Comment by finekatie** [comment]
Anne has been looking at this with us as of 12/17. Still one or two more queries to resolve.

**Comment by finekatie** [comment]
This is still in review and will move to next sprint, I suppose?

**Comment by sarah-sch** [comment]
Let's pick review back up with federal team next sprint. Cc @finekatie

**Comment by finekatie** [comment]
@sarah-sch and I discussed today and I took a quick peek. Would like Anne to revisit since there were comments after their last review. @annepetersen can you take a look?

**Comment by annepetersen** [comment]
Will start resolving changes to look at the cleanest closest-to-final copy now

**Comment by annepetersen** [comment]
Still a few queries to resolve in there, but it's looking good. Back to you, @sarah-sch and @finekatie. 

Realizing that moving to FFR might have been premature, FWIW, but we're still figuring out the details there

**Comment by sarah-sch** [comment]
@annepetersen - picking this issue back up. I'm thinking it might most expeditious to lay the text out on our first guidance page (progress easily pattern) and get @thisisdano review on the PR. Does that plan work for the fed team? cc @finekatie and @jaclinec

**Comment by sarah-sch** [comment]
Passing to @thisisdano for FFR on 5/1/2024

**Comment by sarah-sch** [comment]
Literature review had been approved by Dan. Slate review of website update copy by @thisisdano for sprint starting 5/2/2024.

**Comment by thisisdano** [comment]
Content approved. Moving back to `In Progress` to move it into production

**Comment by finekatie** [comment]
hi @brunerae , I'm revisiting. Looks like copy is ready to be added to the site now and I just need to do PRs to get the pages updated. Is that correct?

**Comment by brunerae** [comment]
Hey @finekatie - correct!!

**Comment by finekatie** [comment]
First PR created today for Progress Easily: https://github.com/uswds/uswds-site/pull/2744

I also asked team for guidance on where pieces of new content will live. Here's the request I sent today:
Hey team, I am ready to work on PRs for adding the [Disabled States content](https://docs.google.com/document/d/1M1h6hLsLqhDtJb5S9NXjO4M4AKeoNjEiogtKiL59wk8/edit) to the following pages:
Complete a complex form - [Progress easily pattern](https://designsystem.digital.gov/patterns/complete-a-complex-form/progress-easily/)
[Form templates](https://designsystem.digital.gov/templates/form-templates/)
[Form component](https://designsystem.digital.gov/components/form/)
I was not on the contract when all the initial discussions happened about this. I researched meeting notes but still need help with these things:

1. For the Progress Easily content, am I adding the What to do and What not to do FIRST in the lists, or at the end of each?
2. For Form templates, am I adding it first or last in the Accessibility guidance list?
3. For Form component, the doc says "New section" Disabled states for components in forms" - Am I adding that section AFTER Accessibility guidance, or somewehere else on the page? 
 
 I plan to create two other PRs for the other pages.
Once I have guidance, I can complete the edits on the PRs and ask for review.

**Comment by amycole501** [comment]
Any accessibility-related error messaging information should be added with the existing accessibility guidance. 

Also: FWIW on the [form template page](https://designsystem.digital.gov/templates/form-templates/), the guidance around required fields is _also_ considered accessibility guidance. I'm not sure why it's in a separate section without a reference to accessibility.

In general: I suggest adding any relevant WCAG guidance links as references on these pages. The more we can tie in our recommendations to WCAG the better. For example: https://www.w3.org/WAI/WCAG22/Understanding/labels-or-instructions << that's related to required fields.

**Comment by jaclinec** [comment]
@finekatie:

1.Progress Easily content - Add at the end of the list
2.Form templates - Add at the end of the list
3. Form component - Yes, let's add that section after Accessibility guidance

And I agree with Amy that we might want to rethink/discuss how we want organize content on both the form template and form component pages since disabled states and required fields guidance kinda fall under accessibility.

**Comment by finekatie** [comment]
> @finekatie:
> 
> 1.Progress Easily content - Add at the end of the list 2.Form templates - Add at the end of the list 3. Form component - Yes, let's add that section after Accessibility guidance
> 
> And I agree with Amy that we might want to rethink/discuss how we want organize content on both the form template and form component pages since disabled states and required fields guidance kinda fall under accessibility.

Question for @amycole501  and @jaclinec just to clarify: Does this mean I'm still going forward with these changes for now and then we're discussing a content reorg for the pages?  Thank you for your patience!

**Comment by amycole501** [comment]
Yes for now I think you can move forward; we can log this as something to come back to later. Thanks!

**Comment by finekatie** [comment]
PR #2744 is ready for review

**Comment by finekatie** [comment]
PR #2775 is ready for review

**Comment by finekatie** [comment]
PR: #2776  (form component)is ready for review.

**Comment by finekatie** [comment]
PRs approved internally but need changelog update resolution (two are using the same changelog and have different content: [Form component](https://designsystem.digital.gov/components/form/) and [Form templates](https://designsystem.digital.gov/templates/form-templates/). This may be on hold until next week pending review with Dev team.

**Comment by finekatie** [comment]
Amy L added the changelog to the Progress Easily page and everyone has approved in general review. [This is now](https://github.com/uswds/uswds-site/pull/2744) with Dan for FFR. 

Amy and Charlie and I discovered that content is publishing to both Form component and template page. Charlie combined the recommended content into the originally proposed Disabled states section and we are elminating ticket for changes to Form template page. [This is in review. ](https://github.com/uswds/uswds-site/pull/2776)

**Comment by finekatie** [comment]
Both #2776 and #2744 are ready for FFR with @thisisdano

**Comment by finekatie** [comment]
#2776 merged and published today.

**Comment by finekatie** [comment]
[form component](https://designsystem.digital.gov/components/form/) guidance - PR: https://github.com/uswds/uswds-site/pull/2776 - merged 10/4/24
Update complete a complex form [progress easily pattern] (https://designsystem.digital.gov/patterns/complete-a-complex-form/progress-easily/) - PR: https://github.com/uswds/uswds-site/pull/2744 - merged 10/15/24.

This task is now complete. On to Phase 2.
