### ISSUE TITLE
Phase 2 rollout of disabled states guidance

### ISSUE THREAD

**Issue by jaclinec** [uswds/uswds-site#2247]
Phase 2 content to update:

- [Create an account template](https://designsystem.digital.gov/templates/authentication-pages/create-account/)
- [Sign in template](https://designsystem.digital.gov/templates/authentication-pages/sign-in/)
- Components:
- [Button](https://designsystem.digital.gov/components/button/)
- [Date picker](https://designsystem.digital.gov/components/date-picker/)
- [Date range picker](https://designsystem.digital.gov/components/date-range-picker/)
- [Text input](https://designsystem.digital.gov/components/text-input/)

**Comment by jaclinec** [comment]
I created a [draft of the guidance](https://docs.google.com/document/d/11t_miLZP7BZG352itnSOuX3pWQyuFoeD2Le2rkmRDbs/edit?usp=sharing) for this phase of the rollout. Ready for CS to take over review and implementation.

**Comment by brunerae** [comment]
Closing in favor of https://github.com/uswds/uswds/issues/5709
