### ISSUE TITLE
Inventory areas of the site where guidance is referenced

### ISSUE THREAD

**Issue by bonnieAcameron** [uswds/uswds-site#2259]

**Comment by bonnieAcameron** [comment]
Presenting at CS sync 9/6

**Comment by bonnieAcameron** [comment]
[Completed in USWDS Drive.](https://docs.google.com/spreadsheets/d/1NCr004u-cyyKDKrnSyFWjcR1jdXI4KGK/edit#gid=186698082)

**Comment by thisisdano** [comment]
Stale issue. Closing
