### ISSUE TITLE
Draft UX research recruitment page for disabled participants

### ISSUE THREAD

**Issue by amycole501** [uswds/uswds-site#2274]
Work with Jacline to create a draft webpage explaining the UX research process and how participants can get involved. We will also give an overview of the process to add legitimacy and transparency for potential participants. Our contact information or possibly a form (if PRA approved) to connect with us could be included.

The definition of done for this ticket will be a draft of the page shared with the GSA and 10x team(s) for review.

**Comment by annepetersen** [comment]
Does it make sense to use Zendesk / uswds@gsa.gov for this? Trying to eliminate single points of failure / increase visibility

**Comment by amycole501** [comment]
I didn't realize that email existed, that's perfect!

**Comment by amycole501** [comment]
First round draft is here https://docs.google.com/document/d/1n5soFmfRVlXUmPt2mMfz1MUy3NsDEIPSc-DdfxivVY4/edit?usp=sharing and ready for @jaclinec  edits and review.

**Comment by amycole501** [comment]
Nope good call! @katieekline or @sarah-sch could one of you take a look at the draft for the recruitment page?

**Comment by sarah-sch** [comment]
@amycole501, will take a look

**Comment by jaclinec** [comment]
Sarah reviewed the recruitment page copy and nearly all of her suggestions have been accepted. Ready for fed final review @annepetersen or @thisisdano

**Comment by annepetersen** [comment]
[My changes are in the doc now](https://docs.google.com/document/d/1n5soFmfRVlXUmPt2mMfz1MUy3NsDEIPSc-DdfxivVY4/edit#heading=h.906eyj5d1uyn). Let's try to avoid passive voice and be consistent with our use of contractions. Thanks!

**Comment by jaclinec** [comment]
@annepetersen thanks- all edits were accepted. Marking this issue as done.

**Comment by jaclinec** [comment]
Next step: Add this page to the USWDS site as a sub-page to the [Research page](https://designsystem.digital.gov/about/research/). Track that in #2400
