### ISSUE TITLE
USWDS-Site - Date Picker/Date Range Picker Guidance: Allow for manual entry

### ISSUE THREAD

**Issue by mahoneycm** [uswds/uswds-site#2294]
### Is your feature request related to a problem? Please describe.

Related to Usability Testing [results](https://github.com/uswds/uswds/issues/5524).

User preference on entering dates: 2 prefer to type it in, one likes memorable date picker drop-downs

### Describe the solution you'd like

Explicitly call out in our guidance that the component should always allow for the date to also be typed in manually.
Provide language to that effect in Usability Guidance sections in both [Date Picker](https://designsystem.digital.gov/components/date-picker/) and [Date Range Picker](https://designsystem.digital.gov/components/date-range-picker/) components. Both offer calendar picker functionality.

### Additional context

This was originally intended for Date Picker. We discovered Date Range Picker also had similar functionality so we decided to add the same language on that component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds-site/issues) for duplicate feature requests.

**Comment by mejiaj** [comment]
@jaclinec, @mahoneycm this looks ready to start, we just need help with writing up the guidance. If there's additional work required, please outline the tasks in the issue description.

CC @sarah-sch

**Comment by annepetersen** [comment]
In discussion, this seems like a quick win that should only require a content addition to the Usability section indicating that manual date entry should always be possible also. Content (with the assistance of UX), all yours! There are only two sentences in that section presently, so should be simple to integrate.

**Comment by finekatie** [comment]
Hi! Wondering if we should consider adding the same language to [Date Range Picker](https://designsystem.digital.gov/components/date-range-picker/) as well?

> In discussion, this seems like a quick win that should only require a content addition to the [Usability section](https://designsystem.digital.gov/components/date-picker/#usability-guidance) indicating that manual date entry should always be possible also. Content (with the assistance of UX), all yours! There are only two sentences in that section presently, so should be simple to integrate.

**Comment by finekatie** [comment]
Hi @mahoneycm and @annepetersen , I created a [draft here](https://docs.google.com/document/d/1Tw144ltLP4DaFfNfp5nzu6edCLc2bQ9qvM8FnpjERQo). I'm not sure what other guidance we provide beyond advising manual date entry should be allowed. See what I wrote and have at it!

**Comment by mahoneycm** [comment]
@finekatie I added a potential suggestion to the draft. Let me know what you think!

**Comment by jaclinec** [comment]
@finekatie I commented on some of the content - just recommend tweaking a couple of words. Otherwise it LGTM! Also I agree we should add this guidance to date range picker.

**Comment by finekatie** [comment]
> @finekatie I commented on some of the content - just recommend tweaking a couple of words. Otherwise it LGTM! Also I agree we should add this guidance to date range picker.

I like your tweaks and added them. If you approve of this version, mark yourself done in table at top of doc and I suppose a PR can be created to get it added. As for [Date Range Picker](https://designsystem.digital.gov/components/date-range-picker/) - @mahoneycm do we need to do something specific to get this guidance added to that page? Like a new issue and PR, or make THIS Issue include it now?

**Comment by jaclinec** [comment]
My name isn't listed in the table and for some reason I can't figure out how to add it, but I approve! Thanks!

**Comment by finekatie** [comment]
> My name isn't listed in the table and for some reason I can't figure out how to add it, but I approve! Thanks!

Oh no! I added you! I'll add the date you approved. Just need to check with @mahoneycm next about a PR for this and Date Range Picker.

**Comment by mahoneycm** [comment]
> > @finekatie I commented on some of the content - just recommend tweaking a couple of words. Otherwise it LGTM! Also I agree we should add this guidance to date range picker.
> 
> I like your tweaks and added them. If you approve of this version, mark yourself done in table at top of doc and I suppose a PR can be created to get it added. As for [Date Range Picker](https://designsystem.digital.gov/components/date-range-picker/) - @mahoneycm do we need to do something specific to get this guidance added to that page? Like a new issue and PR, or make THIS Issue include it now?

My vote is to include it in this Issue/PR since we'd be adding the same piece of guidance to both pages!

**Comment by finekatie** [comment]
> > > @finekatie I commented on some of the content - just recommend tweaking a couple of words. Otherwise it LGTM! Also I agree we should add this guidance to date range picker.
> > 
> > 
> > I like your tweaks and added them. If you approve of this version, mark yourself done in table at top of doc and I suppose a PR can be created to get it added. As for [Date Range Picker](https://designsystem.digital.gov/components/date-range-picker/) - @mahoneycm do we need to do something specific to get this guidance added to that page? Like a new issue and PR, or make THIS Issue include it now?
> 
> My vote is to include it in this Issue/PR since we'd be adding the same piece of guidance to both pages!

Ok! I'll edit the Issue here to include it. What's next?

**Comment by mahoneycm** [comment]
Assigned to myself, @RachelCorsino, and @cathybaptista for whoever gets free first to add these updates to site this sprint!
