### ISSUE TITLE
Lightweight study for "known issues" prototype

### ISSUE THREAD

**Issue by jaclinec** [uswds/uswds-site#2316]
### Background
After recent usability testing revealed a number of usability and accessibility issues with some components, the USWDS team wanted to find ways to communicate those issues with our community on our site. We created a “known issues” prototype for the combo box component. We want to get some quick, early feedback from users to discover their perceptions of our solution.

### Research goal and questions:
Overall, we are looking for users’ first impressions of the prototype and any feedback they have to share. 

We are hoping their feedback can answer some of our questions:

- What does the ideal solution to the problem look like to them? 
- What type of solution do they expect?
- What do they think of how known issues are displayed on the page? 
- What’s helpful? 
- What’s missing? 
- Is anything confusing? What questions do they have?
- What do they like or dislike and why?
- How well does the current way we’ve set it up meet their needs?

### Method
This is a lightweight study we intend to turn around very quickly. It will be asynchronous in that we’ll share a link to the prototype with a sample of our community of testers through email and ask the to write back with their feedback. 

We’ll aim to include participants with various USWDS proficiency levels.

**Comment by jaclinec** [comment]
I've created the [research plan and email communications ](https://docs.google.com/document/d/1y_PRGsHAf97XVc-WD38PTlSYCTGD5VzXyheOv-8eS78/edit?usp=sharing)for this study. Ready for review. We will likely discuss at the next CS/UX/a11y sync.


### Email message to testers:

Hello USWDS tester community!

The U.S. Web Design System is doing a very light-weight study of an early prototype and we’d love your feedback. We want to better communicate research we’ve done and what usability issues we’ve discovered for specific components. In this prototype, we are testing how we communicate usability issues found for combo box.

If you’re interested in participating, please take a few minutes to go through the prototype and jot down any thoughts you have about it, paying special attention to the alert at the top of the page, and then the “Known issues” section of the prototype.

*Note: We ask that only federal employees participate due to PRA restrictions.*

Some possible reflection questions to give you an idea of what feedback we’re looking for:

- In general, what are your first impressions? What did you like? What’d you not like? Why?
- What surprised you or didn’t match your expectations (if anything)?
- Was anything confusing?
- What’s missing (if anything)?
- How would you improve this solution?
- What questions do you have about this solution?

…and we welcome anything else you want to share! Please share your feedback by ___. Thank you so much!!

Sincerely,

[signature]

**Comment by thisisdano** [comment]
Done
