### ISSUE TITLE
USWDS-Site - Bug: Flag Layout Cards overlapping

### ISSUE THREAD

**Issue by hobbez** [uswds/uswds-site#2323]
### Describe the bug

Browsing the Flag Layout Card demo on the USWDS website's Card Component [page](https://designsystem.digital.gov/components/card/) results in an overlap of cards and elements within the cards when the browser window has a width of 1024px to about 1380px. Checked with Firefox, Chrome and Safari on MacOS.

### Steps to reproduce the bug

1. Go to https://designsystem.digital.gov/components/card/
2. Resize browser window width to 1024px~1380px
3. Overlap in Flag Layout Card should be evident

### Expected Behavior

No overlap of cards or elements in cards. If there is to be an overlap, each card should be in its own "row".

### Screenshots

![image](https://github.com/uswds/uswds/assets/19226765/e576ed4b-2cc4-478c-aebc-89229023b275)

### Additional context

Slack thread: https://gsa-tts.slack.com/archives/C3F14AHSQ/p1696350438474629

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by amyleadem** [comment]
Transferring this issue to the `uswds-site` repo because the grid classes can be managed in the component preview template.
