### ISSUE TITLE
Update mission, vision, and polestar on USWDS website

### ISSUE THREAD

**Issue by sarah-sch** [uswds/uswds-site#2336]
### Purpose
To update the mission, vision, and polestar on the USWDS website.

### Definition of done

[About page](https://designsystem.digital.gov/about/) has been updated to reflect USWDS's new mission, vision, and polestar.

> **Mission**
> Shaping the future of government digital services.
> 
> **Vision**
> Empowered and supported digital service teams. Familiar and easy-to-use digital services.
> 
> **Polestar**
> We help government teams align, design, and keep their websites and services up to date.

### Will be closed by
 PR [2397](https://github.com/uswds/uswds-site/pull/2397)

**Comment by finekatie** [comment]
Worked on this with Sarah today. [Branch is here]( https://github.com/uswds/uswds-site/blob/kf-mission-vision-updates/pages/about/overview.md). Holding off publish until we can discuss with team at CS/UX sync.

**Comment by finekatie** [comment]
Discussed with Sarah today. We DID talk about it in CS/UX sync and decision was made to update with what we have now, and revise at a future date. Pull request will be made to update.

**Comment by finekatie** [comment]
[PR created](https://github.com/uswds/uswds-site/pull/2397) for this. (sarah and I created).
Waiting for Amy and Charlie review before sending to feds for final ok.

**Comment by finekatie** [comment]
Amy and Charlie approved yesterday. Assigned to Anne and Dan to review and approve.

**Comment by annepetersen** [comment]
Wow, this got deprioritized! Let's get back to it. I made some [direct revisions here](https://github.com/uswds/uswds-site/blob/kf-mission-vision-updates/pages/about/overview.md).

**Comment by sarah-sch** [comment]
Thanks, @annepetersen! Pulling into the current sprint.
