### ISSUE TITLE
UX issue related to headings in Accordions

### ISSUE THREAD

**Issue by sarah-sch** [uswds/uswds-site#2342]
### Purpose
This work stems form the content audit (#2341). When headings are embedded within an accordion (such as on the [Alert component page](https://designsystem.digital.gov/components/alert/#standard-alerts)), a potential UX issue occurs:

When the accordion is closed, headings available on the in-page nav are no longer available on the visible page. Further, the headings nested in the accordion may be hidden from screen readers. 

### Goals
Assess how screen readers interact with accordions when they are closed. Discuss usability implications. Align on and execute solutions.

Tasks### 

- [ ] uswds/uswds-site#2344
- [ ] Create comprehensive (as possible) list of usability concerns raised by this issue.
- [ ] Align on and implement solutions.

**Comment by brunerae** [comment]
This Issue was closed in favor of https://github.com/uswds/uswds-site/issues/2344
