### ISSUE TITLE
Determine how screen readers interact with accordions when they are open vs. closed.

### ISSUE THREAD

**Issue by sarah-sch** [uswds/uswds-site#2344]
### Purpose
This work is part of the larger issue of investigating how heading nested inside accordions affect usability (#2342). The goal here is to screen-reader test a page ([such as the Alert page](https://designsystem.digital.gov/components/alert/)) that includes headings nested in accordions.

### Goal
Manually test this page with various screen readers, both when the accordion is opened and when it is closed. Make a note of any accessibility problems you encounter.

**Comment by amycole501** [comment]
In JAWS (Chrome, Firefox, Edge on a PC desktop)  I don't hear "collapsed" or "expanded" if I try to open and close the accordions on the component pages. I hear "to activate press enter". The role and purpose isn't announced. Will need to create an issue for this if @alex-hull finds the same results.

In NVDA I hear "collapsed" and "expanded". Works as it should in all browsers (PC, desktop).

**Comment by alex-hull** [comment]
Tested in Chrome on PC: 

- Both JAWS and NVDA say "collapsed" and "expanded". However, in JAWS, it does tell you to activate the button for the accordion to open OR close. This does not happen every time. After about two times, you no longer hear collapse and expand, just "to activate, press enter". It could be misleading, as typically activating a button will collapse it, directing the user to the information within the accordion.

- In relation to issue [https://github.com/uswds/uswds-site/issues/2342](url), when the accordions are expanded, headings and content will not be read aloud. When expanded, they also do not appear in the list of elements on page when pulled up in the JAWS elements list.

- On the alert page, top content is not read first. Error status within the component preview is read first. Discussed with Amy C and will put in a bug ticket.

**Comment by brunerae** [comment]
Closing this in favor of #2368
