### ISSUE TITLE
USWDS-Site - Feature: Add GA4 analytics snippet

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds-site#2390]
### Is your feature request related to a problem? Please describe.

We'll need to add a new code snippet to our websites so we can transition to GA4 data collection under the GSA Enterprise Analytics account while continuing to collect UA data on our existing account.

### Describe the solution you'd like

The existing DAP code in `_includes/analytics.html` should continue to appear within the document `head`, but this new GA4 snippet AND our existing UA snippet should now appear directly _after_ the `head`.

[DAP implementation guide](https://github.com/digital-analytics-program/gov-wide-code/blob/master/documentation/GSA%20DAP%204.1%20-%20Quick%20Guide.pdf) (PDF) → 
[GA4 Implementation guide](https://support.google.com/analytics/answer/9304153?sjid=7848239909584944126-NC#zippy=%2Cadd-the-google-tag-directly-to-your-web-pages) (see "Set up data collection for websites") → 

In the `head`:
```html
<--! DAP -->
<script async type="text/javascript" id="_fed_an_ua_tag" src="https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js?agency=GSA&subagency=TTS"></script>
```

Directly after `head`:
```html
<--! GA4 -->
<!-- Google tag (gtag.js) --> <script async src="https://www.googletagmanager.com/gtag/js?id=G-HBYXWFP794"></script> <script> window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'G-HBYXWFP794'); </script>

<--! UA -->
<script>
	window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
	ga('create', '{{ site.google_analytics_ua }}', 'gsa.gov');
	ga('send', 'pageview');
	// anonymize user IPs (chops off the last IP triplet)
	ga('set', 'anonymizeIp', true);

	// forces SSL even if the page were somehow loaded over http://
	ga('set', 'forceSSL', true);

	ga('send', 'pageview');
</script>
<script async src='https://www.google-analytics.com/analytics.js'></script>
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds-site/issues) for duplicate feature requests.

**Comment by mahoneycm** [comment]
After reviewing the documentation, some Q&A online, and testing, I believe the instructions mean after the _opening_ `head` tag rather than after the `head` completely / closing tag. More information available in #2428
