### ISSUE TITLE
USWDS-Site - UX: Publish new research recruitment page (for public)

### ISSUE THREAD

**Issue by jaclinec** [uswds/uswds-site#2400]
Builds on #2274 

We need to create a new research recruitment sub-page that would be under the main Research page. The copy is finalized and ready to be added to the site.

[Recruitment page contents / copy ](https://docs.google.com/document/d/1n5soFmfRVlXUmPt2mMfz1MUy3NsDEIPSc-DdfxivVY4/edit?usp=sharing)(recruiting for the public)

On the main [Research page](https://designsystem.digital.gov/about/research/), add a "How to participate in research" section that links to this recruitment page. See copy in the [research page content doc](https://docs.google.com/document/d/1Lx-oUHboZ33aUt4XYyNU--SB_1_6Je-LHyLYHVRRCD0/edit?usp=sharing)

**Comment by jaclinec** [comment]
@annepetersen, the [public recruitment page copy](https://docs.google.com/document/d/1n5soFmfRVlXUmPt2mMfz1MUy3NsDEIPSc-DdfxivVY4/edit?usp=sharing) is ready for final review. CS (Katie) had a chance to review it and I accepted many of her changes. I think it's in good shape. Thanks!

**Comment by annepetersen** [comment]
Added some changes, but very close to done here

**Comment by jaclinec** [comment]
I accepted all changes. I think this can be marked as done @annepetersen - thank you!
