### ISSUE TITLE
Top Tasks Performance: Perform usability tests

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-site#2420]
We recruited and scheduled 7 participants (mostly those with a design background). See the [Top Tasks Usability testing Plan](https://docs.google.com/document/d/1VrTjgW3adHO94UE2witTJMnpnVcIwE7O-ZzA1y15vxU/edit?usp=sharing) :lock: for details on our approach in this study.

**Comment by jaclinec** [comment]
All 7 sessions have been conducted with participants and we're now analyzing the data. This issue can be closed.

**Comment by annepetersen** [comment]
Thanks Jacline! I'm assuming a read-out will be scheduled as well as adding details to the wiki (and if I missed the open issue on those, apologies: trying to wrap up before the weekend)

**Comment by jaclinec** [comment]
@annepetersen Yes definitely planning a readout later when the findings are finalized
