### ISSUE TITLE
USWDS-Site - Bug: Remove mention of Alert dismissability

### ISSUE THREAD

**Issue by werdnanoslen** [uswds/uswds-site#2425]
### Describe the bug

The Alert page's usability guidance mentions Alerts should be dismissable.

### Steps to reproduce the bug

https://github.com/uswds/uswds-site/blob/7943e666c36de06b0cf7190cb860d89b25eda4d2/_components/alert/guidance/usability.md?plain=1#L5

### Expected Behavior

Should this be removed until there is guidance on _how_ to do this, given it is [not on the roadmap](https://github.com/uswds/uswds/issues/988#issuecomment-405390279)?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds-site/issues) for duplicate bug reports.

**Comment by brunerae** [comment]
Hi @werdnanoslen! Thanks for submitting this. We're going to explore making the Alert able to be dismissed (https://github.com/uswds/uswds/issues/5754) and, for now, we'll update our Guidance to add a note that we understand our guidance and current functionality don't align. We'll reference this Issue in that PR once its created.

**Comment by sarah-sch** [comment]
@finekatie - sharing [a rough draft of this updated guidance](https://docs.google.com/document/d/1FsjtzT5t2u-t-QmoMXhdVGAx2pcPxhxGL1hNg7ReXco/edit?usp=sharing) for the [Alert page](https://designsystem.digital.gov/components/alert/)

**Comment by sarah-sch** [comment]
Has been reviewed by @finekatie. Will send for fed final review on 3/13.

**Comment by thisisdano** [comment]
Approved copy, with an edit. Let's get it into production.

**Comment by sarah-sch** [comment]
@thisisdano and @finekatie, I left a final question for you in the document. Thanks for taking another look!

**Comment by finekatie** [comment]
I commented on 3/18. Still waiting for Dan's input.

**Comment by sarah-sch** [comment]
@brunerae asking @thisisdano for input 3/22/24 in FFR roundup. If dan can't look today, we will finalize copy with @annepetersen next week.

**Comment by sarah-sch** [comment]
Assigned @finekatie, @amyleadem, and @mahoneycm as reviewers on PR #2563.
