### ISSUE TITLE
USWDS-Site - Feature: Bootstrap compatible theme

### ISSUE THREAD

**Issue by nonprofittechy** [uswds/uswds-site#2429]
### Is your feature request related to a problem? Please describe.

I would like to provide theming that is consistent with the USWDS when working on guided interviews for court forms or government forms for executive branch agencies.

### Describe the solution you'd like

I would like to make a theme for https://github.com/jhpyle/docassemble that follows the USWDS design language and implements its choices. It looks like there was a defunct Code for America project that worked on this. https://github.com/codeforamerica/uswds-bootstrap

Docassemble uses out of the box Bootstrap 5 themes. With the SCSS implementing Bootstrap variable names, most of the USWDS system could be implemented quickly.

### Describe alternatives you've considered

The alternative I have considered is creating the theme from scratch. An official project would have additional value for other folks with a similar need.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds-site/issues) for duplicate feature requests.

**Comment by brunerae** [comment]
Hi @nonprofittechy - thanks for submitting this and apologies for our delayed response! We don't currently have a Bootstrap theme on our roadmap, but if you've embarked on this yourself we'd love to hear about it! For now, I'm going to close this Issue.
