### ISSUE TITLE
CC a11y: publish select checklist - draft content

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-site#2436]
Follow-up from https://github.com/uswds/uswds/issues/5595

### A11Y
- [x] Review checklist content
- [x] Final approval of checklist content

### Content
- [x] Draft checklist content and send for review with A11Y
- [x] Final edits to checklist content

### Dev
- [x] #2666

## References
[Critical Checklist spreadsheet](https://docs.google.com/spreadsheets/d/1fAJaObQHv7aIaeUpH4fTLmauhmugMtNCrbpZe4BJcPY/edit?usp=sharing)
[List of all components](https://docs.google.com/spreadsheets/d/1ASzZ80oI6WVWAifqPO6gYAqrsRaiZs_qGTOStuQPyKs/edit?usp=sharing)

**Comment by finekatie** [comment]
started work on this yesterday. should finish today.

**Comment by finekatie** [comment]
Select is finished and ready for your review, @amycole501  and @alex-hull !

**Comment by finekatie** [comment]
I completed Select component gherkin copy on 5/31. Tagged @amycole501  and @alex-hull (accidentally deleted when thinking I updated the wrong Issue).

**Comment by finekatie** [comment]
Hey @amycole501 or @alex-hull , is this already reviewed and dev building out content on page? I'm not sure of status.

**Comment by amycole501** [comment]
@amyleadem has been reviewing the select checks so I think content is done.

**Comment by amyleadem** [comment]
Yes, we are adding this content to the page in #2702. It should be safe to close out this issue.
