### ISSUE TITLE
CC a11y: publish icon checklist - draft content

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-site#2456]
Follow-up from https://github.com/uswds/uswds/issues/5730

### A11Y
- [x] Review checklist content
- [x] Final approval of checklist content

### Content
- [x] Draft checklist content and send for review with A11Y
- [x] Final edits to checklist content

### Dev
- [x] #2535

## References
[Critical Checklist spreadsheet](https://docs.google.com/spreadsheets/d/1fAJaObQHv7aIaeUpH4fTLmauhmugMtNCrbpZe4BJcPY/edit?usp=sharing)
[List of all components](https://docs.google.com/spreadsheets/d/1ASzZ80oI6WVWAifqPO6gYAqrsRaiZs_qGTOStuQPyKs/edit?usp=sharing)

**Comment by finekatie** [comment]
Started adding gherkin copy to spreadsheet.

**Comment by sarah-sch** [comment]
Gherkin copy ready for review by @alex-hull and @amycole501 as of 2/23.

**Comment by alex-hull** [comment]
2/27: Reviewed and ready for any final CS edits.

**Comment by alex-hull** [comment]
@amyleadem : Checklist items are ready for your review. The gherkins can be found in column k for easy scanning.
