### ISSUE TITLE
Draft and finalize content for feds-only recruitment page

### ISSUE THREAD

**Issue by jaclinec** [uswds/uswds-site#2463]
The draft  of the [feds-only recruitment page](https://docs.google.com/document/d/1UoaxVKe9iKwUvH7U26Xgx6l5PZR2ZHRsFHf0t-i0hvk/edit?usp=sharing) content is nearly ready to be finalized and published on the site and linked from the refreshed research page.

**Comment by jaclinec** [comment]
@sarah-sch or @finekatie this content is ready for your review. Thank you!

**Comment by annepetersen** [comment]
Reviewed this and put some suggestions in.

**Comment by jaclinec** [comment]
@annepetersen and @thisisdano this is ready for final review.

**Comment by annepetersen** [comment]
Approved on my end. @thisisdano, would you like to also review, or is my approval enough to publish?

**Comment by thisisdano** [comment]
Looks good to me!
