### ISSUE TITLE
USWDS-Site - Bug: [Fix heading on Community page]

### ISSUE THREAD

**Issue by sarah-sch** [uswds/uswds-site#2467]
### Describe the bug

Dan's name is a heading under "Community Managers" on this page. It shows up as part of the in-page navigation. Let's reformat so that his name is no longer in the heading structure.

### Steps to reproduce the bug

1. Go to https://designsystem.digital.gov/about/community/
2. Look at the in-page navigation

### Closed by

#2492 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds-site/issues) for duplicate bug reports.

**Comment by finekatie** [comment]
Hey @sarah-sch , I'm looking at the page and there's a link on Dan's name to [this page](https://digital.gov/authors/dan-williams/). Do we want to leave that link?

**Comment by finekatie** [comment]
Sarah and I talked about this today. 
We should remove header tags at the very least. That should stop it from showing up in the On this page menu.

Things we need to discuss:
 - Is Dan the community manager? Should we have that there?
  - Is there a threshold for On this page functionality showing up on a short page?

**Comment by finekatie** [comment]
This will be closed by: https://github.com/uswds/uswds-site/pull/2480

**Comment by finekatie** [comment]
Sarah approved. Still needs to be merged.

**Comment by sarah-sch** [comment]
Reviewed PR and attempted to merge changes this morning. Merged changes not appearing on site yet; will check later this morning and close or follow up with dev team if needed.
