### ISSUE TITLE
USWDS-Site - Bug: [Eliminate extra period on Identifier page]

### ISSUE THREAD

**Issue by sarah-sch** [uswds/uswds-site#2468]
### Describe the bug

Eliminate extra period on Identifier page (under Accessibility guidance section).

### Steps to reproduce the bug

1. Go to https://designsystem.digital.gov/components/identifier/
2. Search the page for ".."

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds-site/issues) for duplicate bug reports.

**Comment by finekatie** [comment]
Made change in a kf branch and created PR: https://github.com/uswds/uswds-site/pull/2471
