### ISSUE TITLE
Add descriptive alt text to showcase images on USWDS homepage

### ISSUE THREAD

**Issue by sarah-sch** [uswds/uswds-site#2469]
### Statement of problem
The [USWDS homepage](https://designsystem.digital.gov/) includes images of Showcase USWDS websites that all have very similar alt text, reading "Preview of [website name] homepage." 

### Work to be done
- [x] Draft new alt text
- [x] Review with content and a11y team
- [ ] Get approval from federal team
- [ ] Publish

**Comment by finekatie** [comment]
Discussed with content and a11y team. 

ANDI is flagging that the alt text in each of these images is redundant. Using "image remover" browser extention to Chrome one can see the page without the images and tell that those screen shots aren't critical for figuring out the purpose of those links

- We propose removing alt text, as the images are decorative. The links to the sites are what's important.

- We also propose changing the title on that section from "Showcase" to "Sites built with USWDS". It's clearer than Showcase.

**Comment by finekatie** [comment]
This will be closed by[ PR 2478](https://github.com/uswds/uswds-site/pull/2478)

**Comment by finekatie** [comment]
Asked for fed final review on 2/22.
