### ISSUE TITLE
USWDS-Site - Footer: Update guidance to import `layout-grid`

### ISSUE THREAD

**Issue by mahoneycm** [uswds/uswds-site#2475]
# Summary

Add guidance surrounding the footer's use of `layout-grid` and how to import the package if users want to customize their footer layout.

## Problem statement

If users are only importing `usa-footer` without `usa-layout-grid`, they will be unable to customize the grid classes that are included in the components markup without breaking the layout.

Note from changelog:
> If you notice changes in your layout after making this update, your Sass might be missing the usa-layout-grid package. You can include it by adding @forward usa-layout-grid to your [Sass entry point](https://designsystem.digital.gov/documentation/migration/#using-component-packages).

## Additional information

Layout grid dependency removed in uswds/uswds#5289

**Comment by mejiaj** [comment]
@mahoneycm is this still required?

**Comment by mahoneycm** [comment]
@mejiaj  I think it would help users now that the footer no longer has `layout-grid` as a dependency. They might see the grid classes in the markup and assume they can customize it. 

If we want to include it, I can try to come up with some mock guidance and pass it to content for revision 👍

**Comment by brunerae** [comment]
@mahoneycm to check and see if this is still relevant

**Comment by mahoneycm** [comment]
Deeming this no longer necessary as we've restored the layout-grid dependency in uswds/uswds#5930
