### ISSUE TITLE
CC a11y: publish Table checklist - draft content

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-site#2486]
Follow-up from https://github.com/uswds/uswds/issues/5450

### A11Y
- [x] Review checklist content
- [x] Final approval of checklist content

### Content
- [x] Draft checklist content and send for review with A11Y
- [x] Final edits to checklist content

### Dev
- [x] #2534

## References
[Critical Checklist spreadsheet](https://docs.google.com/spreadsheets/d/1fAJaObQHv7aIaeUpH4fTLmauhmugMtNCrbpZe4BJcPY/edit?usp=sharing)
[List of all components](https://docs.google.com/spreadsheets/d/1ASzZ80oI6WVWAifqPO6gYAqrsRaiZs_qGTOStuQPyKs/edit?usp=sharing)

**Comment by finekatie** [comment]
Sarah made recommendations on these.

**Comment by sarah-sch** [comment]
Meeting 2/23 to discus queries with @alex-hull. Then, copy will be ready for review by @alex-hull and @amycole501.

**Comment by sarah-sch** [comment]
Gherkin copy ready for review by @alex-hull and @amycole501.

**Comment by amycole501** [comment]
Copy looks good to me.

**Comment by alex-hull** [comment]
2/27: Reviewed and ready for any final CS edits.

**Comment by alex-hull** [comment]
@amyleadem : Checklist items are ready for your review. The gherkins can be found in column k for easy scanning.

**Comment by sarah-sch** [comment]
@mahoneycm and @amyleadem - please add @finekatie and me as reviewers on the PR for the new page
