### ISSUE TITLE
Draft updated icons guidance based on literature review findings

### ISSUE THREAD

**Issue by jaclinec** [uswds/uswds-site#2490]
This work is an extension of what came out of the recently completed [icons literature review](https://github.com/uswds/uswds-team/issues/335). We're updating our icons guidance to clarify and emphasize:

- when icons should and shouldn't be preceivable to screen readers
- emphasize that icons should serve as recognizable symbols/pictograms that serve a functional purpose, distinguished from illustrations.
- explain that universally recognized icons are rare and emphasize the importance of testing icon recognition and memorability with your users if you suspect an icon is ambiguous.

**Comment by jaclinec** [comment]
The draft of the [updated icons guidance suggestions](https://docs.google.com/document/d/1LyXxWulNU2ERobWP-VSTnG25Na6aA8DjvBH3XRGdJ4w/edit?usp=sharing) is a work in progress.

**Comment by jaclinec** [comment]
Now that I've had a chance to present the lit review findings to the team, the icons guidance draft linked above is ready for review @sarah-sch and @finekatie . Thank you!

**Comment by sarah-sch** [comment]
@jaclinec - content team has finished review. LMK if you have any questions.

**Comment by jaclinec** [comment]
@annepetersen this is ready for your review - thanks!

**Comment by annepetersen** [comment]
Reviewed, and [my changes are in](https://docs.google.com/document/d/1LyXxWulNU2ERobWP-VSTnG25Na6aA8DjvBH3XRGdJ4w/edit#heading=h.2h7x1byzq7p2). Will wait for discussion or acceptance of changes before closing.

**Comment by annepetersen** [comment]
All set!

**Comment by annepetersen** [comment]
missed a few things
