### ISSUE TITLE
Update Link page to remove references to OMB M-17-06

### ISSUE THREAD

**Issue by sarah-sch** [uswds/uswds-site#2511]
### Purpose of this issue
This issue closes #2474 reporting the outdated reference to OMB M-17-06 on the [USWDS Link component page](https://designsystem.digital.gov/components/link/). Here, we are outlining work related to updating the Link page to remove these outdated policy references.

### Summary of team's discussion of this issue
@finekatie updated the team on the state of the Link page on 2/28/2024. She shared this [Mural board analyzing opportunities for updates on the Link page](https://app.mural.co/t/gsa6/m/gsa6/1709139000067/13d3ab9683ddb24d52ad44d6fa1830ab947783db?sender=u0621280f41cdbc6a64e46748).

The team discussed the following points on 2/28/2024, which should guide page updates:

- Remove references to M-17-06 because M-23-22 rescinds the previous memo. OK to mention that M-23-22 rescinds M-17-06 in copy.
- Some of the guidance based on M-17-06 is still solid and not addressed by M-23-22, so it is ok to keep those best practices in our content.
- Restructure/reorganize "musts" as "shoulds": Guidance should generally remain the same, but where we are currently talking about what you "must" do and it is not referenced in M-23-22, it should become what you "should do."
- We do NOT need to replace the M-17-06 accordion with a M-23-22 accordion
- Under "Additional Information" heading remove old policy and add new one

### Work to be done

- [x] Draft copy updates for Links page
- [x] Fed approval of copy updates
- [x] Create a pull request for copy updates
- [ ] Fed final review

**Comment by finekatie** [comment]
Draft is ready for review: https://docs.google.com/document/d/19dL65nsLGLLRd_FRv8izk823do32UNzzPxF-n6MHiak/edit

**Comment by finekatie** [comment]
Sarah reviewed today. I need to get my reviews in before submitting changes.

**Comment by sarah-sch** [comment]
3/13 - sent for feedback from @annepetersen and @thisisdano

**Comment by finekatie** [comment]
We got feedback and then had more discussion about what to keep and how to structure in a meeting with Dan and Anne yesterday. Draft in a final pass with Anne and Sarah. I'll work on it in a branch when draft is done and get FFR from Dan and Anne.

**Comment by finekatie** [comment]
Discussed in CS/UX sync today. Going to create branch from current version of the reworked page. Will submit to Dan and Anne for FFR when ready.

**Comment by finekatie** [comment]
New PR: https://github.com/uswds/uswds-site/pull/2545. Should close this issue.

**Comment by sarah-sch** [comment]
We need to create a new issue after this closes so that we can continue the discussion about updates to the guidance. Working with @brunerae on 3/21/24 to get issue written.

**Comment by finekatie** [comment]
Had issues with branch yesterday but James found and corrected. I updated two icons and re-merged. Waiting to send for FFR.
