### ISSUE TITLE
USWDS-Site - Bug: No example of inline field errors

### ISSUE THREAD

**Issue by sawyerh** [uswds/uswds-site#2522]
### Describe the bug

There used to be a demo of form fields with different states (error, success). There's no longer an example anywhere that I can find, which makes it difficult to quickly identify how to structure the markup to display an inline error message for a form field.

### Expected Behavior

I expected to find an example on either the [Form page](https://designsystem.digital.gov/components/form/), [Text input](https://designsystem.digital.gov/components/text-input/) page, and/or [Validation](https://designsystem.digital.gov/components/validation/) page.

**Comment by mahoneycm** [comment]
Thank you for submitting this issue @sawyerh !

This appears to be a duplicate of #2476. I'll close this issue in favor of that one since there is already some discussion in that thread. We'll continue tracking the work there!
