### ISSUE TITLE
USWDS-Site - Evaluate existing copy on accessibility checklist pages

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds-site#2546]
## Tasks
Evaluate the copy on the following pages:
- [Icon accessibility tests](https://designsystem.digital.gov/components/icon/accessibility-tests/)
- [Table accessibility tests](https://designsystem.digital.gov/components/table/accessibility-tests/)
- [Typography accessibility tests](https://designsystem.digital.gov/components/typography/accessibility-tests/)

In this task we should:
- Edit the checklist copy for plain language and consistency across components.
- Consider if we should add additional sections or "how to" instructions, such as:
    - Creating a "how to" accordion for general tests that includes instructions for how to check color contrast (This would allow us to simplify copy on the actual test items)
    - Creating a section with how to instructions for adjusting text spacing and size with a plugin (This would allow us to include a few more types of tests)

**Comment by finekatie** [comment]
Reviewed existing copy and made notes here:
https://docs.google.com/document/d/1ixCyiEGtikB7q2r_Ha2Xlr1R6nBBqAznRpoMBd7pkZ4/edit#heading=h.l8qur6xdsj9z

**Comment by finekatie** [comment]
Here are my thoughts on the other considerations mentioned in the issue:
1.  I think a how-to for color contrast checking is a great idea if we know users are unfamiliar with how to do that.
2. Instructions for adjusting text spacing and size with a plugin - A particular plug in or any plugin? Does that open up a pandora's box for different operating systems or anything? Even if that's fine, how many tests do they NEED to run and when does it become too many to keep them engaged in doing the work?

**Comment by finekatie** [comment]
Discussed with @sarah-sch today. Review is complete here. We will create a new issue for addressing the recommendations and changes to be made.

@amyleadem, before I close this, do you want to take a look at my thoughts above that addresses questions in the issue?

**Comment by sarah-sch** [comment]
@finekatie and @amyleadem - opening #2590 to update these posts next sprint. @amyleadem, I can add any thoughts you have to that issue once you've shared them here.

**Comment by amyleadem** [comment]
Thanks for opening that issue @sarah-sch and thanks for the edits @finekatie! I think we are good to mark this issue as done. We can address any remaining questions in issue #2590.

**Comment by sarah-sch** [comment]
Closing per @amyleadem's comment above.
