### ISSUE TITLE
Improve content in Link guidance

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-site#2547]
The Link guidance information could use some improvements and we've generated ideas for those [in Mural.](https://app.mural.co/t/gsa6/m/gsa6/1709139000067/13d3ab9683ddb24d52ad44d6fa1830ab947783db?sender=u6f001d0317caa2b318226577)

**Comment by finekatie** [comment]
I believe this should have been addressed by #2511. The Link page is up to date and old OMB guidance is updated or removed. :)

**Comment by thisisdano** [comment]
It's OK to close this one
