### ISSUE TITLE
Content Audit: pull together analysis report

### ISSUE THREAD

**Issue by sarah-sch** [uswds/uswds-site#2550]

**Comment by sarah-sch** [comment]
4/5-4/5 and 4/6 - checking and cleaning up data and fleshing our results/recommendations deck with more detailed information and examples. Meeting with @jaclinec to discuss on 4/9. Slated to discuss and CS/UX/a11y sync on 4/17 to align on ongoing, repeatable processes.

**Comment by sarah-sch** [comment]
Looking forward to [sharing report with the team](https://docs.google.com/presentation/d/1D_qSevvRKA715_83XYiqEq_FhZh32iadGDhp8S8giXI/edit?usp=sharing) at today's CS/UX/a11y team.

**Comment by thisisdano** [comment]
Thank you!
