### ISSUE TITLE
Update accessibility page with new copy

### ISSUE THREAD

**Issue by amycole501** [uswds/uswds-site#2554]
Please update the [accessibility content on the site](https://designsystem.digital.gov/documentation/accessibility/) with the content [located here](https://docs.google.com/document/d/1n4DcDUbL5jVDVT3HY7TE6I4LLrY0CmKUhUDKCo873E8/edit?usp=sharing).

All content on the page will be replaced with the google doc information.

When ready for review, please add Sarah and Katie as reviewers.

**Comment by amyleadem** [comment]
@mahoneycm I grabbed this issue so I removed you as an assignee.
