### ISSUE TITLE
USWDS-Site: Create a component that notifies users of outdated content

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds-site#2565]
## Summary
Create a component that notifies readers of outdated content.

Here is an example of an implementation of something similar from [digital.gov](https://digital.gov/2015/12/31/digitalgovs-2015-year-in-review/):
![image](https://github.com/uswds/uswds-site/assets/93996430/f4232f55-8a29-4f2b-9903-a3112d732f60)

**Comment by brunerae** [comment]
Next steps:

- [ ] Copy from content team
- [ ] Update Component

**Comment by sarah-sch** [comment]
@katharine-carr and @amyleadem - [sharing some copy ideas here](https://docs.google.com/document/d/1Y1HWbjVGI_nK7nFpYYmBaZT9RT6gypmBtXlTY3uAerE/edit?usp=sharing). Would love input.

**Comment by sarah-sch** [comment]
@amyleadem - see [our top choice for copy in this document](https://docs.google.com/document/d/1Y1HWbjVGI_nK7nFpYYmBaZT9RT6gypmBtXlTY3uAerE/edit?usp=sharing):

This page is in the process of being archived. It was published X years ago and may include broken links or outdated information.

cc @finekatie

**Comment by amyleadem** [comment]
@sarah-sch Thanks! I'll work on incorporating that soon so you can get a preview
