### ISSUE TITLE
USWDS-Site - Update link on Keep A Record page

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-site#2574]
### Is your feature request related to a problem? Please describe.

Usability guidance content for the [Keep A Record pattern](https://designsystem.digital.gov/patterns/complete-a-complex-form/keep-a-record/) contains a link to archived content on digital.gov.

> TEST BROADLY
> Test print outputs. Test printing using a variety of printers, print-to-PDF options, and assistive output devices, using [representative browser and operating system combinations](https://digital.gov/2013/07/15/digital-metrics-for-federal-agencies/) prior to launch. Remember that mobile device users will have additional challenges printing or saving to PDF so some on-screen guidance may be necessary.

### Describe the solution you'd like

We should find a newer relevant piece of content to replace this link.

### Additional context

This will be closed by #2939 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds-site/issues) for duplicate feature requests.

**Comment by finekatie** [comment]
Hey @amycole501 , I would love your feedback on what we might recommend as a replacement for the link noted here. I did some preliminary research but I'm not coming up with what I think is appropriate. I'm also thinking the current archived link isn't even to the correct type of content.

**Comment by amycole501** [comment]
I agree on both counts.

Do you think this would work instead?? https://digital.gov/topics/analytics/

the confusing thing is the URL wording doesn't match where it's sending someone to.

**Comment by finekatie** [comment]
> I agree on both counts.
> 
> Do you think this would work instead?? https://digital.gov/topics/analytics/
> 
> the confusing thing is the URL wording doesn't match where it's sending someone to.

I don't think that link works in this context either. The content in the section is about testing print outputs. So the link _text_ makes sense. What it _links_ to doesn't. We need some kind of place to send folks to understand what kind of "representative browser and operating system combinations" are good to test on. Do we have a best practices thing somewhere for that? Does digital.gov? Do we NEED this content? Wondering if we shouldn't craft something ourselves.

@sarah-sch what do you think?

**Comment by sarah-sch** [comment]
Hm, so there's [this note about popular browsers on our documentation page](https://designsystem.digital.gov/documentation/getting-started-for-developers/), which links to [analytics.usa.gov](https://analytics.usa.gov/). Could one of these be helpful? 

We could change the wording to something like:
".... using representative browser and operating system combinations prior to launch. [Analytics.usa.gov](using [representative browser and operating system combinations](https://digital.gov/2013/07/15/digital-metrics-for-federal-agencies/) prior to launch.) provides user device demographics that can help you plan your tests."

Unfortunately I don't think there's a way to link directly to the device demographics section ... We'll have to count on people to scroll.

**Comment by finekatie** [comment]
Revisiting this now. Hey @amycole501 , in reviewing this, it appears to me that what the content in the pattern seeks to link to ("representative browser and operating system combinations") takes people to an old archived link about analytics and performance metrics. I'd imagine we'd want to send someone to a page that talks about current acceptable operating systems and browser combos, right? If you agree, where would we take them?

**Comment by amycole501** [comment]
I think we should reword that link entirely. What it should say is something along the lines of:

Test print outputs. Test printing using a variety of printers, print-to-PDF options, and assistive output devices, using representative browser and operating system combinations[ based on your site's visitor data ](https://digital.gov/guides/dap/make-data-informed-decisions/#content-start)prior to launch. Remember that mobile device users will have additional challenges printing or saving to PDF so some on-screen guidance may be necessary.

**Comment by finekatie** [comment]
> I think we should reword that link entirely. What it should say is something along the lines of:
> 
> Test print outputs. Test printing using a variety of printers, print-to-PDF options, and assistive output devices, using representative browser and operating system combinations[ based on your site's visitor data ](https://digital.gov/guides/dap/make-data-informed-decisions/#content-start)prior to launch. Remember that mobile device users will have additional challenges printing or saving to PDF so some on-screen guidance may be necessary.

I LOVE IT!!! So much clearer.

Do I need to draft the page and share this for review with Dan before we start a PR, or what do you think?

**Comment by amycole501** [comment]
This is the advice I'd give anyone who asks this question so even if it's not hitting the mark of whatever that previous link was trying to do it's still solid guidance. I think it's good to go as-is and if needed, we can augment with further guidance in the future.

**Comment by finekatie** [comment]
Ok. @brunerae , I think Amy has language here that we can update the page with. Instead of drafting a whole doc, I'd like to start a PR to update the content and have Dan/Anne review in context. Do I need a Dev to get involved for a prelim review or can I start it up and move it along?

**Comment by brunerae** [comment]
Sounds like a plan @finekatie  - thank you!

**Comment by finekatie** [comment]
PR created. Want @amycole501 review alongside FFR.
