### ISSUE TITLE
USWDS-Site - HTML Proofer: fix Performance Research broken link

### ISSUE THREAD

**Issue by mahoneycm** [uswds/uswds-site#2589]
### Describe the bug

When testing HTML Proofer ignored codes, I found multiple broken links throughout the site. 

### Steps to reproduce the bug

Visit any of the following links which can be found on the respective USWDS pages:

>[!NOTE]
>Showcase links resolved by #2586 

- ~[Showcase](https://designsystem.digital.gov/documentation/showcase/)~
    - ~[`https://datacenters.cio.gov/`](https://datacenters.cio.gov/)~
    - ~[`https://feedback.usa.gov/`](https://feedback.usa.gov/)~
    - ~[`https://www.move.mil/`](https://www.move.mil/)~
    - ~[`https://itmodernization.cio.gov/`](https://itmodernization.cio.gov/)~
    - ~[`http://vsfs.state.gov/`](http://vsfs.state.gov/)~
- [Performance Research](https://designsystem.digital.gov/performance/research/)
    - [`https://pulse.cio.gov/`](https://pulse.cio.gov/)

### Expected Behavior

Links should be updated or removed.

### Additional context

I found this error after removing `--ignore-status-codes 0`. Unfortunately, some of the results were false positives, so we'll need to continue ignoring error code `0`.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds-site/issues) for duplicate bug reports.

**Comment by finekatie** [comment]
Updating content on Performance-related pages is covered by #2542, so for this issue, I'm simply going to remove the link from the page.

**Comment by finekatie** [comment]
This will be closed by #2609

**Comment by finekatie** [comment]
After copy updates in PR, waiting for review from @sarah-sch and hoping to get ffr and merge after that.

**Comment by finekatie** [comment]
Sarah and Charlie approved. Added Dan and Anne for approval and added message in PR.

**Comment by mejiaj** [comment]
Closing as resolved.
