### ISSUE TITLE
Update copy on Icon, Table, and Typography pages

### ISSUE THREAD

**Issue by sarah-sch** [uswds/uswds-site#2590]
During the previous sprint, @finekatie completed review of the following pages as assigned in #2546 :

- [Icon accessibility tests](https://designsystem.digital.gov/components/icon/accessibility-tests/)
- [Table accessibility tests](https://designsystem.digital.gov/components/table/accessibility-tests/)
- [Typography accessibility tests](https://designsystem.digital.gov/components/typography/accessibility-tests/)

Next, the team will work together to make updates that came out of the review.

[Plain language review is outlined in this document.](https://docs.google.com/document/d/1ixCyiEGtikB7q2r_Ha2Xlr1R6nBBqAznRpoMBd7pkZ4/edit#heading=h.l8qur6xdsj9z)

@finekatie also provided the following recommendations:

1. I think a how-to for color contrast checking is a great idea if we know users are unfamiliar with how to do that.
2. Instructions for adjusting text spacing and size with a plugin - A particular plug in or any plugin? Does that open up a pandora's box for different operating systems or anything? Even if that's fine, how many tests do they NEED to run and when does it become too many to keep them engaged in doing the work?

**Comment by amyleadem** [comment]
Putting this on hold until PR #2581 is merged.
