### ISSUE TITLE
USWDS - Bug: Correct capitalization of npm at the beginning of sentences on "Getting started for developers" page

### ISSUE THREAD

**Issue by sarah-sch** [uswds/uswds-site#2624]
This issue is for the [Getting started for developers](https://designsystem.digital.gov/documentation/getting-started-for-developers/) page.  Where possible, avoid beginning sentences with words like "npm" that conventionally begin with a lowercase letter. When it appears at the beginning of a sentence, capitalize the N in npm.  

[See this conversation in Slack for more context](https://gsa-tts.slack.com/archives/C050HRGN7/p1713367302497929) on the decision about why to capitalize the N in npm at the beginning of a sentence.

**Comment by mahoneycm** [comment]
@sarah-sch Looks like the only potential change on this page is the bullet point for `npm`. Should I go ahead and capitalize here? Or does this get a pass since it's not a full sentence and it's just referring to the tool?

**Comment by sarah-sch** [comment]
> @sarah-sch Looks like the only potential change on this page is the bullet point for `npm`. Should I go ahead and capitalize here? Or does this get a pass since it's not a full sentence and it's just referring to the tool?

@mahoneycm - yes, I think you should capitalize there.

**Comment by mahoneycm** [comment]
Since I was in the repo, I did a quick search and updated other npm references that needed to be updated to match the new pattern! 

Pages updated were:
- Getting started for developers
- Maturity model
- Website policies and notices

All references of npm on site should be good to go after #2659 👍
