### ISSUE TITLE
Add April MC Q&A to Discussions

### ISSUE THREAD

**Issue by finekatie** [uswds/uswds-site#2630]
Add Add [questions from the April Monthly Call](https://docs.google.com/spreadsheets/d/1qLr8JzIbnVjqa44Rki8nVr4--Ls9G7TYvU3VT2ymrXk/edit#gid=0) to a Discussion post.

[Working draft of Q&A for review](https://docs.google.com/document/d/18mWkMwycX9shpGkdDHVv7zfEE5DrlEeS0UGJgUFazUg) 

- [x] Draft Q&A after April monthly call
- [x]  Get review from dev team members
- [ ]  Get approval from fed team
- [ ]  Post to GitHub

**Comment by finekatie** [comment]
Draft prepped 4/18 after meeting. Sarah has reviewed. Seeking some dev input before handing off for FFR.

**Comment by finekatie** [comment]
Hi @mejiaj , @mahoneycm and @amyleadem, Would love your eyes on this Q&A. There are some questions that still need answers and we also need eyes on the responses we documented. Grateful for any and all input!

**Comment by finekatie** [comment]
Followed up to ask James to take a look.

**Comment by mejiaj** [comment]
I've added initial answers.

**Comment by sarah-sch** [comment]
Sharing [the April MC Q&A for fed review](https://docs.google.com/document/d/18mWkMwycX9shpGkdDHVv7zfEE5DrlEeS0UGJgUFazUg/edit?usp=sharing). Thank you, @annepetersen and @thisisdano!

**Comment by finekatie** [comment]
This was approved and published on Friday 5/10
