### ISSUE TITLE
Add April Monthly Call content to Monthly Calls page

### ISSUE THREAD

**Issue by finekatie** [uswds/uswds-site#2632]
## Purpose
To add the April monthly call video and video (if available) to the [USWDS monthly calls page](https://designsystem.digital.gov/about/monthly-calls/).

## References
[Digital.gov April event page](https://digital.gov/event/2024/04/18/uswds-monthly-call-april-2024/)

## Steps to be completed

- [x]  [Draft copy for monthly calls page](https://docs.google.com/document/d/1jMV62J7RTXB-ER6Xh3hXqNIpph1LH6aCnhvka3Bc-1o)
- [x]  Get feedback from content team
- [x]  Get approval of content from fed team
- [x]  Work with dev team on adding #2630
- [x]  Create branch to update YML page
- [x]  Submit pull request - will be closed by #2671 
- [ ]  Pull request approval

**Comment by finekatie** [comment]
Draft is created. Needs review and we still need April Q&A review as well.

**Comment by sarah-sch** [comment]
@finekatie - [made a few small suggestions](https://docs.google.com/document/d/1jMV62J7RTXB-ER6Xh3hXqNIpph1LH6aCnhvka3Bc-1o/edit?usp=sharing). Looks good!

**Comment by finekatie** [comment]
Need to get Q&A copy edited, and then we can send for FFR. Will visit next week.

**Comment by mejiaj** [comment]
@finekatie should this be part of the May milestone?

**Comment by finekatie** [comment]
> [@finekatie](https://github.com/finekatie) should this be part of the May milestone?

I suppose so!

**Comment by finekatie** [comment]
Copy is ready for FR. Still waiting for Q&A link but this could go up and we can add link later.

**Comment by finekatie** [comment]
Waiting for FR/FFR to get in PR.

**Comment by finekatie** [comment]
Anne and Dan approved content. PR created and needs review and approval.
