### ISSUE TITLE
Historic report of Touchpoints feedback

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-site#2647]
Create a report of all historic Touchpoints data that depicts at least the following:

- What pages were most helpful
- What pages were least helpful
- Overall CSAT
- Trends in feedback

**Comment by jaclinec** [comment]
I have downloaded the data and started cleaning it in Excel.

**Comment by jaclinec** [comment]
I've finished analyzing and synthesizing data and have created drafts for the [USWDS Survey Findings Report](https://docs.google.com/document/d/12_k4q2vQppwyB8Ggbyrugt-ZR6pepo0kohj11VhGTFI/edit?usp=sharing) and the [Survey Findings Slide Deck](https://docs.google.com/presentation/d/1HMKQLO7QayLn1OWKWdVbeVA6K17VhTuXRIAwEIY3F6o/edit?usp=sharing).

Just need to do fine tuning before these are finalized. After finalizing, findings will be presented to the team.

**Comment by jaclinec** [comment]
The findings written report and slide deck are complete (see links above) and results were presented to the team in today's CS/UX sync, so this issue can be marked as done. 

Next step is creating issues from the findings and recommendations. [#367](https://github.com/uswds/uswds-team/issues/367)

**Comment by annepetersen** [comment]
Thanks Jacline!
