### ISSUE TITLE
CC a11y: publish Identifier checklist - create PR

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-site#2669]
## Summary
Publish the `usa-identifier` accessibility test checklist items found in the [Critical Checklist spreadsheet](https://docs.google.com/spreadsheets/d/1fAJaObQHv7aIaeUpH4fTLmauhmugMtNCrbpZe4BJcPY/edit?usp=sharing) (Google Doc :lock:). 

The process for creating a new accessibility test page can be found in the [Creating accessibility checklists - process doc](https://docs.google.com/document/d/14WTCsdzgwpoz_Miztd66RmEGfwwSEUFCVN1DkSQITTE/edit#heading=h.fa3sv1ray42g) (Google Doc :lock:).

**Comment by amyleadem** [comment]
Moving this issue to the "hold" status while we wait for the content team to finish drafting the gherkin statements.

**Comment by amyleadem** [comment]
This issue is ready to work now that the gherkin summaries have been written. 👍
