### ISSUE TITLE
USWDS-Site - Bug: empty Documentation section

### ISSUE THREAD

**Issue by jfredrickson** [uswds/uswds-site#2677]
### Describe the bug

There is an empty or incomplete section on the USWDS site: https://designsystem.digital.gov/documentation/developers/

### Steps to reproduce the bug

1. Visit https://designsystem.digital.gov/documentation/developers/
2. Visit any link under the "Documentation" side nav

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds-site/issues) for duplicate bug reports.

**Comment by brunerae** [comment]
Closing as duplicative of https://github.com/uswds/uswds/issues/5931
