### ISSUE TITLE
USWDS - Site - Known issue: Add known issue to time picker

### ISSUE THREAD

**Issue by jaclinec** [uswds/uswds-site#2683]
Usability test findings from the 'zebra' batch, which included testing time picker, revealed some issues that we should add to the 'known issues' section for memorable date. We should also add an alert.

Known issue:
[USWDS - Time picker: Verbose and unclear screen reader announcements make selecting and clearing a time difficult for some users. #5905](https://github.com/uswds/uswds/issues/5905)

**Comment by thisisdano** [comment]
Fixed by https://github.com/uswds/uswds/pull/6147
