### ISSUE TITLE
Add May MC Q&A to Discussions

### ISSUE THREAD

**Issue by finekatie** [uswds/uswds-site#2696]
Add [questions and answers from the May Monthly Call](https://docs.google.com/spreadsheets/d/1qLr8JzIbnVjqa44Rki8nVr4--Ls9G7TYvU3VT2ymrXk/edit#gid=525308354) to a Discussion post.*

- [x] Draft Q&A after May monthly call
- [x]  Get review from team members
- [x]  Get approval from fed team
- [x]  Post to GitHub

[Working draft of Q&A for review](https://docs.google.com/document/d/1U4bEMp0s03l4RNoEUPU5Rp5LZSr6SwRnILOlhKqWj0s/edit)

* Note: Answers were not documented in the spreadsheet. review [Transcript from call](https://docs.google.com/document/d/1TLPmuDhQ-yBvm9dX38quadzG5A7bwfyevoDa-TzAXLU/edit) for the full answers. It may also be helpful to [watch the full video](https://drive.google.com/file/d/1m3eYHyfiS4QLuhhUjqAl_SuLn080GoWE/view).

**Comment by finekatie** [comment]
Hey @sarah-sch , I just finished drafting the Q&A. Wondering if you might review before I send to Dan and Anne for review and ffr. Draft link is above.

**Comment by mejiaj** [comment]
Removing triage label because this is already assigned to a sprint.

**Comment by finekatie** [comment]
> Removing triage label because this is already assigned to a sprint.

Oh that's weird. Wonder how that got there. lol Thanks

**Comment by finekatie** [comment]
Shared with @amycole501  and @alex-hull to get feedback as well.

**Comment by alex-hull** [comment]
Shared comments in document.

**Comment by sarah-sch** [comment]
@finekatie - I added some suggestions [to the document](https://docs.google.com/document/d/1U4bEMp0s03l4RNoEUPU5Rp5LZSr6SwRnILOlhKqWj0s/edit?usp=sharing
) for clarity.

**Comment by finekatie** [comment]
Amy, Alex and Sarah have completed review. I left some comments in for @annepetersen  and @thisisdano to look at as part of FFR. Handing off today.

**Comment by thisisdano** [comment]
Sent the transcript out for author review

**Comment by finekatie** [comment]
Whitney approved and @thisisdano ok'd Katie to go forward with creating discussion page.

**Comment by finekatie** [comment]
Posted to GH today: https://github.com/uswds/uswds/discussions/5952. This is complete.
