### ISSUE TITLE
Add May Monthly Call content to Monthly Calls page

### ISSUE THREAD

**Issue by finekatie** [uswds/uswds-site#2698]
## Purpose
To add the May monthly call video and video (if available) to the [USWDS monthly calls page](https://designsystem.digital.gov/about/monthly-calls/).

## References
[Digital.gov May event page](https://digital.gov/event/2024/05/16/uswds-monthly-call-may-2024/)

## Steps to be completed

- [x] [Draft copy for monthly calls page](https://docs.google.com/document/d/13iAE34GCgyJ4CxgSehIFDxlrlKAipFlhbidfsk7QA_I/edit#heading=h.np764fsuy3vf)
- [x]  Get feedback from content team
- [x]  Get approval of content from fed team
- [x]  Work with team on adding May MC Q&A
- [x]  Create branch to update YML page
- [x]  Submit pull request - will be closed by #2708  
- [ ]  Pull request approval

**Comment by sarah-sch** [comment]
@finekatie - this text looks good to me!

**Comment by finekatie** [comment]
Handing draft off to @thisisdano and @annepetersen for FFR before the PR.

**Comment by thisisdano** [comment]
Copy approved, ready to draft a PR

**Comment by finekatie** [comment]
PR #2707 created. Need checks on tests to get preview link.

**Comment by finekatie** [comment]
Sending for @thisisdano to review in PR #2708 today for merge.
