### ISSUE TITLE
Audit links on Design principles page

### ISSUE THREAD

**Issue by finekatie** [uswds/uswds-site#2733]
Create document that lists all resource links from the [Design principles](https://designsystem.digital.gov/design-principles/) page. 

Document is here: https://docs.google.com/spreadsheets/d/1n2qzP7F2osR-kis2wSJcwZsXZ69WUMzQzxvVsMnc7PA
Make recommendations and review with team.
Use approved recommendations to update page (related issue #2573 ) and share progress on TTS audit

**Comment by finekatie** [comment]
Findings:

There are 98 links on the page
--
22 links are broken or redirected and need correction, or are duplicative
38 links may be outdated, and need some kind of review
38 links are ok.

**Comment by brunerae** [comment]
Updates to be made as part of #2573
