### ISSUE TITLE
USWDS-Site - Bug: Broken link on Design Principles page leads to spam

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-site#2770]
### Describe the bug

On the Design Principles page, a link in the Practical Actions section formerly pointing to "Inclusive Design Principles" is broken and now leads to spam.

### Steps to reproduce the bug

1. Navigate to https://designsystem.digital.gov/design-principles/
2. Scroll to Practical Actions section
3. Click link in Design Generously bullet point

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds-site/issues) for duplicate bug reports.

**Comment by mejiaj** [comment]
This URL seems to be the replacement: `https://inclusivedesignprinciples.info/`

![image](https://github.com/user-attachments/assets/a2e3157c-3b27-43aa-9aed-15d57bef080d)

**Comment by brunerae** [comment]
Agreed, @mejiaj - confirming with the team then will draft a PR to fix this!
