### ISSUE TITLE
USWDS-Site - Feature: Use LTS in nvmrc

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds-site#2784]
### Is your feature request related to a problem? Please describe.

To stay better aligned with current LTS node we should update our NVMRC file.

**Currently**
https://github.com/uswds/uswds-site/blob/7ea3b8c37dcfb9fc4df87ecfb9b7da1427c5d3a9/.nvmrc#L1

### Describe the solution you'd like

We should set to `lts/*`.

### Describe alternatives you've considered

n/a

### Additional context

We should double-check CircleCI config to make sure the version matches.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds-site/issues) for duplicate feature requests.

**Comment by kodyjackson** [comment]
Working on the changing the version to lts.
