### ISSUE TITLE
USWDS-Site - Documentation: Remove redundant nunjucks reference

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds-site#2809]
Nunjucks is mentioned in pagination guidance and we no longer use it. We should replace with more general guidance or remove it completely.

https://github.com/uswds/uswds-site/blob/b9d50694d88b0f04bc9f027e450ef78c2c44496f/_components/pagination/guidance/implementation.md#L1

### Preview

<img src="https://github.com/user-attachments/assets/179a4654-a1dc-43c6-bdce-0aa54fbbaff8" width="500" />

[Using the pagination component](https://designsystem.digital.gov/components/pagination/#:~:text=the%20reading%20order.-,Using%20the%20pagination%20component,them%20in%20the%20Nunjucks%20templates%20for%20Pagination%20in%20our%20source%20code.,-Set%20the%20current)

**Comment by amyleadem** [comment]
I see a few possible options to address this:
1. Wondering if we can remove the entire section intro highlighted in the attached screenshot. (It feels like the information is implied, but maybe it is good to still be explicit):

    > Unlike many USWDS components, Pagination includes behaviors we cannot build into the HTML, CSS, and JavaScript we ship with the design system. Developers will need to build these behaviors into their Pagination templates. We’ve outlined these behaviors below, and included them in the Nunjucks templates for Pagination in our source code.
2. Alternatively, maybe we can just remove the sentence about Nunjucks?
    > We’ve outlined these behaviors below, and included them in the Nunjucks templates for Pagination in our source code.
3. OR if we think the [twig template](https://github.com/uswds/uswds/blob/develop/packages/usa-pagination/src/usa-pagination.twig) has valuable info, we replace the Nunjucks reference with Twig:
    > We’ve outlined these behaviors below, and included them in the Twig template for Pagination in our source code.
    
Option 3 might be the cleanest, easiest option, but I'd be curious to hear what others think.
