### ISSUE TITLE
USWDS-Site - Feature: Update website standards to align with Federal Web Standards

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-site#2834]
### Is your feature request related to a problem? Please describe.

We need to update the website standards page to align with Federal Web Standards. 

### Describe the solution you'd like

Update the page content to reflect standards ([doc](https://docs.google.com/document/d/1eN8aLjKGcrxwYR4MFc_E-ShdMhqYRHyiAZ1-jJayl6U/edit#heading=h.xh0ppbwzbscz) 🔒)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds-site/issues) for duplicate feature requests.

**Comment by annepetersen** [comment]
The linked site is ready to go and they hope to remove the prototype label shortly. Could we coordinate this to go live around the same time? (Which is soon!)
