### ISSUE TITLE
USWDS-Site - Feature: Add modal accessibility guidance for trapping focus

### ISSUE THREAD

**Issue by amycole501** [uswds/uswds-site#2840]
### Is your feature request related to a problem? Please describe.

The modal component code does trap the users' focus inside the modal upon activation.

However there is no callout to ensure that it is a key element to accessibility compliance for that component.

### Describe the solution you'd like

On the modal page https://designsystem.digital.gov/components/modal/ under "accessibility" please add the following:

Ensure keyboard focus is trapped inside the modal. When using a keyboard to test the modal, ensure focus does not move to the page behind it.

### Describe alternatives you've considered

The modal accessibility tests will expand on this guidance but it is important to call out keyboard focus for the modal to highlight its importance.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds-site/issues) for duplicate feature requests.

**Comment by brunerae** [comment]
@uswds/a11y and Anne to take a look at this again and how the content looks on the page. May want to consult @uswds/content.
