### ISSUE TITLE
Add September Monthy Call to Monthly Calls page

### ISSUE THREAD

**Issue by finekatie** [uswds/uswds-site#2849]
### Purpose
To add the September monthly call video and video (if available) to the [USWDS monthly calls page](https://designsystem.digital.gov/about/monthly-calls/).

### References
[Digital.gov September event page](https://digital.gov/event/2024/09/19/uswds-monthly-call-september-2024/)

### Steps to be completed

- [x] [Draft copy](https://docs.google.com/document/d/1p1S5smK5zM7O_bV2x0L0yuUfSh5glZCA9XOY1ld82IQ) for monthly calls page
- [x] Get feedback from dev team
- [x] Get approval of content from fed team
- [x] Work with team on adding September MC Q&A
- [x] Create branch to update YML page
- [x] Submit pull request - will be closed by: #2934 
- [x] Pull request approval

**Comment by JaymeCharles** [comment]
Anne suggested adding additional detail to the MC summary copy. I'll need to check in with Jacline for specifics when she returns from PTO.

**Comment by JaymeCharles** [comment]
Sent updated copy to Dan and Anne for FFR

**Comment by JaymeCharles** [comment]
Accepted Dan's 10/4 edits. @finekatie Ready for the PR. Sorry for letting this fall through the cracks a bit!

**Comment by JaymeCharles** [comment]
Video is now available! [](https://www.youtube.com/watch?v=E826mR1B6_Y )

**Comment by finekatie** [comment]
I added to PR and got approval from Anne. This will be published.
