### ISSUE TITLE
USWDS-Site - What's new: Prototype combined "What's new" and "News and updates" page (Phase 1)

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds-site#2859]
## Summary
Prototype a new content structure for the [What's new](https://designsystem.digital.gov/about/whats-new/) and [News and updates](https://designsystem.digital.gov/about/updates/) pages. 

## Task list
- Make "News and updates" a child of "What's new"
- Explore opportunities to add CTAs to other ways to stay up to date with USWDS (Monthly call, newsletter, combined changelogs)
- Preview some "News and updates" posts on the "Whats new" page

## Related documents
- [USWDS News Revival Plan](https://docs.google.com/document/d/1tq0Z9PVVSr3Gp-YgsiPJVYJNHnYFY9CGktBL9KprTcU/edit) (Google docs :lock:)
- [What's new meeting notes](https://docs.google.com/document/d/1GTMtepdyng47cVTEF164c9koM8YVFd_cpQJ-4-FvcIo/edit#heading=h.gzr02v7cd52e) (Google docs :lock:)

**Comment by brunerae** [comment]
@brunerae / @finekatie - create sub-issues for content/UX work (content types, content model, etc.)

**Comment by amyleadem** [comment]
## Update
This prototype should demo:
- link to release notes
- link to changelogs
- link to github discussions
- news feed with sample content types
- subpage for full news feed
- subpage for collected changelogs

**Comment by amyleadem** [comment]
## Update
This is now considered phase 1 of the prototype. We will follow up with a phase 2 of the page layout in #2967.

**Comment by amyleadem** [comment]
Closing this issue as complete now that phase 1 has been merged in with PR https://github.com/uswds/uswds-site/pull/2958
