### ISSUE TITLE
November 2024 Newsletter

### ISSUE THREAD

**Issue by finekatie** [uswds/uswds-site#2871]
### Helpful links:
[November newsletter draft here
](https://docs.google.com/document/d/14M08mGmxc2hwZRTqYoLLq8dYS-Xu6xyTMyKgTiG3xSc)[2024 Newsletter folder in Google Drive](https://drive.google.com/drive/folders/1mErWw9qfDP3wqrJDfZEAFhKYKTUFqSQK)
[GovDelivery](https://admin.govdelivery.com/session/new)
[November Comms Timeline](https://docs.google.com/document/d/1VmeJHR_Jnin1clPsKIwV33OVNDf63yEnQo6VOWdkLts/edit#heading=h.4y82866nl1nf)

### Steps to send newsletter

**Draft copy**

- [x] New release/compile -
- [x] New USWDS sites -
- [x] Accessibility feature -
- [x] Featured component discussions
- [x] October monthly call recap
- [x] November monthly call info

**Review**
- [x] Review by content team
- [x] Review and feedback from larger team if needed
- [x] FFR - Approval by Anne and Dan

**Compile**
- [x] Add content to GovDelivery
- [x] Proofread
- [x] Publish

**Comment by JaymeCharles** [comment]
Added checklist items and deadlines to the new [comms content calendar](https://docs.google.com/document/d/1VmeJHR_Jnin1clPsKIwV33OVNDf63yEnQo6VOWdkLts/edit#heading=h.4y82866nl1nf)

**Comment by finekatie** [comment]
Worked on this all week and had reviews by Amy L, Charlie M, Jacline C. and Amy C. Will hand off as-is to Feds today.

**Comment by finekatie** [comment]
Hi @thisisdano and @annepetersen, the [November Newsletter Draft is ready for your review.](https://docs.google.com/document/d/14M08mGmxc2hwZRTqYoLLq8dYS-Xu6xyTMyKgTiG3xSc). 
Lots of comments and questions, but it's about 70% there. 
Here's the editorial plan:
 - Approve for publish by 11/14 EOD, 11/15 early afternoon absolute latest for 11/15 publish.
 - Email promo to go out 11/12, slack promo out Monday 11/18 or Tuesday 11/19

note: the What's New page is not dependent on this, and nor is this dependent on it. 

Thank you!!

**Comment by finekatie** [comment]
FFR completed 11/14. 
11/15 Got team member to review test. Reviewed. Sent.
