### ISSUE TITLE
USWDS-Site: Draft content for summary box accessibility checklist page 

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds-site#2982]
## Summary
Draft the website content for the summary box accessibility checklist items in the [Critical Checklist spreadsheet](https://docs.google.com/spreadsheets/d/1fAJaObQHv7aIaeUpH4fTLmauhmugMtNCrbpZe4BJcPY/edit?usp=sharing) (Google Doc :lock:)

## Tasks
- [x] Draft checklist content and send for review with A11Y
- [x] Final edits to checklist content

**Comment by finekatie** [comment]
Halfway through gherkins.

**Comment by finekatie** [comment]
Gherkins done and ready for your review @alex-hull !

**Comment by alex-hull** [comment]
Reviewed and marking as done. @amyleadem @RachelCorsino this is ready for y'all!
