### ISSUE TITLE
USWDS-Site: Draft content for process list accessibility checklist page

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds-site#2983]
## Summary
Draft the website content for the process list accessibility checklist items in the [Critical Checklist spreadsheet](https://docs.google.com/spreadsheets/d/1fAJaObQHv7aIaeUpH4fTLmauhmugMtNCrbpZe4BJcPY/edit?usp=sharing) (Google Doc :lock:)

## Tasks
- [x] Draft checklist content and send for review with A11Y
- [x] Final edits to checklist content

**Comment by finekatie** [comment]
Hi @alex-hull , process list is ready for review!
