### ISSUE TITLE
USWDS-Site: Draft content for collection accessibility checklist page

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds-site#2984]
## Summary
Draft the website content for the collection accessibility checklist items in the [Critical Checklist spreadsheet](https://docs.google.com/spreadsheets/d/1fAJaObQHv7aIaeUpH4fTLmauhmugMtNCrbpZe4BJcPY/edit?usp=sharing) (Google Doc :lock:)

## Tasks
- [x] Draft checklist content and send for review with A11Y
- [x] Final edits to checklist content

**Comment by finekatie** [comment]
I'm done drafting, @alex-hull ! Review when ready.

**Comment by alex-hull** [comment]
Reviewed and everything looks good! Marking as done. @amyleadem @RachelCorsino this is ready for y'all!
