### ISSUE TITLE
Validate built site's HTML5 during 'npm test'

### ISSUE THREAD

**Issue by toolness** [uswds/uswds-site#325]
This is spun off from #269. From that issue, I wrote:

> ... "ensure our HTML is valid" is turning out to be a bit tricky: it seems like the only really robust solution out there that everyone uses is http://validator.w3.org/nu/, which is powered by https://github.com/validator/validator/.  However, that thing requires Java 8, which I guess is why most people just use the website; existing modules in software package repository like [npm's `html-validator`](https://www.npmjs.com/package/html-validator) are just simple wrappers for the web service.

**Comment by maya** [comment]
Your suggestion is appreciated, however it is not on the current product roadmap.
