### ISSUE TITLE
Document how to use Sass files included in zip files

### ISSUE THREAD

**Issue by toolness** [uswds/uswds-site#353]
As of https://github.com/18F/web-design-standards/pull/2028, we're including our SASS files in the ZIP file that contains all our JS/CSS/image assets, so we should update the documentation to reflect this.

This is the first issue I've filed that is specific to the new version of USWDS that hasn't been released yet, so I'm wondering what we should do... Should we just push the documentation site at the same time as we release the next version of USWDS?  Another alternative might be to create a liquid plugin macro that allows us to only include certain content if the [version of USWDS we're using](https://github.com/18F/web-design-standards-docs/pull/349) meets a certain criteria.

**Comment by maya** [comment]
Seems like the Sass files are already documented in "Where things live" https://designsystem.digital.gov/getting-started/developers/#where-things-live
