### ISSUE TITLE
Document Sass path variable overrides

### ISSUE THREAD

**Issue by toolness** [uswds/uswds-site#354]
I only knew about the `font-path` and `img-path` overrides because I stumbled upon https://github.com/18F/web-design-standards/issues/1797. If I had known about them earlier, it would have saved me some headaches in other projects that I'd used the standards in, so they might be useful to document in the [developer's guide](https://standards.usa.gov/getting-started/developers/).

**Comment by maya** [comment]
[Getting started > For developers > Customization and theming](https://designsystem.digital.gov/getting-started/developers/#customization-and-theming) may be a good spot for this.
