### ISSUE TITLE
"Code" accordion should be expanded on page load, not collapsed

### ISSUE THREAD

**Issue by toolness** [uswds/uswds-site#368]
I forget where it was discussed, but I think we've had issues with people missing the code examples on the docs site (I know I've sometimes not found code examples b/c my eyes are scanning for syntax-highlighted monospaced code as I scroll down a page). @msecret also [consulted the design systems Slack](https://github.com/18F/web-design-standards/issues/1765#issuecomment-316516777) and they recommended keeping the code accordion expanded initially to avoid this kind of problem.

**Comment by maya** [comment]
Closing, for now, may be addressed in the new component page design work.
