### ISSUE TITLE
Make jekyll site run faster

### ISSUE THREAD

**Issue by maya** [uswds/uswds-site#417]
The site is taking 18 seconds to build which makes it really time consuming to work on. It's loading all fractal components on every update which seem to be taking most of the time. Is it possible to only load them incrementally when that component has changed?

Related to #334.

/cc @toolness

**Comment by maya** [comment]
You can run: `npm run serve` to run incremental + livereload

**Comment by maya** [comment]
Maybe it's doing something goofy with pulling in components

**Comment by maya** [comment]
The components are loaded from `node_modules/uswds/build/components/render/`, e.g.:
```
Loading fractal component accordion--default from node_modules/uswds/build/components/render/accordion--default.html.
```

**Comment by thisisdano** [comment]
Updated to Jekyll 4.0 and this is no longer such a critical issue
