### ISSUE TITLE
Document usa-input-required, with caveats

### ISSUE THREAD

**Issue by toolness** [uswds/uswds-site#455]
It was recently decided in https://github.com/18F/web-design-standards/issues/2238 that `usa-input-required` is in fact *not* deprecated and will continue to be supported. However, when `usa-input-optional` was added in 1.4.0, all references to it in the documentation were removed and replaced with `usa-input-required`, thus eliminating any traces of `usa-input-required` from the documentation.

Since the class is no longer deprecated, it should be documented somewhere, preferably with caveats that point users to [best](http://uxmovement.com/forms/why-users-fill-out-less-if-you-mark-required-fields/) [practices](https://www.nngroup.com/articles/web-form-design/) indicating that `usa-input-optional` should be preferred whenever possible.

**Comment by thisisdano** [comment]
`Required` may be back in business again! The best-practice guidance is shifting: https://www.nngroup.com/articles/required-fields/

**Comment by thisisdano** [comment]
For future reference: https://dequeuniversity.com/tips/identify-required-elements

**Comment by thisisdano** [comment]
@pglevy This is an instance where the UX guidance environment has shifted, and our guidance may need to be updated to match. What can we learn about current best practice for form field labelling?

**Comment by thisisdano** [comment]
Going to close this issue and make a new one that better captures the issue at hand.

**Comment by thisisdano** [comment]
New issue here: https://github.com/uswds/uswds-site/issues/1163
