### ISSUE TITLE
Existence of "develop" branch is extremely confusing

### ISSUE THREAD

**Issue by toolness** [uswds/uswds-site#558]
Hi, I was trying to help debug an issue with the aXe tests breaking, and was using the `develop` branch because I assumed that since it's the default branch for [uswds/uswds](https://github.com/uswds/uswds), it would also be the main branch for this documentation. 

After spending time debugging and creating a fix, I was about to issue a PR until I discovered that `develop` is actually quite out of date and hasn't been updated since Feb 5, and that my fix was actually completely irrelevant to the current state of `master`. 😣 

There's a number of ways to avoid this confusion; one is to make sure both uswds and uswds-site use the same default branch name.  Another is to just get rid of the `develop` branch on uswds-site to ensure that the kind of problem I ran into doesn't happen again.

**Comment by thisisdano** [comment]
@toolness First — thank you for taking the time to look into our aXe and headless Chrome issues, we really appreciate it. 🙏 I see how the `develop` branch is confusing and frustrating!

@maya As far as I remember, we'd stopped using the `develop` --> `master` workflow to make our release process more streamlined. Is there any reason to continue to maintain a `develop` branch at this point? I would vote to delete it unless you have an objection.

**Comment by maya** [comment]
I don't think we need it. I think we kept it as a back up in case we didn't like working off master or needed it for some other reason. Also, it was a protected branch so a little more effort to delete. We can delete it if it's causing confusion.

**Comment by maya** [comment]
Deleted the branch, so should clear things up.

**Comment by maya** [comment]
Sorry, we should have clarified but we're working on the `add-utility-docs` branch, not `master` or `develop`.
