### ISSUE TITLE
styleguide.css 404's on add-utility-docs branch

### ISSUE THREAD

**Issue by toolness** [uswds/uswds-site#563]
I'm unclear on why the [`add-utility-docs` branch](https://github.com/uswds/uswds-site/tree/add-utility-docs) doesn't at least have a WIP PR filed for itself, but I was asked to investigate why [aXe is failing on it](https://circleci.com/gh/uswds/uswds-site/1408) with the following output:

```
Static file server is listening at http://d2e72c53e10f:43543.
Chrome is debuggable on http://chrome:9222.
Running aXe on:
  /page-templates/docs/ A network request failed to load.
{ requestId: '1000000189.2',
  timestamp: 12285.282268,
  type: 'Stylesheet',
  errorText: 'net::ERR_ABORTED',
  canceled: true }
Terminating with exit code 1.
```

This isn't great error output because it's not actually reporting anything about the URL in question that's failing to load.  But visiting the Jekyll site in the browser reveals the following:

> ![css-fail](https://user-images.githubusercontent.com/124687/41165450-b9004992-6b0b-11e8-9fab-466a4b99b845.png)

So it looks like the `styleguide.css` file isn't loading, and that's breaking the CSS of the whole site. (This is important to aXe because lots of the accessibility characteristics of the page, e.g. color contrast ratios, is determined by the stylesheet.)

Once this 404 is fixed, the aXe tests should work (or at least, they should no longer report the kind of error they're currently reporting).

**Comment by thisisdano** [comment]
Is it convention to always have a WIP PR on a working branch?

**Comment by toolness** [comment]
I think it is--otherwise an open-source project's community doesn't have any visibility into what's being worked on at a given time. It also makes it a lot easier to code review the PR incrementally, among other benefits.  See this nice post for more info: https://ben.straub.cc/2015/04/02/wip-pull-request/

**Comment by thisisdano** [comment]
Thanks @toolness that makes sense — we'll adopt that as our own convention!

**Comment by maya** [comment]
Thanks @toolness! We've fixed the 404ing of the stylesheet, CircleCI is passing, and it's building appearing correct on Federalist 🎉 We still can't run `npm test` locally but can open a new issue for that. Thanks again!
