### ISSUE TITLE
typography documentation issues

### ISSUE THREAD

**Issue by bruffridge** [uswds/uswds-site#566]
Found some issues in the documentation on [typography](https://designsystem.digital.gov/components/typography/) page.

1. Merriweather headings, source sans pro body
    - font weights included in this package is missing: source sans pro light, source sans pro bold, merriweather light, and merriweather italic. These fonts [are included in the default package](https://github.com/uswds/uswds/blob/master/src/stylesheets/core/_fonts.scss).

2. Source Sans Pro headings, merriweather body.
    - The text "Lead paragraph" is listed as being 400 weight, but is actually displayed at 300 weight.

**Comment by maya** [comment]
Hi, thanks for opening this issue. I'm not sure I understand number 1: "font weights included in this package is missing". Could you explain what you experienced and what you were expecting and where/how you expected it?

**Comment by bruffridge** [comment]
What I experienced:


What I was expecting:



which matches what the uswds package actually contains
<https://github.com/uswds/uswds/blob/master/src/stylesheets/core/_fonts.scss>

**Comment by maya** [comment]
Hey @bruffridge, unfortunately I'm still not seeing any content under your headings :/ 
<img width="802" alt="screen shot 2018-06-08 at 11 03 08 am" src="https://user-images.githubusercontent.com/5249443/41173416-a717f7fc-6b0b-11e8-8486-4428e08d6b9a.png">

**Comment by bruffridge** [comment]
I guess it doesn't allow image uploads from email replies. I edited my last comment and added the images.

**Comment by maya** [comment]
Ah got it, that is much clearer, thank you. So the default font pairings listed on the documentation site is correct. More fonts are included in the font file but are not in use. From our last assessment, doing so would not have an effect on page loading times so it seemed OK to leave it as is. Let us know if this doesn't sound right or if you have more questions.

**Comment by maya** [comment]
Documentation fixed here: #567. Doesn't sound like the second issue may be a concern so closing this.
