### ISSUE TITLE
Run autoprefixer on CSS

### ISSUE THREAD

**Issue by maya** [uswds/uswds-site#628]
Ensure we're running autoprefixer on our project CSS e.g. `css/_project-custom.scss`. 

I noticed it wasn't running when I visited https://v2.designsystem.digital.gov/ in Safari and saw the sticky navigation wasn't working bc there was no `position: -webkit-sticky;` added to the `.sticky` class, only `position: sticky;`.

**Comment by thisisdano** [comment]
I think this is a cssnano configuration issue. See https://github.com/cssnano/cssnano/issues/176
If we match our cssnano config with our autoprefixer config, all should be well.

**Comment by maya** [comment]
@thisisdano good to know! are you able to open the PR for this?

**Comment by thisisdano** [comment]
Oh huh, nevermind, looks like we're just not using autoprefixer _or_ cssnano on the docs site... Maybe I'll port over the config from `uswds` and add the nano options above...

**Comment by maya** [comment]
Fixed in #634.
