### ISSUE TITLE
Perform a Lighthouse performance audit on the site

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds-site#668]
How are we doing? I bet we could tidy things up and make some performance improvements! Let's start by seeing where we are, then pull all the performance tasks into a new epic.

**Comment by mejiaj** [comment]
Audited homepage and accordion page.

Results are pretty nice, we got a score of `97`.

<details>
  <summary>
    Homepage
  </summary>
<p>
<img src="https://user-images.githubusercontent.com/3385219/74543428-f6f8f700-4f0a-11ea-8786-2a6efb91cae8.png" />
</details>


<details>
  <summary>
    Accordion Page
  </summary>
<p>
<img src="https://user-images.githubusercontent.com/3385219/74543547-290a5900-4f0b-11ea-8a78-2c82d5e53abc.png" />
</details>

### Overall
Quick wins:
- Using webp with a jpg fallback
- picture element for images
- proper sizing for images (**Showcase** section uses 1280x720 max-width is 604px +/-)

### Download the test results
[uswds-site-lighthouse.zip](https://github.com/uswds/uswds-site/files/4205028/uswds-site-lighthouse.zip)
