### ISSUE TITLE
Update our design principles

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds-site#670]
Our current design principles read a bit more like a feature list than a set of design principles. Look at the GDS design principles (https://www.gov.uk/guidance/government-design-principles) — these are an appropriate level of abstraction — highlighting real goals and constraints while letting the expression of any solution influenced by these principles take its own form. 

I think our design principles are pretty strong as-is, but there's very little in here about research or putting users first, while we highlight showcasing benefits, which feels like a smaller, more minor idea.

Here's what I suggest:

- - -

**Put user needs first.**
If we don’t know what our users need, we won’t build the right thing. Research, analyze data, and talk to the people who use what we build. Test with them. Continuously validate assumptions, even those of our users. Listen, and try to understand.

**Make it easy to do the right thing.**
The U.S. Web Design System should be the easiest way for teams around the federal government to build with contemporary best practices and comply with federal policy. We should cultivate the curiosity, research, and open communication necessary to understand what is best and easiest for those who use the system and for those who use what we build with it.

**Accessibility is fundamental.**
Accessibility isn’t an optional enhancement, it’s at the core of how we design. Every design, asset, and piece of code we offer should meet or exceed the accessibility standards outlined in Section 508, and our guidance should ensure any project-specific customizations perform well for the broadest possible definition of the public.

**Start from existing solutions.**
It’s counterproductive and wasteful to recreate basic components and patterns for every new government website. We should encourage building from a common collection of practical solutions that reflect modern best practices. Enable teams to focus on the their users and their mission, and less on reinventing existing solutions. Do less to do more.

**Be consistent but not static.**
While consistency builds familiarity, our guidance and code should support the diverse needs of government digital services and the teams that understand them. Our guidance should be specific enough to be practical but general enough to be extensible. We should support and welcome new information. Our goal should be continuous user- and mission-focussed improvement, not static uniformity.

**Share what we do.**
Be open about what we do and encourage others to share with us. Honesty, scrutiny, and accountability strengthen our connection to our principles and improve our decision making. We both rely on and contribute back to the commons that sustains our project and its future. We encourage those who build with our tools to follow this example.

**Comment by thisisdano** [comment]
@jz @andrewmaier Any initial thoughts?

**Comment by andrewmaier** [comment]
Hey Dan,

I agree; the existing [USWDS design principles page](https://designsystem.digital.gov/about/design-principles/) frames the principles with user-facing language: "Here’s how using the Design System can help **you".** Instead of positioning them this way, I see design principles as useful tools for helping the USWDS team itself make important design decisions. I like that the updates you've suggested make this clear with a bunch of "we" language (clarifying that these principles will guide the USWDS team itself).

Two of these principles raise my eyebrow: "starting from existing solutions" and "being consistent but not static." 

My concern about starting from existing solutions comes from my position as a researcher: I often find myself questioning existing structures (beliefs, etc.) in my pursuit of value for the user.  (That isn't to say that USWDS isn't a valuable starting point. It is. I'm just not sure this needs to be elevated to a design principle. It *does* feel like a useful starting point for anyone implementing the USWDS.)

My concern about championing consistency is that the solutions to most design problems is "it depends." [This post from 37 signals](https://signalvnoise.com/archives2/getting_real_context_over_consistency.php) really shaped my thinking on this when I did more front-end development. Context is often more important than consistency.



PS: I really welcome the addition of putting user needs first!

**Comment by thisisdano** [comment]
Thanks @andrewmaier!

I tend to agree with your gloss on this and the concerns you raise. It's definitely my hope that our design principles are about _how we make good decisions for the system_ and not abut _how the design system will help your project_. But while they are inward-focussed, I also hope that they can provide an example for those who design with the system as well.

I'm actually glad that a couple of these threw some red flags for you — in a way that might mean they're doing their job, staking out a positions that are, if not _controversial_, at least point to places where teams make real decisions and have real differences of opinion.

I certainly do not mean to stake out the "ours is not to question why" position in any of these principles. What I hope to convey is that defaults can and should be the appropriate starting place, if only to learn, as soon as possible, that these defaults are not the proper solution. But if they _are_, it's better to learn sooner rather than later that you've found a good-enough solution. I wouldn't want to say "end at existing solutions" but I'll stake the claim that they are the appropriate place to start. And if continuing questioning leads to changing the starting point in the system itself — that is acceptable and healthy.

Which, I'd say is connected to `Be consistent but not static` — which, perhaps counterintuitively is mostly a principle about accepting change. I would say that we know that a certain consistency in our solutions to common patterns is a net positive — whether this is strict look-and-feel or other more abstract elements of UX (the position of a `close` icon, or the way a submenu reacts to selection) — because context _does_ matter and one kind of context is that of familiarity. That said, I really do agree with your position that design is a process of understanding and adaptation, and that procustean beds fit everyone... at a cost perhaps too dear to pay.

I think it's important for the design system to prioritize consistency in its components and in the holistic experience of services built with them. And I also think it's important that the design system accommodate the necessary, legitimate adaptations projects will require. That's really one of the primary dualities USWDS 2.0 attempts to synthesize, through the consistency of its theme defaults and the flexibility — within limits — of its system palettes. It attempts to provide an environment for coherent extension and adaptation, a stylistic language that can potentially capture these adaptations as new guidance, and a language itself that's based on animating principles subject to refinement and change themselves.

I think the design system can be a dynamic organizing force that pushes against both entropy and crystallization. It's a bit of a balancing act, but I tend to want to weight the die in favor of incremental, conservative progress.

**Comment by jeremyzilar** [comment]
I do like the **Start from existing solutions.** addition. I feel like it sets the stage for better defining what those patterns and components are.

I really like the focus on openness and honesty in the **Share what we do** principle.

**Comment by thisisdano** [comment]
Added in https://github.com/uswds/uswds-site/pull/682
