### ISSUE TITLE
Roadmap - Up next label is missing margin

### ISSUE THREAD

**Issue by saracope** [uswds/uswds-site#679]
## Description

The Up next label on the [Roadmap](https://designsystem.digital.gov/about/product-roadmap/) doesn't have the same left margin as the other labels. Looks like it was left out of that grouping.

<img width="1247" alt="screen shot 2018-10-18 at 10 06 54 am" src="https://user-images.githubusercontent.com/2197515/47161233-a3977a00-d2bf-11e8-8474-132fbb904b8b.png">

**Comment by maya** [comment]
Removed that label, so this is not an issue any more: https://v2.designsystem.digital.gov/about/product-roadmap/
