### ISSUE TITLE
WebP images are not rendering in Firefox

### ISSUE THREAD

**Issue by korajasekar** [uswds/uswds-site#690]
## Description
Images of type **WebP** are not rendering in Firefox.
Not sure about the status of WebP support for Firefox. In the mean time, PNG or JPG type images could be used as fallback.

## Steps to reproduce the issue

For example, in this link:
https://v2.designsystem.digital.gov/style-tokens/color/overview/
the color wheel images are not loading. Its working fine in Chrome.

**Screenshot:**
![image](https://user-images.githubusercontent.com/8013476/48130218-f1494600-e2b1-11e8-9f59-52df59b86a91.png)

## Browser information
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:63.0) Gecko/20100101 Firefox/63.0

**Comment by thisisdano** [comment]
Thanks for letting us know. This will be gone in the next site update. Longer term we’ll probably re-integrate webp as part of a responsive image solution. But for now, it’ll turn into a jpg!

**Comment by korajasekar** [comment]
Got it. Should I close the issue or wait for it to get resolved?

**Comment by thisisdano** [comment]
Let's leave it open until the site is fixed. It'll feel good to close it when the site actually looks right!

**Comment by thisisdano** [comment]
Fixed in https://github.com/uswds/uswds-site/pull/688
