### ISSUE TITLE
Need to update Header example images in docs

### ISSUE THREAD

**Issue by greensteph** [uswds/uswds-site#697]
## Description

[Header](https://v2.designsystem.digital.gov/components/headers/) example images need to be updated to reflect the code block changes. 

- [ ] Basic Header

- [ ] Basic Header with Mega Menu

- [ ] Extended Header

- [ ] Extended Header with Mega Menu

## Additional information

New screenshots can be grabbed from demo's.

**Comment by maya** [comment]
Done in #729.
