### ISSUE TITLE
When should I use uswds npm package vs uswds-gulp?

### ISSUE THREAD

**Issue by adborden** [uswds/uswds-site#702]
## Description

In trying out the 2.0 beta, folks were a bit confused about when to use uswds-gulp.
https://v2.designsystem.digital.gov/documentation/developers/#install-using-npm describes installing uswds from npm, and then suddenly uswds-gulp is introduced mid-way through. When would I use uswds vs uswds-gulp?

There's a few conversations that raise related questions in and around this thread in [#uswds-public](https://gsa-tts.slack.com/archives/C3F14AHSQ/p1547851638071700).

## Steps to reproduce the issue

N/A

## Additional information [optional]

N/A

**Comment by thisisdano** [comment]
`uswds-gulp` is just a gulp compile/transpile pipeline and includes no USWDS source files of its own.

Any project that wants to modify the USWDS defaults with settings variables needs to compile its Sass. (And folks _should_ want to, the system is way more powerful that way, imo.) Installing USWDS via the `uswds` npm package creates the `dist` folder — which includes precompiled css — but it does not install a Sass watch/compile pipeline for future modifications. That's where `uswds-gulp` comes in.

Until recently, we just counted on users to roll their own compile solution, `uswds-gulp` is an attempt to provide a starting point for compiling proper CSS. The idea is that a project could both `uswds` and `uswds-gulp` together. 

If you already have a way to compile USWDS Sass, you would not need `uswds-gulp`.

Is that helpful?

**Comment by adborden** [comment]
> Is that helpful?

Yes, very. Will you include this in the docs?

**Comment by thisisdano** [comment]
Yeah, I'll try to improve the language in the next sprint's work then link that PR here.

**Comment by thisisdano** [comment]
We added clarification to the docs for this a long time ago, but I'm moving it into the backlog so we make sure to address this issue as we improve getting started docs

**Comment by thisisdano** [comment]
Resolved with new changes to docs and USWDS Compile
