### ISSUE TITLE
natives@1.1.6 hack required after installing beta 5

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds-site#706]
We had to install `natives@1.1.6` after using USWDS Beta 5. This is a weird hack that we don't want want USWDS users to have to worry about. We have no issues building locally without the haclk, and no issues on Federalist — but we were getting fails on Circle CI. 

The issue and its solution can be seen here: https://github.com/gulpjs/gulp/issues/2246

Will upgrading to Gulp 4.x fix this? And if so, do we need to upgrade both here and in the `uswds` repo?

**Comment by maya** [comment]
Done in #726.
