### ISSUE TITLE
Create an introduction to USWDS 2.0 (blog)

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds-site#719]
As we get ready to launch USWDS 2.0 we should understand what we want to communicate about its new features and functionality.

#### At the end of this issue, we should know the answers to the following
How do we communicate what's new in USWSD 2.0 on the home page for new visitors?
What do we need to do to more fully flesh out what's new in USWDS 2.0?
What new page or pages do we need to build?
What content do we need on this page or pages?

**Comment by thisisdano** [comment]
🔒 [Google Doc](https://docs.google.com/document/d/1xl_IOTjN4iRSsoOmDt6NFw9JNHBnXleG3n8nEsVF3MM/edit?usp=sharing)

**Comment by maya** [comment]
Done in #753.
