### ISSUE TITLE
Create a USWDS 2.0 Getting Started guide

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds-site#720]
#### To resolve this issue, we need to document the answers to the following questions
What do folks need to do to get started with USWDS 2.0 (step-by-step)?
What are the key concepts they need to understand?
How can they install USWDS 2.0 on a new or existing site?
What are the technical requirements for USWDS 2.0?
What other resources do we have for designers and developers?

**Comment by thisisdano** [comment]
:lock: [Google doc](https://docs.google.com/document/d/1BGJkp0pIc0JYxyupdHpgW2_DNiN8oiEU-zQpgMjybuE/edit?usp=sharing)

**Comment by maya** [comment]
Is this still relevant?

**Comment by thisisdano** [comment]
It's probably still a good idea, but I'd say we can close this one out
