### ISSUE TITLE
Z-index page not showing content

### ISSUE THREAD

**Issue by maya** [uswds/uswds-site#721]
See: https://v2.designsystem.digital.gov/design-tokens/z-index/

There's a big space between "Z-index tokens" and "Using z-index tokens"

![v2 designsystem digital gov_design-tokens_z-index_](https://user-images.githubusercontent.com/5249443/54307146-2d562580-4588-11e9-9c80-c90ceec6e36a.png)

**Comment by thisisdano** [comment]
It's also missing on its utility page. I think I have the fix, tho

**Comment by maya** [comment]
Fixed in #723.
