### ISSUE TITLE
USWDS site and fractal using different sans fonts

### ISSUE THREAD

**Issue by maya** [uswds/uswds-site#722]
The demo components on the USWDS site are using Public Sans while the fractal size is using Source Sans Pro for the sans serif font. They are both using Merriweather for the serif. Should they be using the same sans serif font?

Fractal site (Source Sans Pro): https://federalist-proxy.app.cloud.gov/preview/uswds/uswds/release-2.0/components/preview/layout--docs.html
USWDS docs site (Public Sans): https://v2.designsystem.digital.gov/page-templates/docs/

**Comment by maya** [comment]
The serif headings also appear to be different sizes.

**Comment by thisisdano** [comment]
I'm not certain it's possible to to use both sans faces at the same time, but I will see if that's actually true.

**Comment by maya** [comment]
Done in #726.
