### ISSUE TITLE
System color tokens page (USWDS 2.0) is missing the blue-cool-vivid family

### ISSUE THREAD

**Issue by bet4a** [uswds/uswds-site#743]
The [System color tokens](https://v2.designsystem.digital.gov/design-tokens/color/system-tokens/) page should include the complete palette of available colors. By my count there should be a total of **47** families listed on that page:
* 22 standard color families,
* 22 corresponding vivid families,
* 3 gray families (`gray-warm`, `gray`, `gray-cool`).

However, the page only shows **46** families—for whatever reason, the `blue-cool-vivid` category and its colors are missing entirely. I’m presuming the omission wasn’t intentional since the [USWDS `blue-cool` definitions](https://github.com/uswds/uswds/blob/v2.0.0-beta.7/src/data/colors/blue-cool.json) include `vivid` variants, which are also shown in the [vivid color wheel](https://v2.designsystem.digital.gov/design-tokens/color/overview/#uswds-color-wheels) graphic:

![image](https://user-images.githubusercontent.com/787536/55178881-aba3f180-515c-11e9-8362-ed1241a4f92a.png)

**Comment by thisisdano** [comment]
Thanks for submitting this issue. We've just updated these images last week at https://v2.designsystem.digital.gov/design-tokens/color/overview/

Here's what I see when I look at the page:

<img width="646" alt="Screen Shot 2019-03-28 at 10 46 46 AM" src="https://user-images.githubusercontent.com/11464021/55180471-eef36580-5146-11e9-932f-445e2efe67bd.png">

Does it look different on your machine? Maybe an old cache?

**Comment by bet4a** [comment]
The issue isn’t with the color wheel; sorry for the confusion. I only included it to point out that there *are* `blue-cool-vivid` colors that have been defined in the USWDS.

(And for what it’s worth, there are actually two color wheels images I see [on the page](https://v2.designsystem.digital.gov/design-tokens/color/overview/#uswds-color-wheels), one for the standard palettes and another for the vivid variants.)
![Screenshot 2019-03-28 at 13 55 23](https://user-images.githubusercontent.com/787536/55181081-4acae800-5161-11e9-956b-1a7965d20bfe.png)

---

In any case, my actual issue solely concerns the [System color tokens](https://v2.designsystem.digital.gov/design-tokens/color/system-tokens/#blue-cool) page, which seems to be missing the `blue-cool-vivid` color family. Here’s a screenshot of the page and with my scribbled annotation of the issue:

![ink](https://user-images.githubusercontent.com/787536/55181508-2de2e480-5162-11e9-99f8-cee07808a3a3.png)

**Comment by thisisdano** [comment]
I getcha now — thanks and sorry for the misunderstanding. I'll reinstate these asap!

**Comment by maya** [comment]
Fixed in uswds/uswds-site#744.
