### ISSUE TITLE
Wrong URL for "theme color tokens" link

### ISSUE THREAD

**Issue by robertromore** [uswds/uswds-site#747]
The "theme color tokens" link on https://v2.designsystem.digital.gov/utilities/color/#advanced-settings (under "Custom Values" -> "Color Palettes" -> "Palette Contents") is currently pointing to https://v2.designsystem.digital.gov/design-tokens/color/state-tokens/ instead of https://v2.designsystem.digital.gov/design-tokens/color/theme-tokens/. 

I believe this is the line that needs changed: https://github.com/uswds/uswds-site/blob/v2/_includes/utilities/color-palettes.html#L44.

**Comment by maya** [comment]
Thanks for letting us know, @robertromore. This is fixed in 101f63b5d90bdd2257d5adfefbbc86f983de2b50.
