### ISSUE TITLE
Links example on dark background using non-default colors

### ISSUE THREAD

**Issue by maya** [uswds/uswds-site#748]
The link is correctly using `base-lighter` `#dcdee0` on the [fractal site](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds/release-2.0/components/detail/links.html), but `#e6e6e6` on the [docs site](https://v2.designsystem.digital.gov/components/typography/#links). 

The dark background is also different: on the fractal site it's using `base-darker` `#3d4551` and on the docs site, it's`#2e2e2e`.

This is probably from the custom theme colors set in the docs site.

**Comment by thisisdano** [comment]
Clearing out the old issues pile. I'm inclined to close this one as I see it as a minor discrepancy between theme tokens and not something the end user might notice. Am I wrong?

**Comment by maya** [comment]
I'd guess that theme tokens set on the site override the default styles. I'll leave it up to you to decide if regularizing this is important or not.
