### ISSUE TITLE
Migration page Footer section needs updated. 

### ISSUE THREAD

**Issue by greensteph** [uswds/uswds-site#758]
On the [Migration](https://v2.designsystem.digital.gov/documentation/migration/) page the Footer class name changes are currently a copy of the Checklist section. Correct table needs added in.

![Screenshot 2019-04-06 18 31 48](https://user-images.githubusercontent.com/11343071/55676062-f202fa00-589a-11e9-89b3-05e9b3845cfc.png)

**Comment by thisisdano** [comment]
Thanks for finding this! Fix is here: https://github.com/uswds/uswds-site/pull/760

**Comment by maya** [comment]
Fixed in #760.
