### ISSUE TITLE
Add usa-sidenav__item to Migration page Sidenav Section

### ISSUE THREAD

**Issue by greensteph** [uswds/uswds-site#759]
Need to add usa-sidenav__item to Migration page chart. Was not previously used in 1.6.x 

<hr>
<h3>2.0</h3>
<img width="480" alt="Screenshot 2019-04-06 19 10 43" src="https://user-images.githubusercontent.com/11343071/55676270-b28adc80-589f-11e9-92fe-d8c9147a4906.png">

<hr>
<h3>1.6</h3>
<img width="553" alt="Screenshot 2019-04-06 19 13 16" src="https://user-images.githubusercontent.com/11343071/55676289-2b8a3400-58a0-11e9-8ae5-1ca1848f79f4.png">

**Comment by thisisdano** [comment]
I appreciate this attention to detail. Thank you! Fix here: #760

**Comment by maya** [comment]
Fixed in #760.
