### ISSUE TITLE
Empty Sections in documentation

### ISSUE THREAD

**Issue by co16353sidak** [uswds/uswds-site#770]
## Description

URL: https://designsystem.digital.gov/documentation/developers/#installation

The `for developers` section of the website seems to be missing content from the documentation, the website shows blank screen after the installation heading and the navigation links on the left target empty sections.

## Steps to reproduce the issue

1. Open the url provided
2. Scroll down to see empty section
3. Click links on the left to see no changes and empty targeting
4. And so on

## Additional information [optional]
<img width="1280" alt="Screenshot 2019-04-11 at 2 08 03 PM" src="https://user-images.githubusercontent.com/35738138/55943225-cd749c80-5c63-11e9-882b-bcb3853a50c3.png">

Would love to work on this issue and solve it if possible. 🥇

**Comment by maya** [comment]
@co16353sidak thanks for opening this issue! It looks like there's some issue displaying the contents of the GitHub README. Also, this is the v2 site and looks like it's referencing the `develop` branch while we want it to reference `release-1.6.10`. The develop branch is now version 2.0. Also, the v2 site is referencing `release-2.0`, while we now want it to reference the `develop` branch.

>Would love to work on this issue and solve it if possible. 🥇

We're always glad to have contributions.
