### ISSUE TITLE
Slack logo needs to be updated in footer

### ISSUE THREAD

**Issue by girliemac** [uswds/uswds-site#776]
## Description
The Slack logo needs to be updated in the footer!  

## Additional information
The new logo in svg is available on: 
https://brandfolder.com/slack/logos

Thanks 🙇‍♀️ 
(I gave up creating the SVG asset in the right format to send a PR)

**Comment by thisisdano** [comment]
Thanks for pointing this out — it's next on my list and I'm sorry it's taken me so long to get to it!
