### ISSUE TITLE
Some links in developer docs redirect to the wrong url

### ISSUE THREAD

**Issue by pawjob** [uswds/uswds-site#778]
## Description
Under the "Customization, Theming, and Tokens" section in the developer docs, the links that are supposed to redirect to pages in "Design tokens" instead try to go to a nonexistent "Style tokens" section. These links end up in a 404 page.

## Steps to reproduce the issue
1. Go to the ["Customization, Theming, and Tokens" section](https://v2.designsystem.digital.gov/documentation/developers/#customization-theming-and-tokens) of the [developer docs](https://v2.designsystem.digital.gov/documentation/developers)
2. Clicking the links "Style tokens section", "color", "spacing units", and "typescale" try to go to their pages (supposed to be located at "...digital.gov/**design-tokens**/[page name]") but go to "...digital.gov/**style**/[page name]" and end up in a 404 page instead.

**Comment by saracope** [comment]
Thanks for pointing this out!
