### ISSUE TITLE
Documentation for z-index tokens uses the wrong prefix

### ISSUE THREAD

**Issue by benwarfield-usds** [uswds/uswds-site#790]
The [z-index design token page](https://designsystem.digital.gov/design-tokens/z-index/) indicates that the utility class for applying z-index is "z-index-`z-index`", e.g. `z-index-bottom`, `z-index-400` and so forth. In fact, the utility styles are `z-bottom`, `z-400` and the like (see [src/stylesheets/utilities/rules/z-index.scss)](/uswds/uswds/blob/ea7876fba58a92a629547a538a70ce7b30cb996a/src/stylesheets/utilities/rules/z-index.scss) in the USWDS repo).

I think the other descriptions on that page are correct, but I'm not confident about that, and I'm not in a position to test at the moment.

**Comment by thisisdano** [comment]
Oof, yeah. I'll fix that now.

**Comment by thisisdano** [comment]
Proper info for this page:

**utility:** `.z-[token]`
**mixin:** `@include u-z([token])`
**function:** `z-index([token])` and `z([token])`
