### ISSUE TITLE
Unused packages

### ISSUE THREAD

**Issue by fubario** [uswds/uswds-site#792]
Hello, the following packages appear to be redundant as they aren't used anywhere after import:

 * gulp-combine-mq
https://github.com/uswds/uswds-site/blob/92f942b608ec9810c4fe65ce71c46b41981bb3e7/package.json#L80
required in **config/gulp/sass.js**:
https://github.com/uswds/uswds-site/blob/92f942b608ec9810c4fe65ce71c46b41981bb3e7/config/gulp/sass.js#L2
 * gulp-strip-css-comments
https://github.com/uswds/uswds-site/blob/92f942b608ec9810c4fe65ce71c46b41981bb3e7/package.json#L88
 required in **config/gulp/sass.js**:
https://github.com/uswds/uswds-site/blob/92f942b608ec9810c4fe65ce71c46b41981bb3e7/config/gulp/sass.js#L12

Also, possible unused variable express in config/crawl.js:
https://github.com/uswds/uswds-site/blob/92f942b608ec9810c4fe65ce71c46b41981bb3e7/config/crawl.js#L4

**Comment by thisisdano** [comment]
Thanks @fubario — I'm going to check this out now.

**Comment by fubario** [comment]
@thisisdano  might also want to check use of normalize.css 
https://github.com/uswds/uswds-site/blob/92f942b608ec9810c4fe65ce71c46b41981bb3e7/package.json#L59
It looks like it isn't used anywhere, uswds-design already includes normalize.css as part of it's package, (an older version a 3.0.3) 

https://github.com/uswds/uswds/blob/a374307b33e088a29b88c0f93c9000cb607c17d5/package.json#L123
