### ISSUE TITLE
broken banner on some What's New pages

### ISSUE THREAD

**Issue by afeld** [uswds/uswds-site#796]
## Description

The banner markup seems to be broken and showing raw tags on some pages of the site.

![Screen Shot 2019-06-25 at 1 37 09 PM](https://user-images.githubusercontent.com/86842/60120288-7e141780-974e-11e9-9db0-739dd7006062.png)

## Steps to reproduce the issue

Open these pages in a browser:

- https://designsystem.digital.gov/whats-new/updates/2017/11/08/USAGov-case-study/
- https://designsystem.digital.gov/whats-new/updates/2017/07/24/code-gov-case-study/

I confirmed in Firefox and Safari.

**Comment by thisisdano** [comment]
Thanks @afeld — I think we've seen this before and is a result of Jekyll mangling some metadata when there is a link in the description paragraph. Let's see if I can't fix it.
