### ISSUE TITLE
Layout Grid Migration Documentation typo grid-col-* instead of grid-row-*

### ISSUE THREAD

**Issue by rwaery** [uswds/uswds-site#801]
## Description

The mapping table for class names from v1 to v2 seems misspelled: https://designsystem.digital.gov/documentation/migration/#layout-grid

...
.usa-width-one-whole => .grid-row-12
.usa-width-one-half => .grid-row-6
.usa-width-one-third => .grid-row-4
.usa-width-two-thirds => .grid-row-8
.usa-width-one-fourth => .grid-row-3
.usa-width-three-fourths => .grid-row-9
.usa-width-one-sixth => .grid-row-2
.usa-width-five-sixths => .grid-row-10
.usa-width-one-twelfth => .grid-row-1
.usa-width-five-twelfths => .grid-row-5
.usa-width-seven-twelfths => .grid-row-7 
...

**Should be:**
...
.usa-width-one-whole => .grid-col-12
.usa-width-one-half => .grid-col-6
.usa-width-one-third => .grid-col-4
.usa-width-two-thirds => .grid-col-8
.usa-width-one-fourth => .grid-col-3
.usa-width-three-fourths => .grid-col-9
.usa-width-one-sixth => .grid-col-2
.usa-width-five-sixths => .grid-col-10
.usa-width-one-twelfth => .grid-col-1
.usa-width-five-twelfths => .grid-col-5
.usa-width-seven-twelfths => .grid-col-7 
..

**Comment by thisisdano** [comment]
Thanks for the heads up — this should be fixed now!
https://designsystem.digital.gov/documentation/migration/#layout-grid
