### ISSUE TITLE
Document the search JS component

### ISSUE THREAD

**Issue by afeld** [uswds/uswds-site#802]
## Description

I discovered a search JS component being used as part of [uswds-jekyll](https://github.com/18F/uswds-jekyll), but couldn't find any documentation about how to use it.

## Steps to reproduce the issue

n/a

## Additional information

- [The code](https://github.com/uswds/uswds/blob/develop/src/js/components/search.js)
- [Usage in uswds-jekyll](https://github.com/18F/uswds-jekyll/blob/c38a8d6edc51b219c78cf649ac48c622733b35be/_includes/components/header.html#L91-L103)
- The classes to look for are [`js-search-button` and `js-search-form`](https://github.com/search?q=user%3Auswds+%28%22js-search-button%22+OR+%22js-search-form%22%29&type=Code).

**Comment by thisisdano** [comment]
I think this code is for deprecated hide/show functionality. If so, we might want to remove it. 

@el-mapache do you remember why this code exists? Did we keep it only for backward compatibility? (For reference, I think there's a variant of this in use on https://cloud.gov/)

**Comment by afeijoo** [comment]
The [usage in uswds-jekyll](https://github.com/18F/uswds-jekyll/blob/c38a8d6edc51b219c78cf649ac48c622733b35be/_includes/components/header.html#L91-L103) is the standard Search.gov snippet. You may want to loop in @dawnpm too.

**Comment by el-mapache** [comment]
@thisisdano Looking at cloud.gov, it doesn't appear that it's making use of this code. I see some `jquery` that controls the form toggle behavior, but I don't see any references to the code @afeld linked here.

If the behavior is still used in the WDS I think its a good idea to document it, but if it isn't, it should be marked as deprecated and removed at some point in the near future. A note would probably need to be added to the upgrade guide as well?

Removing this shouldn't affect `uswds-jekyll` as  that gem uses version `1.6.0` of the WDS.

**Comment by dawnpm** [comment]
@afeld I've been talking with @eddietejeda about documentation for federalist users on how to use search.gov. @thisisdano I can loop you in on that if it would be helpful for your users as well.

**Comment by thisisdano** [comment]
Thanks for updates everyone. It seems that the javascript [linked above](https://github.com/uswds/uswds/blob/develop/src/js/components/search.js) is specifically related to now-deprecated functionality for showing and hiding the search input field. 

The cloud.gov example may not use this code (I'll take @el-mapache's word for it) but it does use the `js-search-button` and `js-search-form` classes. Perhaps they rewrote this functionality.

USWDS does not currently recommend using show/hide for the search input, preferring that it simply be visible only. 

See:
https://github.com/uswds/uswds/issues/1613
https://github.com/uswds/uswds/issues/1640

This code and these classes aren't used in either the `uswds-jekyll` theme nor in the Search.gov code snippet. This is good! They shouldn't use this. This code appears to be vestigial. I suggest that we mark it as deprecated, then remove it and any reference to it from the in a subsequent USWDS release.

**Comment by dawnpm** [comment]
Always visible search inputs are a good call.
