### ISSUE TITLE
Update variable $theme-navigation-width on _data/migration.yml

### ISSUE THREAD

**Issue by rwaery** [uswds/uswds-site#817]
##  Description

The theme variable $theme-navigation-width was removed as of https://github.com/uswds/uswds/commit/b4bc75b10432c237ba8ed1fff8df3b8733605719#diff-57dbb60b433b4b9e84398ddfaff57cf9L58

Is the new variable name should be $theme-header-min-width?
This also breaks the build on stylesheet that are using the deleted theme variable.

**Comment by thisisdano** [comment]
Good point, and correct. I will update these docs asap.

**Comment by thisisdano** [comment]
Yes, so there are two new variables in `2.2.0+` that control the display of the header.

| file | setting variable | controls | default |
|---|---|---|---
`uswds-theme-components` | `$theme-header-max-width` | maximum width of the header | `desktop`
`uswds-theme-components` | `$theme-header-min-width` | breakpoint at which full header shows | `desktop`

This allows you to set both the maximum width of the header and the breakpoint at which the desktop header should appear — as these may be different. `$theme-header-min-width` is the theme variable that should replace `$theme-navigation-width` in most media queries and component code. `$theme-header-max-width` is pretty much only used in `max-width` expressions.

Yes, this will break existing use of the old variable. I've tried to call out these breaking changes in the release notes.

https://github.com/uswds/uswds/releases/tag/v2.2.0
