### ISSUE TITLE
Line height documentation issues

### ISSUE THREAD

**Issue by robertromore** [uswds/uswds-site#818]
On [the line height documentation page](https://designsystem.digital.gov/utilities/paragraph-styles/#line-height) it seems like something is broken. I'm seeing `0.0` for all values in the right column and `.line-height-{font}-` in the class name in the left column.
<img width="1033" alt="Screen Shot 2019-09-26 at 1 09 44 PM" src="https://user-images.githubusercontent.com/352100/65713590-1d52ee80-e05f-11e9-8cbf-a492fce066da.png">

I'm using Chrome but I've also tested in Safari and Firefox.

**Comment by thisisdano** [comment]
Oof — thanks for the heads up. I'll check on this.

**Comment by maya** [comment]
This is also an issue for font size which shows everything at 0.0px:
<img width="951" alt="Screen Shot 2019-11-12 at 10 31 28 AM" src="https://user-images.githubusercontent.com/5249443/68699318-a3f05c00-0537-11ea-85bb-4b75eed79dc7.png">

**Comment by thisisdano** [comment]
Yeah, this is on my list for today

**Comment by thisisdano** [comment]
Looks like this is a result of https://github.com/jekyll/jekyll/issues/7820
