### ISSUE TITLE
.main-content needs to display: block

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds-site#820]
For some reason, this is set to `display: inline-block` and it's messing with print rendering in Firefox.

**Comment by ardouglass** [comment]
I was trying to explore the website and noticed that I couldn't click on any side navigation. When I set `.main-content` back to `display: inline-block`, it let me click on them again. Looks like this alone isn't a great fix. Maybe put the `display: inline-block` inside a print media query instead?

**Comment by thisisdano** [comment]
Oof. Thanks for the heads up. Lemme dig into this some more.
