### ISSUE TITLE
Add required links to footer

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds-site#825]
Description TK. Do we use the anchor here?

**Comment by mejiaj** [comment]
@thisisdano, happy to help on this if you can provide some guidance.

**Comment by thisisdano** [comment]
We will be doing this as we develop and build the USWDS anchor component. So I'm going to close this one in favor of a new set of issues around the anchor.

**Comment by afeijoo** [comment]
The identifer (formerly anchor) is now done: https://github.com/uswds/uswds-site/issues/1067.
