### ISSUE TITLE
Possible issue with overriding settings in settings/_uswds-theme-typography.scss

### ISSUE THREAD

**Issue by fubario** [uswds/uswds-site#839]
Hello, typography settings refers to an unused variable  $theme-title-font-size, which has been renamed to  $theme-display-font-size

https://github.com/uswds/uswds-site/blob/483b0a47beff40e41390b53d2a5ddd9502ee2f37/css/settings/_uswds-theme-typography.scss#L410

This is the commit where it was renamed:
https://github.com/uswds/uswds/commit/a0d413d979130781676f20b216a585c58bb919d8?diff=unified#diff-69dac101ebc9ed204164c212c138c8bd

**Comment by thisisdano** [comment]
Good catch. We're working on an improvement that should better surface these issues in https://github.com/uswds/uswds/pull/3261

But for now, I'll go in and fix this — and see what happens!
