### ISSUE TITLE
Link to v1 docs is hidden

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds-site#850]
It needs to be in a more obvious location.

**Comment by afeijoo** [comment]
+1 on making it more obvious. Someone else asked, "Is there any way to access the USWDS 1.x documentation?" on #uswds-public on Feb 24.

**Comment by afeijoo** [comment]
+2.  On Feb 26, another person asked in Slack, "is there a way to get to the old V1 docs site for a page that hasn't migrated?"

**Comment by mejiaj** [comment]
@afeijoo @thisisdano , there's a PR #868 open for this. I'd love to get your thoughts on it.
