### ISSUE TITLE
Typo in maturity-model.md

### ISSUE THREAD

**Issue by saracope** [uswds/uswds-site#857]
User reported a typo on the [uswds-site/pages/documentation/maturity-model.md](https://github.com/uswds/uswds-site/blob/c37e9fdb53c93584ae3a1bbc5c5da31005579e62/pages/documentation/maturity-model.md) page

### URL / Link to page
https://designsystem.digital.gov/maturity-model/#level-2-follow-user-experience-guidance

### What seems to be the problem (1 sentence)
Under the Heading: Level 2: Following User... 
"You should follow the UX guidance **even it you** don’t use USWDS code." 

Have a look at what this page used to be like in the Wayback Machine
https://web.archive.org/web/*/digitalgov.gov

**Comment by saracope** [comment]
@onelisadunc-dev

**Comment by mejiaj** [comment]
Thanks for reporting @saracope! I've opened a PR with that fix.
