### ISSUE TITLE
Links that are missing trailing slashes are broken

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds-site#865]
https://designsystem.digital.gov/maturity-model/ == `ok`
https://designsystem.digital.gov/maturity-model == `broken`

Can we make it so both of these urls resolve?

**Comment by mejiaj** [comment]
@thisisdano steps to reproduce? Works for me on:

Firefox (74.0b3 [64-bit])
Chrome (Version 81.0.4044.17)
Safari (Version 13.0.5 [15608.5.11]).

**Comment by thisisdano** [comment]
Huh!

**Comment by thisisdano** [comment]
I'd definitely never noticed this until today. Happening in all my browsers...

**Comment by mejiaj** [comment]
Does it take you to a 404?

**Comment by thisisdano** [comment]
I redirects to `https://designsystem.digital.gov/site/uswds/uswds-site/maturity-model/` and shows a 404

**Comment by thisisdano** [comment]
no longer an issue
