### ISSUE TITLE
Graphic-list on homepage is displaying incorrectly.

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds-site#866]
### Before
https://web.archive.org/web/20200209221607/https://designsystem.digital.gov/
![image](https://user-images.githubusercontent.com/3385219/75073059-52545780-54be-11ea-8ed4-1283d4d3b3c9.png)

### Currently
![image](https://user-images.githubusercontent.com/3385219/75073098-61d3a080-54be-11ea-8890-ad1a91985009.png)

Tablet grid styles are compiling after desktop.
![image](https://user-images.githubusercontent.com/3385219/75074529-7ebda300-54c1-11ea-9d18-2a6b052e7f64.png)

## Steps to reproduce the issue

1. Go to https://designsystem.digital.gov/
2. View graphic-list section below hero

**Comment by thisisdano** [comment]
I was just about to add this issue.

**Comment by thisisdano** [comment]
Looks like we should disable the `forcedMediaMerge` key in csso. I'd also like to do this in `uswds` and release a `2.5.1` patch. This will result in a slightly larger file, but, counterintuitively, one that compresses better with gzip.
