### ISSUE TITLE
Add AChecker as an accessibility resource 

### ISSUE THREAD

**Issue by afeijoo** [uswds/uswds-site#869]
Capturing this feedback on the maturity model: 

TTS' mobile testing program uses [AChecker](https://achecker.ca/checker/). Consider adding it as a resource under https://designsystem.digital.gov/design-principles/#embrace-accessibility.

**Comment by mejiaj** [comment]
Closed PR since AChecker is getting shutdown, will close this issue as well.

![image](https://user-images.githubusercontent.com/3385219/115586955-bcb78200-a292-11eb-8027-234bf8aa6b73.png)
