### ISSUE TITLE
Add SAM.gov resources to the implementations documentation

### ISSUE THREAD

**Issue by afeijoo** [uswds/uswds-site#870]
Consider adding [SAM.gov](https://sam.gov/SAM/) resources for their design system theme, Angular component library, and prototypes to the [USWDS implementations](https://designsystem.digital.gov/documentation/implementations/) page.

- **Sam-Styles** - https://github.com/GSA/sam-styles - HTML/CSS design library built on USWDS 2.0 and [Fractal](https://github.com/frctl).
- **Sam-Design-System** - https://github.com/GSA/sam-design-system - Common Angular components integrated with `sam-styles` css framework.
- **Sam-Prototypes** - https://github.com/GSA/sam-prototypes - A test application that incorporates `sam-styles` and `sam-design-system` components with real-world examples.

**Comment by brunerae** [comment]
Closing as complete https://designsystem.digital.gov/documentation/implementations/
