### ISSUE TITLE
Add link to Figma Community resource file

### ISSUE THREAD

**Issue by afeijoo** [uswds/uswds-site#875]
Add a link to https://www.figma.com/community/file/817531077036545462 on the USWDS `For designers` page at https://designsystem.digital.gov/documentation/designers/

Source: https://gsa-tts.slack.com/archives/C3F14AHSQ/p1583869188104500

**Comment by mejiaj** [comment]
Would this require us to get rid of this alert?

![image](https://user-images.githubusercontent.com/3385219/84064714-b7a65880-a988-11ea-9ef7-872117ab699e.png)
