### ISSUE TITLE
Make it easier to find, suggest, and track pattern and component requests

### ISSUE THREAD

**Issue by afeijoo** [uswds/uswds-site#884]
As a USWDS customer
I would like to know what's in the USWDS backlog
So I can align my own work and planning

See, for example, https://design-system.service.gov.uk/community/backlog/

**Comment by thisisdano** [comment]
See also https://github.com/alphagov/govuk-design-system-backlog/projects/1

**Comment by elisaachen** [comment]
So same as #1465 ?

**Comment by thisisdano** [comment]
I think it's related, but it's one additional step to help everyone understand what's still required to get a pattern or component into our roadmap. This could be accomplished by assigning new pattern and new component request issues into a second project responsible fo tracking needs and status specific to this type of request. It also leads me to believe that there may be room for new Issue Templates specifically for proposing a new pattern or a new component

**Comment by thisisdano** [comment]
Added a new issue about New Pattern/Component issue templates: https://github.com/uswds/uswds-team/issues/182

**Comment by brunerae** [comment]
Closing this as completed by our Component Lifecycle Proposal Process.
