### ISSUE TITLE
Update guidance for date input numeric fields

### ISSUE THREAD

**Issue by jaredcunha** [uswds/uswds-site#891]
## User Story

As a front-end developer, I need updated guidance for the numeric fields in the date input.

### Examples
- [GDS rationale](https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/)

**Comment by thisisdano** [comment]
Done in #890 
Released in https://github.com/uswds/uswds/releases/tag/v2.7.0
