### ISSUE TITLE
Add Twitter button to USWDS website

### ISSUE THREAD

**Issue by afeijoo** [uswds/uswds-site#893]
Add a Twitter button to the USWDS website that links to the USWDS Twitter profile to help people find the account. This is step 6 in OCS's social media SOP to verify accounts.

USWDS website: https://designsystem.digital.gov/
USWDS Twitter profile: https://twitter.com/USWDS

**Comment by mejiaj** [comment]
@afeijoo would this live in the footer area?

![image](https://user-images.githubusercontent.com/3385219/78071256-cbb75380-7362-11ea-91b5-ebebc5b60fef.png)
