### ISSUE TITLE
Possible false positive in `npm run crawl`.

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds-site#909]
## Description

Build failed on commit 1a91ae5. When I tested `npm run crawl` locally, I got the following:

```bash
uswds-site on  aff-about-history [$!] via ⬢ v13.0.1 via 💎 v2.6.3 took 3s
↳ npm run crawl

> @ crawl /Users/jamesmejia/web/uswds-site
> node config/crawl.js

Error: duplicate id attrs found at /form-controls/07-range-input/:
  range-slider
Error: 404 for /about/history/ in [object Object]
  99 referrer(s) including at least: [
  '/',
  '/website-standards/',
  '/download/',
  '/how-to-use-uswds/',
  '/design-principles/'
]
Error: 404 for /about/history/ in [object Object]
  117 referrer(s) including at least: [
  '/',
  '/how-to-use-uswds/',
  '/website-standards/',
  '/download/',
  '/design-principles/'
]
3 error(s) and 0 warning(s) found.
Alas.
```

`range-slider` was never modified, yet it showed up as a duplicate ID. It seems to check this url: `/form-controls/07-range-input/`.

If you take a look at:
https://designsystem.digital.gov/form-controls/07-range-input/

You'll see there is indeed a duplicate ID on the header and the range input.

![image](https://user-images.githubusercontent.com/3385219/78273415-6be0ba00-74d4-11ea-8e44-bdb1e1bef808.png)

![image](https://user-images.githubusercontent.com/3385219/78273469-7a2ed600-74d4-11ea-8218-a5565efb3f7d.png)

## Steps to reproduce the issue

1. Delete a page like `history.md` locally.
2. Run `npm run crawl`
3. You should error on the page you just deleted but also range-slider.

## Additional information

The styleguide page it uses only adds the page title as an id.

https://github.com/uswds/uswds-site/blob/ae7c6d7e7403c57f786a9d28566bd4cf531e6f1e/_layouts/styleguide.html#L23

**Comment by thisisdano** [comment]
Is this still an issue?

**Comment by thisisdano** [comment]
No longer an issue
