### ISSUE TITLE
Update Product Principles labels for consistency

### ISSUE THREAD

**Issue by afeijoo** [uswds/uswds-site#921]
**Description**
As a user I want to understand the difference between the values that support the design system and the design principles that serve as guidelines

**Requirement**
1. Update page title from `Product principles` to `Our values`
1. Update left nav from `Product principles` to `Our values`
1. Update url to read `/about/our-values/` and check for redirects
1. Link `Design Principles` in first paragraph to https://designsystem.digital.gov/design-principles/
1. Delete yellow call out box; no longer needed

**Supporting Data**
Addresses confusion around the word “principles” and promotes design principles as critical part of the process to adopting the design system.

<img width="816" alt="Screen Shot 2020-04-13 at 11 39 22 AM" src="https://user-images.githubusercontent.com/400690/79134301-7a07c380-7d7b-11ea-916f-64c649775780.png">

**Comment by thisisdano** [comment]
Done in https://github.com/uswds/uswds-site/pull/932
