### ISSUE TITLE
Colors: Site should ingest USWDS Color tokens.

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds-site#931]
## Description

Jekyll site should ingest USWDS color tokens JSON file so improve correctness of documentation. Currently they're separated and can get out of sync and cause confusion.

## Additional information [optional]

Related:
https://github.com/uswds/uswds/issues/3398

**Comment by mejiaj** [comment]
Jekyll can take [JSON](https://jekyllrb.com/docs/datafiles/), but it might be better if we had a single place to update and have both of them consume that single source of data.

**Comment by thisisdano** [comment]
Closing since this probably won't make it on the 2021 roadmap. Tagging for future consideration
