### ISSUE TITLE
System color sidenav order inconsistent

### ISSUE THREAD

**Issue by maya** [uswds/uswds-site#936]
In the sidenav order, you start with:
- color warm
- color
- color cool

but at the blues switch to 
- color cool
- color 
- color warm

Should these be the same? Or is this intentional?

**Comment by maya** [comment]
nvm, i think this has to do with the color wheel

**Comment by maya** [comment]
Not sure it follows the color wheel either, so will reopen to confirm:

<img width="783" alt="Screen Shot 2020-04-30 at 4 27 14 PM" src="https://user-images.githubusercontent.com/5249443/80768737-1235d480-8b00-11ea-8c90-cdeaa4b308ff.png">

<img src="https://user-images.githubusercontent.com/5249443/80768717-021df500-8b00-11ea-8b07-0d4547698d01.png" width="30%">

**Comment by thisisdano** [comment]
Yes, let's start with Red Cool

**Comment by thisisdano** [comment]
Yup, move around the color wheel clockwise, starting with `red cool`
