### ISSUE TITLE
Verify blogpost guidance

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds-site#953]
## Description

Is this guidance still correct?
https://github.com/uswds/uswds-site/blob/master/_posts/README.md

Trying to create a blog post from command-line results in following:
```zsh
fatal: 'jekyll draft' could not be found. You may need to install the jekyll-draft gem or a related gem to be able to use this subcommand.
```

## Steps to reproduce the issue

1. `cd uswds-site`
2. Enter `bundle exec jekyll draft "my-blog-title"`

**Comment by thisisdano** [comment]
This would appear to be out of date. We don't have `jekyll-compose` in our gemfile. This happens to be the first time I've seen these docs!

**Comment by mejiaj** [comment]
Verified, thank you! Closing in favor of #1584.
