### ISSUE TITLE
Character count code example is missing required data-maxlength attribute

### ISSUE THREAD

**Issue by ajanickiv** [uswds/uswds-site#968]
## Description

To get the character count component to function like the examples, the developer needs to set the data-maxlength value on the usa-character-count div. This is not included in the code in the component code accordion.

Also, in order to get the character count message to become invalid, the maxlength attribute on the input needs to be set to a value greater than what the data-maxlength attribute is set to or not set at all. The examples seem to not set it at all. This is different than the code in the component code accordion.

Also, the default message in the example is different than in the code in the component code accordion.

https://designsystem.digital.gov/components/form-controls/#character-count

## Additional information
Code Example
```
<form class="usa-form">
  <div class="usa-character-count">
    <div class="usa-form-group">
      <label class="usa-label" for="with-hint-input">
        Text input
      </label>
      <span id="with-hint-input-hint" class="usa-hint">
        This is an input with a character counter.
      </span>
      <input class="usa-input usa-character-count__field" id="with-hint-input" maxlength="25" name="with-hint-input" aria-describedby="with-hint-input-info with-hint-input-hint">
    </div>
    <span id="with-hint-input-info" class="usa-hint usa-character-count__message" aria-live="polite">
      You can enter up to 25 characters
    </span>
  </div>
</form>
```
Code that mimics the functionality of the example
```
<form class="usa-form">
  <div class="usa-character-count" data-maxlength="25">
    <div class="usa-form-group">
      <label class="usa-label" for="with-hint-input">
        Text input
      </label>
      <span id="with-hint-input-hint" class="usa-hint">
        This is an input with a character counter.
      </span>
      <input class="usa-input usa-character-count__field" id="with-hint-input" name="with-hint-input" aria-describedby="with-hint-input-info with-hint-input-hint">
    </div>
    <span id="with-hint-input-info" class="usa-hint usa-character-count__message" aria-live="polite">
      25 characters allowed
    </span>
  </div>
</form>
```

**Comment by wbyoko** [comment]
@ajanickiv There should actually be an initialization/enhancement process that runs to update those attributes. Is the component in your situation being added dynamically? If so, could you explain the tools your using.

**Comment by ajanickiv** [comment]
It is an Angular app so yes, everything is a component and they are loaded dynamically. We take your library and build reusable Angular components out of it like this:
![image](https://user-images.githubusercontent.com/16595489/83802214-588ad000-a678-11ea-8f96-fff151bf87c7.png)
I can set the attributes explicitly and it works fine. So an app just running the USWDS JS app works without setting those attributes explicitly?

One other note, shouldn't the character count div be inside the usa-form-group div? That way the vertical error bar would stretch down to the bottom of character count message in the case of an error.

**Comment by ajanickiv** [comment]
If I import the characterCount module into my component's TypeScript class, then the component works like the examples on the site work without explicitly setting data-maxlength, etc.

`import {characterCount} from 'uswds/dist/js/uswds';`

Is this the proper way to import the module?

**Comment by wbyoko** [comment]
I believe it would be something like this.

```
import USWDS from 'uswds';
const { characterCount } = USWDS.components;

characterCount.on(ref); // for the enhancement and event listening
characterCount.init(ref); // for just the enhancement / event listening should be running somewhere else via an 'on' call
characterCount.off(ref); // for tearing down the component and event listening
```

**Comment by ajanickiv** [comment]
I can import USWDS like you mention, but the USWDS object does not have a component key, only keys and polyfill as seen here... (I tried making a stackblitz but the way to implement uswds on that application does not match what happens in a typical angular app)

![image](https://user-images.githubusercontent.com/16595489/84025872-4780de00-a95a-11ea-87f7-284706692c92.png)

I tried adding the components JavaScript to the global window scope as well, but that hasn't worked either.

**Comment by wbyoko** [comment]
@thisisdano would you know the best way to include USWDS into a javascript application?

**Comment by thisisdano** [comment]
Hm, unfortunately, I would not

**Comment by ajanickiv** [comment]
So I take it that there is no way for me to get access to those methods like `on()`, `init()`, `off()` in my app? Without that, I can't use the components that do DOM initialization/enhancements since Angular apps are based on a dynamic component architecture.

**Comment by wbyoko** [comment]
Are you using a bundler like spoken about here? https://designsystem.digital.gov/documentation/developers/#js-customization

**Comment by ajanickiv** [comment]
It is Angular 7.X which uses Webpack. The USWDS is defined as a dependency in the package.json. We then import the library through the angular.json file like this
```
 "assets": [
              "src/assets",
              {
                "glob": "*",
                "input": "node_modules/uswds/dist/fonts",
                "output": "assets/uswds/dist/fonts"
              },
              {
                "glob": "*",
                "input": "node_modules/uswds/dist/img",
                "output": "assets/uswds/dist/img"
              },
            ],
            "styles": [
              "node_modules/uswds/dist/css/uswds.css",
              "src/styles.css"
            ],
            "scripts": [
              "node_modules/uswds/dist/js/uswds.min.js"
            ]
```

**Comment by jAigret-Bix** [comment]
@chazchumley  needs to be reproduced and tested. Verify issues described.

**Comment by chazchumley** [comment]
@jAigret-Bix I tested this and the JavaScript properly places the `data-maxlength` attribute on the `usa-character-count` element based on the maxlength attribute on the `usa-character-count__field`.  There is **no need to manually** add the data-maxlength attribute.

**Comment by sarnikbixal** [comment]
The component is working as intended. There is no need to manually add the data-max-length attribute as it will be appended via runtime to the container component from the input maxlength attribute.

There is a nuance for using modern libraries such as Angular/React. 

** To import an individual component **

```
import USWDS from '../node_modules/uswds/src/js/components';
const { characterCount } = USWDS; // deconstruct your components here
```

Please see below how to implement for each:

React (hooks): 

```
function App() {
  useEffect(() => {
     characterCount.on(ref);
  })
}
```


Angular (hooks): 

```
export class App implements OnInit {
  constructor() {}

  ngOnInit() {
    characterCount.on(ref);
  }
}
```

**Comment by jAigret-Bix** [comment]
New issue #3658 generated to update documentation.
