### ISSUE TITLE
USWDS - Docs: font-weight function docs are incorrect

### ISSUE THREAD

**Issue by fafnirical** [uswds/uswds-site#989]
## Description

Expected a `weight` function to exist in USWDS, per https://designsystem.digital.gov/design-tokens/typesetting/font-weight/#using-font-weight-tokens. This function doesn't appear to exist, but there is a `font-weight` function.

Proposed change: change the function name from `weight` to `font-weight` in the docs, so that it accurately represents the USWDS function name.

## Steps to reproduce the issue

1. Try to use `font-weight: weight('bold')` in Sass
2. Observe `font-weight: weight("bold")` in output CSS
3. Use `font-weight: font-weight('bold')` in Sass
4. Observe `font-weight: 700` in output CSS, as expected

## Additional information

* Relevant code in USWDS: https://github.com/uswds/uswds/blob/v2.7.1/src/stylesheets/core/_functions.scss#L1467-L1483

**Comment by thisisdano** [comment]
Yes, this is an error. Both `font-weight()` and `fw()` should work for font weight.

**Comment by fafnirical** [comment]
I'll submit a PR changing it from `weight` to `font-weight`
