### ISSUE TITLE
Add Events Template

### ISSUE THREAD

**Issue by saracope** [uswds/uswds-site#99]
I created an Events page template based on the Landing page template in the WDS am interested in contributing that back to the site for other folks to possibly use. We specifically created it to use for hackathons. 

I wanted to check to see what the team thought about including it as a Page Template before starting the PR. Thanks!

Preview:
![screencapture-saracope-github-io-uswds-template-eventpage-1484141619044](https://cloud.githubusercontent.com/assets/2197515/21850729/fb1f47a4-d7d9-11e6-96bb-52b36d31f706.png)

**Comment by saracope** [comment]
Just wondering if anyone had thoughts on adding this type of template. Thanks!

**Comment by juliaelman** [comment]
@saracope this is great work and thank you for submitting this issue.

We have a set of [design contribution guidelines](https://github.com/18F/web-design-standards/wiki/Contribution-Guidelines:-Design) in our wiki. Please take a moment to review these guidelines. 

Also, our user research lead @bradnunnally will respond to your submission with any questions or suggestions.

**Comment by bradnunnally** [comment]
Hi @saracope - This looks really good and the structure of things is really solid I only have one question, why did you go with a single page design? I can see how the template as is could be used as a single page or expanded to include multiple pages (which is good because it shows flexibility). 

Thanks!

**Comment by saracope** [comment]
@bradnunnally - We'll be using this to add our open gov events to the open.gsa.gov website so it makes sense for us to go with a single page for each event.

**Comment by saracope** [comment]
Here's an example of how we did our last hackathon: 
http://open.gsa.gov/grace-hopper-hackathon/event.html

**Comment by bradnunnally** [comment]
That's a great example @saracope, would it be possible to use the hero image (or one like it) from the Grace Hooper Hackathon in the template? It has more of an "event" feel to it. 

Also, after taking a closer look, the only other feedback I would have is to explore other ways to highlight the time, place, and sponsoring agency.

This is great though and I can see a lot of other teams benefitting from having a template like this to work from.

**Comment by saracope** [comment]
@bradnunnally - Yes, will change the hero image. I can run through the photos from our Dec. hackathon to see if there's anything that would work. 
Will have another look at the time/place/agency section. 👍

**Comment by maya** [comment]
Your suggestion is appreciated, however it is not on the current product roadmap.
