### ISSUE TITLE
Review and update Google Analytics settings

### ISSUE THREAD

**Issue by afeijoo** [uswds/uswds-site#991]
A a follow-up to https://github.com/uswds/uswds-site/pull/972, let's look at the Google Analytics settings for the 4 USWDS websites and update them best practices (such as for events).

1. https://designsystem.digital.gov
1. https://components.designsystem.digital.gov
1. https://public-sans.digital.gov
1. https://v1.designsystem.digital.gov

**Comment by thisisdano** [comment]
I'm not sure what this issue would entail. Do we still want or need to do this?

**Comment by afeijoo** [comment]
Closing this issue for now; we can address later as needed.
