### ISSUE TITLE
Update the example data viz charts

### ISSUE THREAD

**Issue by afeijoo** [uswds/uswds-site#992]
In the example bar chart on https://designsystem.digital.gov/components/data-visualizations/, the label for `Great Smoky Mountains National Park` is cut off. See the screenshot below.

<img width="770" alt="Screen Shot 2020-07-01 at 9 22 39 AM" src="https://user-images.githubusercontent.com/400690/86249095-cc879d80-bb7c-11ea-8f7d-2ad6f8c6a6b9.png">

**Comment by afeijoo** [comment]
The example line chart cuts off `Theodore Roosevelt` too.

<img width="629" alt="Screen Shot 2020-07-01 at 9 37 48 AM" src="https://user-images.githubusercontent.com/400690/86250457-98ad7780-bb7e-11ea-9e8c-db889a4d24bb.png">

**Comment by thisisdano** [comment]
I don't see errors on my machine in any of my local browsers. The font also looks bigger in your screenshots than I see it — do you have any custom font-size settings in your browser that might be affecting the display?

**Comment by afeijoo** [comment]
Yes, I do have my font size set to `Large`. The text is cut off at all zoom settings.

**Comment by thisisdano** [comment]
SVGs might not be smart enough to adequately adapt to browser font settings. @jaredcunha do you have any thoughts here?

**Comment by jaredcunha** [comment]
Hmmm - That's something I'll have to look into. I'm not sure offhand how to get a browser to tap into that either. @afeijoo what browser are you using?

**Comment by afeijoo** [comment]
I'm using Chrome. Go to chrome://settings/appearance > Font size > Large.

**Comment by jaredcunha** [comment]
It looks like handling the font-size's in the SVG's CSS might address this somewhat? I'll take a further look into that.

**Comment by jaredcunha** [comment]
@afeijoo @thisisdano I think I have a fix for this. Mind taking a look at Federalist and making sure it looks okay?

https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/svg-font-sizing/components/data-visualizations/

**Comment by afeijoo** [comment]
LGTM at a variety of font size and zoom settings in Chrome.
