### ISSUE TITLE
Draft sample contract language for 21st Century IDEA

### ISSUE THREAD

**Issue by afeijoo** [uswds/uswds-site#995]
## Sample contract language

A short post on how to document requirements related to website modernization in contracts.

### User story 1

As a federal program manager
I want to write include language in my contract for website development and PM support 
so my website complies with 21st Century IDEA

### User story 2
As a federal program manager
I want to write include language in my contract for website development and PM support 
so I can evaluate vendors' ability to use the USWDS maturity model and demonstrate increased maturity over time
and select the best vendor

## Additional information [optional]

- [x] [Draft in gDoc](https://docs.google.com/document/d/1Dd5q9wgzSIqdgNcvslMPVFXPdYGEVLIX0HRvjuRy_JM/edit?ts=5f039c0c) 🔒 
- [x] Route for review and approval
- [ ] Publish on Digital.gov or designsystem.digital.gov (and crosspost on other site)

**Comment by afeijoo** [comment]
Pending comms review and approval.

**Comment by jpgsa** [comment]
Comms and FAS approved on 7/26. We're ready to publish @thisisdano! cc @afeijoo

**Comment by afeijoo** [comment]
@thisisdano and @katieekline This [sample contract language for 21st Century IDEA](https://docs.google.com/document/d/1Dd5q9wgzSIqdgNcvslMPVFXPdYGEVLIX0HRvjuRy_JM/edit) is ready to publish.

Should it be published on Digital.gov or designsystem.digital.gov?

**Comment by thisisdano** [comment]
This feels like it could be a standalone documentation page instead of a blog post. What do you think about that?

**Comment by afeijoo** [comment]
Yes, it is an evergreen resource.

**Comment by afeijoo** [comment]
Draft is done. Created #1025 to publish this resource.
